// ============================================================
// Micro-Guides — Universal Rewrites
// Same neuroscience, reframed for any overwhelmed mother
// No ADHD label — centered on depletion, overload, and the
// lived experience of mothering under impossible conditions
// ============================================================

import type { MicroGuide } from "./types"

export const MICRO_GUIDES_UNIVERSAL: MicroGuide[] = [
  // ---- EXECUTIVE FUNCTION ----
  {
    id: "univ-task-initiation",
    title: "Why You Can't 'Just Start'",
    subtitle: "It's not laziness. Your brain is running on empty.",
    category: "executive-function",
    archetypes: ["plate-spinner", "running-on-empty", "weight-bearer"],
    dimensions: ["cognitive-load"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You're staring at the dishes. You know they need doing. You want them done. But your body won't move. This isn't a character flaw. It's what happens when your prefrontal cortex — the part of your brain responsible for initiating action — has been running on fumes all day.",
      "Your brain has a 'starter motor' that converts intention into action. When you're well-rested and resourced, it fires easily. But after a day of constant decisions, interrupted sleep, sensory overload, and emotional labour, that starter motor weakens. The gap between 'I want to do this' and 'my body is doing this' widens. The doing isn't the problem. The starting is.",
      "This is why you can spend 45 minutes dreading a task that takes 10 minutes. Your brain literally cannot generate the activation signal. It's the same neurology behind why exhausted doctors make worse decisions at the end of shifts, why air traffic controllers have mandatory breaks. Cognitive resources are finite. Yours have been spent.",
      "The workaround isn't willpower. It's what researchers call 'body-first initiation.' Instead of waiting for your brain to send the start signal, you move your body toward the task physically. Stand up. Walk to the sink. Touch the first dish. Don't commit to finishing — just commit to touching. Movement often triggers the brain to engage because you've bypassed the broken starter and push-started the engine instead.",
    ],
    tryThis: "Next time you're stuck: stand up, walk to the task, and touch one object related to it. Don't commit to doing it. Just touch it. See what happens. You're push-starting your brain.",
    remember: "You're not lazy. Your brain's activation system is depleted. Move your body first — your brain will follow.",
  },
  {
    id: "univ-time-blindness",
    title: "Why You Thought You Had 20 Minutes (You Had 5)",
    subtitle: "Your internal clock isn't broken. It's overwhelmed.",
    category: "executive-function",
    archetypes: ["plate-spinner", "storm-weatherer"],
    dimensions: ["cognitive-load", "system-friction"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You genuinely believed you had 20 minutes. You had 5. This isn't carelessness — it's what happens when your brain is juggling too many things to accurately track time passing. Researchers call it 'time blindness' and it intensifies dramatically under cognitive load.",
      "When your brain is resourced, it maintains a rough internal sense of time — you can feel the difference between 5 and 20 minutes without a clock. But when your working memory is full (which for mothers is essentially always), time tracking gets deprioritised. Time becomes either 'now' or 'not now.' And 'not now' could be 5 minutes or 5 hours. They feel identical.",
      "This is why transitions are brutal — you can't feel the time running out until it's gone. It's why you're chronically late despite trying. It's why 'just leave earlier' doesn't work. You can't leave earlier if you can't feel 'earlier' approaching. Your brain is spending its resources on the 40 other things it's tracking.",
      "The solution isn't trying harder. It's externalising time. Timers, alarms, visual countdowns — anything that makes invisible time visible. Your brain needs time translated into something it can perceive: sound, sight, movement. Let external tools do what your overloaded brain can't.",
    ],
    tryThis: "Set a timer for 10 minutes and do nothing. Just sit. Notice how long 10 minutes actually feels versus how long you thought it would feel. That gap is your time blindness showing itself.",
    remember: "You're not careless with time. Your overloaded brain can't track it accurately. Make time visible — alarms, timers, clocks in every room.",
  },
  {
    id: "univ-decision-fatigue",
    title: "Why You Can't Decide What's for Dinner",
    subtitle: "Your brain made 400 decisions today. It's out of fuel.",
    category: "executive-function",
    archetypes: ["plate-spinner", "invisible-architect", "weight-bearer"],
    dimensions: ["cognitive-load", "system-friction"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "It's 4pm. Someone asks what's for dinner. Your brain goes completely blank. Not because you don't know how to cook — because you've already made 400 decisions today and your prefrontal cortex has run out of fuel.",
      "Decision-making uses the same cognitive resources as self-control, planning, and emotional regulation. Every choice — what to wear, which route to take, how to respond to that text, what to feed the toddler for snack — draws from the same limited tank. By afternoon, the tank is empty. This is why judges give harsher sentences before lunch. Why CEOs wear the same outfit. The resource is real and finite.",
      "For mothers, this tank depletes faster because nothing is automated. Every decision feels novel because the variables keep changing — the child's mood, the schedule shift, the unexpected need. You can't autopilot through a day that changes every 15 minutes. Every decision costs full price.",
      "This is why meal planning, capsule wardrobes, and routines aren't luxuries — they're cognitive survival tools. Every decision you eliminate in advance is one you don't have to make when your tank is empty. You're not being rigid. You're being strategic.",
    ],
    tryThis: "Identify your top 3 daily 'decision drains' — the recurring choices that exhaust you most. Eliminate ONE by making it automatic (same breakfast every day, same outfit formula, same Tuesday dinner).",
    remember: "You're not indecisive. You're depleted. Every decision you pre-make is fuel saved for the ones that actually matter.",
  },
  {
    id: "univ-object-permanence",
    title: "Out of Sight, Out of Mind — Literally",
    subtitle: "You're not forgetful. Your brain drops what it can't see.",
    category: "executive-function",
    archetypes: ["plate-spinner", "storm-weatherer", "invisible-architect"],
    dimensions: ["cognitive-load", "system-friction"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "The bill you forgot to pay wasn't laziness. The friend you haven't texted in three weeks isn't because you don't care. The food in the back of the fridge you forgot existed isn't neglect. It's what happens when your brain is carrying too much to keep non-visible things alive in your awareness.",
      "Your working memory — the brain's active 'desktop' — can only hold a few items at once. When it's overloaded (which for mothers managing a household is constant), items that leave your visual field get pushed off the desktop. Not out of your life — out of your active awareness. You still care. You just can't hold it all.",
      "This is why you buy duplicates of things you already own. Why you forget about people you love when you don't see them regularly. Why the laundry sits in the dryer for three days. The item didn't leave your life — it left your overtaxed awareness.",
      "The fix isn't a better memory. It's a better environment. Make important things visible. Bills on the counter, not in a drawer. Reminders on your phone, not in your head. Friends in a recurring calendar event, not left to spontaneous memory. If your brain can't hold it invisibly, make it visible.",
    ],
    tryThis: "Walk through your house and identify 3 things that are 'out of sight, out of mind' right now. Move them somewhere visible. A bill on the fridge. A return by the front door. A reminder set for the friend you keep meaning to call.",
    remember: "You don't forget because you don't care. You forget because your brain is full. Make the invisible visible.",
  },
  {
    id: "univ-hyperfocus",
    title: "When You Can't Disengage",
    subtitle: "Three hours vanished. The kids were on screens. You feel terrible.",
    category: "executive-function",
    archetypes: ["plate-spinner", "the-disappeared", "invisible-architect"],
    dimensions: ["cognitive-load", "identity-erosion"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You sat down to 'quickly check' something and three hours disappeared. The kids were on screens the whole time. Dinner didn't happen. You feel guilty and confused — how can you be so distractible AND so locked in at the same time?",
      "Intense focus isn't actually about attention control. It's about disengagement failure — your brain's inability to pull away once it's locked onto something stimulating. When something novel, interesting, or emotionally activating captures your attention, your brain locks onto the reward signal and can't generate the interruption needed to pull away. It's not choosing to focus. It's being captured.",
      "This happens more when you're depleted. A resourced brain can notice 'I've been doing this too long' and disengage. A depleted brain can't generate that interruption signal. The more exhausted you are, the more likely you are to get captured — because your brain is desperately seeking the stimulation hit it's been missing all day.",
      "This is why the capture often lands on the 'wrong' things — reorganising a cupboard instead of paying bills, scrolling instead of sleeping. Your brain doesn't prioritise by importance. It prioritises by stimulation. And when you're running on empty, anything that provides a hit becomes a trap.",
    ],
    tryThis: "Set a timer before you start anything that might capture you. Not to limit the activity — but to create an external interruption that your brain can't provide internally. A 30-minute alarm that says 'check on the world.'",
    remember: "Getting captured isn't a choice. It's your exhausted brain locking onto stimulation it desperately needs. Use timers as external interrupts.",
  },
  {
    id: "univ-transitions",
    title: "Why Transitions Feel So Hard",
    subtitle: "Every 'switch' costs more than you realise.",
    category: "executive-function",
    archetypes: ["plate-spinner", "storm-weatherer", "burning-engine"],
    dimensions: ["cognitive-load", "emotional-bandwidth"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "Getting out the door. Stopping one activity to start another. Shifting from work-brain to mum-brain. Every transition feels like dragging yourself through wet concrete. It's not resistance. It's cognitive cost.",
      "Switching tasks requires your brain to: close the current mental 'file,' clear working memory, load the new context, and initiate the new behaviour. Each step requires resources. When those resources are depleted — and after a day of mothering, they always are — transitions become genuinely painful. You're not being dramatic. Your brain is paying a real tax on every switch.",
      "This is why your children saying 'Mum!' when you're in the middle of something can feel physically jarring. It's not that you don't want to respond. It's that the switch costs energy you don't have. And they're asking you to pay it instantly, without warning.",
      "Children, by nature, demand constant transitions. Breakfast to getting dressed. Playing to leaving. Bath to bed. Each one costs cognitive resources. By the end of the day, you've paid the transition tax dozens of times. The depletion you feel isn't weakness. It's the accumulated cost of constant switching.",
    ],
    tryThis: "Give yourself (and your children) transition warnings. '5 minutes until we switch.' This isn't just for them — it's for YOUR brain to begin the shutdown process. Your brain needs lead time.",
    remember: "Transitions aren't simple when you're depleted. Each one costs real cognitive resources. Build in warnings and buffer time — for yourself, not just your children.",
  },
  {
    id: "univ-working-memory",
    title: "Your Brain Has 3 Tabs, Not 30",
    subtitle: "Your life needs 30 open tabs. Your brain has 3.",
    category: "executive-function",
    archetypes: ["plate-spinner", "invisible-architect", "weight-bearer"],
    dimensions: ["cognitive-load"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "Working memory is your brain's scratchpad — the space where you hold information you're actively using. Under optimal conditions, most people can hold about 4-7 items. Under chronic stress, sleep deprivation, and cognitive overload? Often 2-3. And motherhood asks you to hold 40.",
      "This is why you walk into a room and forget why. Why you start a sentence and lose the thought. Why you can't hold a grocery list and a phone conversation simultaneously. Your scratchpad is full. Every new input pushes something else off the edge.",
      "It's also why you feel like you're 'going crazy' or worry about early dementia. You're not losing your mind. Your working memory is functioning at its actual capacity under these conditions — it's just that its actual capacity under chronic depletion is smaller than what your life demands. The gap between demand and capacity is what creates the feeling of cognitive failure.",
      "The solution isn't trying harder to remember. It's reducing what you ask your brain to hold. Write everything down. Use lists, alarms, sticky notes, phone reminders. These aren't crutches — they're tools that compensate for a real limitation under these conditions. You wouldn't run a marathon on a broken ankle and call a brace 'cheating.'",
    ],
    tryThis: "For one day, write down EVERYTHING instead of trying to remember it. Every thought, every task, every request. Notice how much lighter your brain feels when it's not trying to hold it all.",
    remember: "Your working memory has 3 tabs open. Your life has 30. The fix isn't a better brain — it's getting things OUT of your brain and into external systems.",
  },
  // ---- EXECUTIVE FUNCTION continued ----
  {
    id: "univ-wall-of-awful",
    title: "The Invisible Wall Between You and the Task",
    subtitle: "The task is 3 minutes. The dread is 6 weeks old.",
    category: "executive-function",
    archetypes: ["plate-spinner", "quiet-volcano", "the-disappeared"],
    dimensions: ["cognitive-load", "emotional-bandwidth"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You need to make a phone call. It would take 3 minutes. You've been avoiding it for 6 weeks. It's not that you're lazy. It's that between you and the task, there's an invisible wall built from every previous failure, every time you were criticised for being late, every shame spiral attached to this type of task.",
      "Psychologists call this the 'Wall of Awful.' It's the accumulated emotional weight that builds around tasks you've struggled with before. The task itself might be simple — but the emotional history makes it feel insurmountable. Each past failure adds a brick. Eventually the 3-minute task feels like climbing Everest.",
      "The wall is built brick by brick: the time you forgot and someone was disappointed. The time you did it wrong and felt stupid. The time you were late and got that look. Every negative experience adds weight. The avoidance isn't about difficulty — it's about shame.",
      "You can't willpower over the wall. You go around it, through it, or shrink it. Around: pair the task with something pleasant (call while walking outside). Through: acknowledge the wall out loud ('I'm avoiding this because of shame, not difficulty'). Shrink: do the tiniest possible version (open the email — don't reply yet).",
    ],
    tryThis: "Name one task you've been avoiding. Ask: 'What's the emotional history here? Am I afraid of the task, or the feelings attached to it?' Naming the wall often shrinks it enough to step over.",
    remember: "The task isn't hard. The feelings attached to it are. Name the wall. Then find a way around, through, or under it.",
  },
  {
    id: "univ-body-doubling",
    title: "Why You Can Only Get Things Done When Someone's There",
    subtitle: "Your brain works better with another human nearby. That's not weakness.",
    category: "executive-function",
    archetypes: ["plate-spinner", "storm-weatherer", "running-on-empty"],
    dimensions: ["cognitive-load", "system-friction"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "Alone, you can't start. But the moment someone else is in the room — even if they're doing something completely different — suddenly you can function. You can clean, organise, make calls, do paperwork. It's like their presence flips a switch in your brain. If this sounds familiar, there's a name for it: body doubling. And it's more common than you'd think.",
      "Body doubling works because depleted brains struggle with internal motivation but respond well to external cues. Another person's presence provides: a subtle sense of accountability, a mirror for 'normal' behaviour, reduced isolation (which worsens executive dysfunction), and a grounding anchor that keeps your brain from floating away into avoidance.",
      "This is why you could study in coffee shops but not at home. Why you clean before guests arrive but not for yourself. Why work feels easier alongside someone else. Your brain needs external structure that it can't generate internally when it's depleted.",
      "Body doubling doesn't require the other person to help, supervise, or even know what you're doing. They just need to exist in your space. A friend on FaceTime while you fold laundry. A YouTube 'work with me' video. Your partner reading in the same room while you do admin. The presence is the mechanism.",
    ],
    tryThis: "Next time you're stuck: call a friend and say 'Can you stay on the phone while I do this thing? You don't have to talk.' Or put on a body doubling video. Notice how much easier the task becomes with another human present — even virtually.",
    remember: "Needing someone's presence to function isn't dependency — it's a legitimate strategy for a depleted brain. Use it without shame.",
  },
  {
    id: "univ-revenge-bedtime",
    title: "Revenge Bedtime Procrastination",
    subtitle: "You're not undisciplined. You're reclaiming the only time that's yours.",
    category: "executive-function",
    archetypes: ["the-disappeared", "running-on-empty", "invisible-architect"],
    dimensions: ["cognitive-load", "identity-erosion", "physical-depletion"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "It's 11pm. You're exhausted. You should be asleep. Instead, you're scrolling, watching, reading — anything to extend this quiet window where no one needs you. You know you'll pay for it tomorrow. You do it anyway. Every night.",
      "This is revenge bedtime procrastination — and it's not a discipline failure. It's a rational response to a day where you had zero autonomy. When every waking hour belongs to someone else (children, partner, work, household), the night becomes the only time that's YOURS. Staying up is how you reclaim a sense of self.",
      "The 'revenge' is against a day that gave you nothing. Your brain is saying: 'I refuse to end this day without having one moment that was mine.' The cost (exhaustion tomorrow) feels worth it because the alternative (going to sleep without any personal time) feels like erasure.",
      "The fix isn't 'just go to bed earlier.' The fix is building personal time INTO the day so you don't have to steal it from sleep. Even 15 minutes of protected 'you time' during waking hours reduces the compulsion to stay up. Your brain needs to know it'll get something — it doesn't have to be at midnight.",
    ],
    tryThis: "Tomorrow, protect 15 minutes during the day that are explicitly yours — not productive, not for anyone else. Then notice if the pull to stay up late is slightly less intense. You're giving your brain what it's been stealing from sleep.",
    remember: "You stay up late because the day gave you nothing that was yours. The fix isn't more discipline — it's more autonomy during waking hours.",
  },
  {
    id: "univ-urgency-dependency",
    title: "Why You Only Function Under Pressure",
    subtitle: "The deadline is tomorrow. Suddenly you're a machine. Then you crash.",
    category: "executive-function",
    archetypes: ["plate-spinner", "burning-engine", "storm-weatherer"],
    dimensions: ["cognitive-load", "physical-depletion"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "The deadline is tomorrow. Suddenly, after weeks of paralysis, you're a machine. Focused, productive, unstoppable. You produce your best work in the final hours. Then you crash. And the cycle repeats.",
      "This isn't procrastination in the traditional sense. It's urgency dependency — your brain's reliance on adrenaline to compensate for insufficient activation. When a deadline creates urgency, your body releases adrenaline and norepinephrine, which temporarily boost the neurotransmitters needed for focus and action. Urgency becomes the only thing that wakes your brain up.",
      "The problem: this works short-term but destroys you long-term. The adrenaline crash is real. The chronic stress of last-minute functioning damages your health. And the pattern reinforces itself — your brain learns it only needs to activate under threat, so it stops activating any other time.",
      "Breaking urgency dependency doesn't mean eliminating deadlines. It means creating artificial urgency for non-urgent tasks: shorter timers, accountability partners, public commitments, or breaking large tasks into small ones with immediate deadlines. Give your brain the urgency signal without the actual emergency.",
    ],
    tryThis: "Next time you have a distant deadline: set a 25-minute timer and tell yourself 'I'm only doing this for 25 minutes.' The time constraint creates artificial urgency. Your brain doesn't know the difference between real and manufactured pressure.",
    remember: "You're not lazy until the last minute — your brain doesn't activate without urgency. Create artificial pressure instead of waiting for real emergencies.",
  },
  {
    id: "univ-procrastination-emotion",
    title: "Procrastination Is Emotional, Not Logical",
    subtitle: "You're not avoiding the task. You're avoiding the feeling.",
    category: "executive-function",
    archetypes: ["plate-spinner", "quiet-volcano", "the-disappeared"],
    dimensions: ["cognitive-load", "emotional-bandwidth"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You're not procrastinating because you're lazy. You're procrastinating because the task is attached to a feeling you don't want to feel — and your brain is protecting you from that feeling by avoiding the task.",
      "Research shows procrastination is fundamentally an emotion regulation problem, not a time management problem. We avoid tasks that trigger: anxiety (what if I fail?), boredom (this is unstimulating), frustration (this is hard), resentment (I shouldn't have to do this), or shame (I should have done this already).",
      "When you're already depleted, this is amplified. You feel negative emotions more intensely AND have fewer resources to push through them. The avoidance isn't a choice — it's your brain's automatic response to emotional discomfort when it has no buffer left.",
      "The intervention isn't 'just do it.' It's: identify the emotion, validate it ('of course I'm avoiding this — it makes me feel anxious'), then ask 'what's the smallest possible action that would reduce this feeling?' Often, starting for just 2 minutes dissolves the barrier because the anticipated feeling was worse than the actual experience.",
    ],
    tryThis: "Pick something you're procrastinating. Ask: 'What feeling am I avoiding by not doing this?' Name it. Then commit to 2 minutes only. Not finishing — just starting. The feeling usually dissolves once you're in motion.",
    remember: "You're not avoiding the task. You're avoiding the feeling attached to it. Name the feeling, start for 2 minutes. Motion dissolves what avoidance amplifies.",
  },
  // ---- EMOTIONAL REGULATION ----
  {
    id: "univ-rejection-sensitivity",
    title: "Why One Comment Can Ruin Your Entire Day",
    subtitle: "The pain is real. Your brain processes social hurt like physical injury.",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "the-disappeared", "burning-engine"],
    dimensions: ["emotional-bandwidth", "identity-erosion"],
    tags: ["universal"],
    readTime: "3 min",
    body: [
      "Someone made an offhand comment — maybe your partner, maybe another mum at pickup, maybe your own mother. It wasn't even that bad. But it landed like a punch and you've been replaying it for hours. The intensity of your reaction scares you.",
      "This isn't being 'too sensitive.' Brain imaging studies show that social rejection activates the same neural pathways as physical pain. Literally. Your anterior cingulate cortex responds to perceived criticism the same way it responds to being struck. The pain isn't imagined — it's neurological.",
      "This response intensifies dramatically when you're depleted. A well-resourced brain can absorb a comment, consider context, and let it pass. A depleted brain — running on no sleep, chronic stress, and zero validation — has no buffer. Every comment lands at full force because there's nothing to absorb the impact.",
      "The most important thing to know: the intensity of the feeling is real, but the story your brain tells about it is often distorted. 'She hates me' might actually be 'she was distracted.' 'I'm a failure' might be 'I made one mistake.' The feeling is valid. The interpretation needs questioning.",
    ],
    tryThis: "Next time a comment hits disproportionately hard, write down: (1) What was actually said. (2) What my brain says it means. (3) Two other possible interpretations. The gap between #2 and #3 is where the distortion lives.",
    remember: "The pain is real — your brain processes rejection like physical injury. But the story it tells about what the rejection means is often wrong. Feel the feeling. Question the narrative.",
  },
  {
    id: "univ-emotional-hangover",
    title: "The Emotional Hangover Is Real",
    subtitle: "Yesterday's meltdown is still in your body today.",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "burning-engine", "running-on-empty"],
    dimensions: ["emotional-bandwidth", "physical-depletion"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "The meltdown was yesterday. The argument was last night. But today you feel like you've been hit by a truck — foggy, exhausted, fragile. Everyone else seems to have moved on. You haven't.",
      "This is an emotional hangover — a documented neurological phenomenon. Intense emotions trigger a cascade of stress hormones (cortisol, adrenaline, norepinephrine) that take 24-72 hours to fully clear. Your body is still processing yesterday's chemical aftermath.",
      "When you're already running depleted, recovery takes even longer. The initial emotional response was more intense (because your buffer was already thin), the rumination continues feeding the stress response (you can't stop replaying it), and your baseline recovery resources are already spent.",
      "This is why you can't 'just move on.' Your nervous system hasn't finished processing. Pushing through an emotional hangover is like running on a sprained ankle — possible, but you're causing more damage and extending recovery.",
    ],
    tryThis: "After an intense emotional event, treat the next day like recovery. Lower expectations by 50%. Cancel what you can. This isn't indulgence — it's giving your nervous system the time it physiologically needs to clear stress chemicals.",
    remember: "Emotional hangovers are biochemical, not weakness. Your body needs 24-72 hours to clear stress hormones. Plan for recovery, not performance, the day after something hard.",
  },
  {
    id: "univ-emotional-permanence",
    title: "This Feeling Will Not Last Forever",
    subtitle: "When you're in it, it feels like forever. It's not.",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "burning-engine", "weight-bearer"],
    dimensions: ["emotional-bandwidth"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "When you're in it — the rage, the despair, the overwhelm — it feels like it will never end. Like this is your permanent state. Like you've always felt this way and always will. This isn't dramatic. It's how the brain works under extreme emotional load.",
      "A resourced brain maintains 'emotional object permanence' — the ability to remember that other emotional states exist even while experiencing a current one. When you're sad, you can recall being happy. But when you're depleted and overwhelmed, the current emotion fills the entire screen. There's no room for perspective.",
      "This is why a bad morning feels like a bad life. Why one fight feels like the relationship is over. Why one parenting failure feels permanent. The emotion isn't just big — it's all-consuming because your brain can't access other states from inside it.",
      "The intervention is external reminders of other states. A note on your mirror: 'This feeling is temporary.' A photo from a good day. A text saved for hard moments. You need evidence from outside the current emotional state because your brain can't generate it from inside.",
    ],
    tryThis: "Right now, while you're NOT in crisis: write yourself a note for when you are. 'This feeling will pass. You've felt this before and it ended. You are not your worst moment.' Put it somewhere you'll find it when you need it.",
    remember: "The current emotion feels permanent because your brain can't access other states while activated. It's lying about 'forever.' This will pass.",
  },
  {
    id: "univ-shame-spiral",
    title: "The Shame Spiral Is Keeping You Stuck",
    subtitle: "Shame says 'you ARE the problem.' That's a lie.",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "the-disappeared", "plate-spinner"],
    dimensions: ["emotional-bandwidth", "identity-erosion", "cognitive-load"],
    tags: ["universal"],
    readTime: "3 min",
    body: [
      "You forgot something important. Instead of just fixing it, your brain launches a full investigation: 'Why am I like this? What's wrong with me? Everyone else manages.' The shame spiral has begun — and now it's preventing you from addressing the original problem.",
      "Shame is the most paralysing emotion humans experience. Unlike guilt ('I did something bad,' which motivates repair), shame says 'I AM bad' and motivates hiding. When you're in shame, you can't problem-solve, can't take action, can't ask for help. You can only freeze, avoid, or self-punish.",
      "The shame-avoidance cycle: you avoid a task → shame builds about the avoidance → shame makes the task feel more impossible → you avoid harder → more shame accumulates → eventually the task becomes untouchable. The original 5-minute task is now surrounded by weeks of shame.",
      "Breaking the cycle requires separating behaviour from identity. 'I forgot' is not 'I am forgetful.' 'I was late' is not 'I am unreliable.' 'I yelled' is not 'I am a bad mother.' The behaviour can be addressed. The identity statement just buries you deeper.",
    ],
    tryThis: "Next time shame hits, catch the identity statement ('I'm so stupid/lazy/broken') and rewrite it as a behaviour statement ('I forgot this specific thing because my brain was full'). Behaviour is fixable. Identity is a trap.",
    remember: "Shame says 'you ARE the problem.' That's a lie that keeps you stuck. You DID a thing. You are not the thing. Separate behaviour from identity.",
  },
  {
    id: "univ-perfectionism-loop",
    title: "The Perfectionism-Procrastination Loop",
    subtitle: "You can't start because it won't be perfect. So nothing gets done.",
    category: "emotional-regulation",
    archetypes: ["plate-spinner", "the-disappeared", "invisible-architect"],
    dimensions: ["emotional-bandwidth", "cognitive-load"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You can't start because it won't be perfect. You can't finish because it's not good enough. You can't delegate because they won't do it right. Perfectionism looks like high standards from the outside. From the inside, it's paralysis.",
      "The loop: you set an impossibly high standard → the gap between where you are and 'should' be feels overwhelming → overwhelm triggers avoidance → avoidance creates guilt → guilt raises the standard higher → the gap grows → more paralysis. It feeds itself.",
      "Perfectionism in mothers often develops as armour. You've been judged — by your mother, by society, by other parents, by yourself. You learned: 'If I do it perfectly, no one can criticise me.' The perfectionism isn't about excellence. It's about protection from shame.",
      "The exit: done is better than perfect. A sent email with a typo beats a perfect email never written. A 'good enough' dinner beats a gourmet meal you were too paralysed to start. Imperfect action beats perfect inaction. Every single time.",
    ],
    tryThis: "Pick one thing you've been avoiding because it won't be perfect. Do the worst possible version of it. Intentionally bad. A terrible first draft. A half-cleaned room. Notice: the world didn't end. And now it's done.",
    remember: "Perfectionism isn't high standards — it's fear of criticism wearing a mask. Done beats perfect. Always. Lower the bar and move.",
  },
  // ---- PHYSICAL / NERVOUS SYSTEM ----
  {
    id: "univ-interoception",
    title: "You Might Not Know You're Hungry Until You're Shaking",
    subtitle: "Your brain deprioritises your body's signals. Here's why.",
    category: "physical-nervous-system",
    archetypes: ["running-on-empty", "plate-spinner", "the-disappeared"],
    dimensions: ["physical-depletion", "cognitive-load"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "It's 3pm and you realise you haven't eaten. Or you suddenly notice you desperately need the bathroom — and have for hours. Or you're shaking and irritable and only then realise you're hungry. This isn't just being busy. It's impaired interoception — your brain's ability to notice internal body signals.",
      "Interoception — sensing hunger, thirst, temperature, fatigue, pain — requires brain resources. When those resources are consumed by managing a household, tracking children, making decisions, and regulating emotions, body signals get deprioritised. You don't feel hungry until you're starving. Don't feel tired until you're collapsing.",
      "Motherhood compounds this. You're trained to ignore your own body in favour of everyone else's needs. Over years, the ignoring becomes automatic. You genuinely lose access to what your body is telling you until it's screaming.",
      "The downstream effects: you're making decisions on an empty stomach (impaired glucose = impaired cognition), you're dehydrated (cognitive decline), you're holding tension you don't notice (chronic pain), and you're exhausted without registering it until you crash.",
    ],
    tryThis: "Set 3 alarms today: 10am, 1pm, 4pm. When they go off, stop and scan: Am I hungry? Thirsty? Do I need the bathroom? Am I tense anywhere? Don't wait for your body to tell you — ask it on a schedule.",
    remember: "You might not feel hungry, thirsty, or tired until it's an emergency. That's your brain deprioritising you. Use scheduled check-ins instead of waiting for signals that may never come.",
  },
  {
    id: "univ-exercise-paradox",
    title: "Why Exercise Helps But You Can't Make Yourself Do It",
    subtitle: "It helps. You know it helps. Starting requires energy you don't have.",
    category: "physical-nervous-system",
    archetypes: ["running-on-empty", "plate-spinner", "the-disappeared"],
    dimensions: ["physical-depletion", "cognitive-load"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "Every piece of advice says exercise helps. And it does — research shows 20 minutes of moderate movement can improve mood, cognition, and stress tolerance for hours afterward. There's just one problem: starting exercise requires the exact energy and executive function that exercise is supposed to restore. It's a cruel catch-22.",
      "To exercise, you need: the ability to start (task initiation), time management (fitting it in), memory (remembering to do it), emotional push (overcoming inertia), and planning (what, where, when). All of these are depleted in an overwhelmed mother. Telling an exhausted woman to 'just exercise' is like telling someone with a flat tyre to drive to the mechanic.",
      "The workaround isn't motivation or discipline. It's removing every barrier between you and movement. Not 'go to the gym for an hour' but 'walk to the end of the street.' Not 'follow a workout plan' but 'put on shoes and step outside.' Not 'exercise at 6am' but 'move your body at whatever time you happen to have energy.'",
      "The lowest-barrier version: movement that doesn't feel like exercise. Dancing in the kitchen. Walking while on a phone call. Squats while waiting for the kettle. Playing chase with your children. Your brain doesn't need a 'workout' — it needs 20 minutes of elevated heart rate. How you get there doesn't matter.",
    ],
    tryThis: "Don't plan exercise. Instead: right now, stand up and walk for 5 minutes. Around the house, around the block, anywhere. No gear, no plan, no commitment beyond 5 minutes. Notice how your brain feels after.",
    remember: "Exercise helps but requires energy to start — energy you don't have. Remove every barrier. Make it tiny. Make it now. 5 minutes beats 0 minutes of a perfect plan.",
  },
  {
    id: "univ-chronic-pain",
    title: "Why Your Body Holds Everything Your Mind Won't",
    subtitle: "Your shoulders are concrete. Your jaw aches. There's a reason.",
    category: "physical-nervous-system",
    archetypes: ["running-on-empty", "burning-engine", "weight-bearer"],
    dimensions: ["physical-depletion"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "Your shoulders are concrete. Your jaw aches. Your back is always tight. You carry tension you don't notice until someone touches you and you flinch. This isn't 'just stress' — it's your nervous system storing what your conscious mind hasn't had time to process.",
      "When you're in a chronic state of hypervigilance — always scanning for the next need, the next crisis, the next demand — your muscles stay braced. They're preparing for impact that never resolves. Your body is stuck in 'ready' mode, tensed against a threat that isn't a single event but a permanent state of overwhelm.",
      "Impaired body awareness means you don't register the tension until it becomes pain. You've been clenching your jaw for 6 hours without noticing. Holding your shoulders at your ears all day. The tension accumulates invisibly until it becomes chronic, then you wonder why you 'suddenly' have back problems.",
      "The connection goes both ways: chronic pain worsens cognitive function (pain uses brain resources), and cognitive overload worsens pain (you can't maintain the habits that prevent it). It's a feedback loop that requires attention at both ends.",
    ],
    tryThis: "Right now: drop your shoulders. Unclench your jaw. Unfurrow your brow. Release your tongue from the roof of your mouth. Notice how much tension you were holding without awareness. Set a reminder to do this 3 times today.",
    remember: "Your body stores what your mind can't process. The tension you don't notice is still costing you. Check in with your body on a schedule — don't wait for pain to alert you.",
  },
  {
    id: "univ-sensory-overload",
    title: "Why the Noise Makes You Want to Scream",
    subtitle: "You're not overreacting. Your nervous system is overfull.",
    category: "physical-nervous-system",
    archetypes: ["plate-spinner", "burning-engine", "storm-weatherer"],
    dimensions: ["physical-depletion", "emotional-bandwidth"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "The TV is on. Someone is asking you a question. The toddler is whining. A toy is making noise. And suddenly you want to scream, cover your ears, or leave the room. You feel like a terrible person for being unable to tolerate your own family. You're not terrible. You're sensorially overwhelmed.",
      "Your nervous system has a processing capacity — a threshold for how much sensory input it can handle at once. When that threshold is exceeded, additional input registers as pain, not information. The child's voice isn't loud — but it's the 400th input in an hour, and your system is full.",
      "This threshold lowers when you're depleted. Well-rested, you might tolerate noise, touch, and visual clutter simultaneously. Exhausted, any single input can tip you over. This is why the same noise that was fine at 9am is unbearable at 5pm. Your capacity contracted as the day drained it.",
      "The craving for silence, darkness, and stillness isn't antisocial. It's your nervous system's emergency request for recovery. Just as an overstimulated infant needs to be held in a dim, quiet room, an overstimulated adult needs sensory reduction. The need is identical — only the shame is different.",
    ],
    tryThis: "When sensory overload hits: remove ONE input. Turn off the TV. Close a door. Put in one earbud with nothing playing (reduces input by half). You don't need perfect silence — you need any reduction.",
    remember: "Sensory overwhelm isn't overreacting. It's a full nervous system receiving more input than it can process. Reduce one input — any input — and the system can breathe.",
  },

  // ---- SYSTEMS & STRUCTURE ----
  {
    id: "univ-routine-building",
    title: "Why Routines Keep Failing (and How to Build Ones That Don't)",
    subtitle: "They fail because they weren't built for a depleted brain.",
    category: "systems-structure",
    archetypes: ["plate-spinner", "storm-weatherer", "running-on-empty"],
    dimensions: ["system-friction", "cognitive-load"],
    tags: ["universal"],
    readTime: "3 min",
    body: [
      "You've tried routines. Morning routines, evening routines, cleaning routines. They work for 3 days and then collapse. You conclude: 'I'm just not a routine person.' But the problem isn't you — it's how the routines were designed.",
      "Most routine advice assumes a consistent brain with consistent energy. Rigid schedules, specific times, long sequences, perfection expected. A depleted brain needs the opposite: flexible anchors, body-based cues, short sequences, and forgiveness built in.",
      "The principles that work: (1) Anchor to an existing behaviour, not a time. 'After I pour coffee' is more reliable than '7:15am.' (2) Keep it to 3-5 steps max. Long sequences collapse. (3) Make it visible — a checklist on the wall, not a plan in your head. (4) Build in a 'good enough' version for bad days. (5) Expect it to break. Have a restart plan, not a shame spiral.",
      "The most important principle: a routine that works 4 days out of 7 is not a failed routine. It's a successful one. Perfection is 7/7. Reality is 4-5/7. That's still structure. It's still helping. Stop designing for perfection. Design for 'good enough, most days.'",
    ],
    tryThis: "Pick ONE chaotic transition point (morning, after school, bedtime). Write 3 steps — not 10 — on a card and put it where you'll see it. Do those 3 things in that order for one week. That's your routine.",
    remember: "A routine that works 4 days out of 7 isn't a failure. It's a success for a depleted brain. Design for 'good enough, most days.'",
  },
  {
    id: "univ-environmental-design",
    title: "Design Your Environment, Not Your Willpower",
    subtitle: "Your house should do the remembering for you.",
    category: "systems-structure",
    archetypes: ["plate-spinner", "storm-weatherer", "invisible-architect"],
    dimensions: ["system-friction", "cognitive-load"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You keep losing your keys. You forget to take your vitamins. The children's shoes are never by the door. You blame yourself — 'Why can't I just remember?' But the question isn't why you can't remember. It's why your environment isn't remembering for you.",
      "Environmental design is the principle that your physical space should make the right behaviour easy and the wrong behaviour hard. It's more powerful than willpower, more reliable than memory, and more sustainable than any habit app.",
      "Examples: a hook by the door means keys always go in one place (no searching). Vitamins next to the coffee maker means you see them every morning (no forgetting). A bin by the entrance means shoes have a home (no hunting). A visual checklist on the wall means the routine is external (not held in your head).",
      "For a depleted brain, environmental design isn't a nice-to-have — it's essential. Your working memory can't hold the location of every object. Your cognitive function can't initiate a search every time you need something. The environment needs to do the work your brain can't reliably do under these conditions.",
    ],
    tryThis: "Identify your top 'friction point' — the thing you lose, forget, or can't find most often. Ask: 'Where should this LIVE so I never have to think about it?' Give it a permanent, visible home.",
    remember: "Don't ask your brain to remember what your environment can hold. Every object with a 'home,' every routine made visible, is cognitive load permanently removed.",
  },
  {
    id: "univ-decision-elimination",
    title: "The Power of Eliminating Choices",
    subtitle: "Fewer options means better functioning. Here's why.",
    category: "systems-structure",
    archetypes: ["plate-spinner", "invisible-architect", "running-on-empty"],
    dimensions: ["cognitive-load", "system-friction"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "Steve Jobs wore the same outfit daily. Obama limited suits to two colours. These aren't quirks — they're decision elimination strategies. Every choice you remove from your day is cognitive fuel saved for choices that actually matter.",
      "For depleted brains, this principle is critical. Your decision-making resources are smaller under chronic stress and deplete faster. Every 'what should I wear,' 'what should we eat,' 'which route should I take' costs the same cognitive currency as 'how should I handle this parenting moment.' By afternoon, the currency is spent.",
      "Decision elimination looks like: same breakfast every weekday (no choosing). Capsule wardrobe with pre-matched outfits (no assembling). Meal rotation that repeats weekly (no planning). Same grocery list (no browsing). Automated bill payments (no remembering). Same bedtime routine in same order (no improvising).",
      "This isn't boring. It's strategic. The most effective people eliminate routine decisions so they can spend cognitive resources on things that require genuine thought. You deserve the same strategy.",
    ],
    tryThis: "Pick the decision that drains you most (usually meals or clothing). Eliminate it for one week: same breakfast, same lunch formula, or 5 pre-planned outfits. Notice how much lighter your brain feels.",
    remember: "Every decision you eliminate is fuel saved for decisions that matter. Automation isn't laziness — it's intelligence applied to a limited resource.",
  },
  {
    id: "univ-good-enough-systems",
    title: "Your System Doesn't Have to Be Perfect to Work",
    subtitle: "The 70% system you use beats the perfect one you don't.",
    category: "systems-structure",
    archetypes: ["plate-spinner", "invisible-architect", "storm-weatherer"],
    dimensions: ["system-friction", "cognitive-load"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You've tried every planner, every app, every system. They work for a week, then collapse. You conclude you're 'not an organised person.' But the problem isn't you — it's that you keep choosing systems designed for brains operating at 100% consistency.",
      "A system that works for a depleted mother has one requirement: it works when you're at 50% capacity. Not when you're motivated and energised — when you're exhausted, distracted, and barely functioning. If a system only works on your best days, it's not a system. It's a hobby.",
      "The principles: (1) Fewer steps always wins. A 3-step system beats a 10-step system. (2) Visible beats hidden. A whiteboard on the wall beats a notebook in a drawer. (3) Forgiving beats rigid. Working 4/7 days is better than requiring 7/7. (4) Started beats perfect. A messy list on your phone beats a beautiful planner you never open.",
      "The best system for you is the one you'll actually use on your worst day. Not the prettiest. Not the most comprehensive. The one with the lowest barrier to entry when you have nothing left.",
    ],
    tryThis: "Look at your current system. Ask: 'Would I use this on my worst day? When exhausted and barely thinking?' If no — simplify until the answer is yes. That's your real system.",
    remember: "A 70% system you use beats a 100% system you abandon. Design for your worst day, not your best.",
  },
  {
    id: "univ-batch-processing",
    title: "Stop Switching Between 20 Different Types of Task",
    subtitle: "Group similar tasks. Your brain will thank you.",
    category: "systems-structure",
    archetypes: ["plate-spinner", "invisible-architect", "storm-weatherer"],
    dimensions: ["cognitive-load", "system-friction"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You make one phone call, then switch to email, then start laundry, then remember the other call, then check email again. Each switch costs cognitive resources. By the end of the day, you've done 20 things but finished 3. The rest are half-done, scattered across your attention.",
      "Batch processing is the opposite: group similar tasks together. All phone calls in one block. All emails in one sitting. All meal prep at once. All errands in one trip. Instead of switching between task types 50 times daily, you switch 5 times.",
      "Why this works for depleted brains: each task type requires a different 'mode' — phone calls need social energy, emails need writing energy, physical tasks need body energy. Switching modes is expensive. Staying in one mode and completing multiple tasks of that type is dramatically more efficient.",
      "The practical version: designate 'admin time' (15 minutes, all emails/texts/forms at once), 'errand time' (one trip, all stops), 'cleaning time' (30 minutes, all rooms), 'planning time' (one sitting, whole week). Batch by type, not by urgency.",
    ],
    tryThis: "Tomorrow, batch your communication: instead of responding to messages all day, check and respond twice — mid-morning and mid-afternoon. Notice how much less fragmented your day feels.",
    remember: "Switching between task types costs more than the tasks themselves. Group similar things together. One mode at a time. Batch, don't scatter.",
  },
  {
    id: "univ-visual-timers",
    title: "Visual Timers Change Everything",
    subtitle: "You can't manage time you can't see. Make it physical.",
    category: "systems-structure",
    archetypes: ["plate-spinner", "storm-weatherer", "burning-engine"],
    dimensions: ["cognitive-load", "system-friction"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "Time is invisible. When your brain is overloaded, invisible time might as well not exist. '10 minutes' means nothing if you can't see it shrinking. You can't feel it passing. Until suddenly it's gone and you're late again.",
      "Visual timers solve this by making time physical. A Time Timer (the red disk that shrinks), a sand timer, or a phone timer with a visual countdown — these translate abstract time into something your brain can perceive: a shrinking shape, falling sand, a moving bar.",
      "For both you and your children, visual timers reduce transition difficulty (you can SEE the end approaching), improve time estimation (you learn what 10 minutes looks like), reduce anxiety (no surprise endings), and support task completion (the visual creates gentle urgency without panic).",
      "Use them for: morning routines (15-minute timer visible to everyone), transitions ('when the timer ends, we leave'), focused work blocks (25-minute sessions), and self-care ('10 minutes of rest — watch the timer so you don't feel guilty about stopping').",
    ],
    tryThis: "Get a visual timer (a Time Timer app on your phone works). Tomorrow morning: set 15 minutes visible to everyone. 'When the red is gone, we leave.' Notice how much smoother the transition is when time is visible.",
    remember: "You can't manage time you can't see. Visual timers make the invisible visible — for you AND your children. They're assistive tools for overloaded brains.",
  },
  {
    id: "univ-context-switching",
    title: "Why One Interruption Ruins Your Whole Hour",
    subtitle: "One 'Mum!' and your entire train of thought is gone.",
    category: "executive-function",
    archetypes: ["plate-spinner", "invisible-architect", "burning-engine"],
    dimensions: ["cognitive-load"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You were finally in flow — writing that email, cleaning, having a thought — and then: 'Mum!' By the time you've handled the interruption (30 seconds), you've lost the thread entirely. Research shows it takes 23 minutes to fully re-engage with a task after an interruption. Twenty-three minutes. For a 30-second disruption.",
      "This isn't unique to any brain type — it's universal neuroscience. But it's worse when depleted because: getting into flow was harder in the first place, the interrupted task may vanish from overloaded working memory entirely, and the frustration of being interrupted depletes your remaining regulation resources.",
      "Motherhood is essentially a job of constant interruption. Children's needs are unpredictable, immediate, and non-negotiable. You're asked to maintain complex cognitive tasks while being interrupted every 3-7 minutes. No professional environment would expect this — but motherhood does, without acknowledgment.",
      "You're not failing to focus. You're being interrupted more than any brain can sustain. The solution isn't better concentration — it's protected windows. Even 20 minutes of uninterrupted time can accomplish what 2 hours of interrupted time cannot.",
    ],
    tryThis: "Tomorrow, create ONE 20-minute protected window. Partner takes over, kids in independent play, door closed. Do one thing without interruption. Notice how much you accomplish compared to the fragmented rest of the day.",
    remember: "One interruption costs 23 minutes of re-engagement. You're not unfocused — you're over-interrupted. Protect small windows fiercely.",
  },
  {
    id: "univ-note-imperative",
    title: "'I'll Remember This' — You Won't",
    subtitle: "Your brain has a 30-second shelf life right now. Write it down.",
    category: "executive-function",
    archetypes: ["plate-spinner", "invisible-architect", "storm-weatherer"],
    dimensions: ["cognitive-load", "system-friction"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "The thought arrives: 'I need to buy milk.' 'I should call the dentist.' 'That form is due Friday.' You think: 'I'll remember.' You won't. Not because you're careless — because under these conditions, your working memory has a 30-second shelf life for non-urgent information.",
      "Every thought you don't capture is a thought you'll lose. And every lost thought becomes: a missed appointment, a forgotten birthday, a child without a costume on costume day, a bill paid late. The consequences accumulate. The shame accumulates. And the solution was always the same: write it down. Immediately. Every time.",
      "This isn't about being organised or having a perfect system. It's about accepting a reality: your brain, under chronic overload, cannot hold information reliably. Once you accept this without shame, writing everything down becomes as natural as breathing. It's not a crutch. It's how you function in these conditions.",
      "The tool doesn't matter. Phone notes, voice memos, scrap of paper, a text to yourself. What matters is the habit: thought arrives → capture immediately → trust the system instead of your memory. The gap between 'I'll remember' and 'I'll write it down' is the gap between chaos and function.",
    ],
    tryThis: "For one day, capture EVERY thought that requires future action. Don't filter, don't organise — just dump it into one place. At the end of the day, look at the list. That's how much your brain was trying to hold invisibly.",
    remember: "'I'll remember' is the most expensive lie your overloaded brain tells. Write it down. Immediately. Every time. Your capture system is more reliable than your memory right now.",
  },
  {
    id: "univ-starting-projects",
    title: "Why You Start 10 Things and Finish None",
    subtitle: "The trail of half-finished projects isn't laziness. It's how depletion works.",
    category: "executive-function",
    archetypes: ["plate-spinner", "the-disappeared", "storm-weatherer"],
    dimensions: ["cognitive-load"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "The closet reorganisation you started in March. The craft project from last summer. The online course you signed up for. You have a trail of 80%-done projects behind you and the shame of each one weighs on you.",
      "This is the novelty-completion gap. Starting new things gives your brain a hit of engagement — the neurochemistry of interest and reward. The beginning is exciting. The middle is monotonous. And monotonous tasks don't generate enough brain activation to sustain your attention when you're already running on empty. So you start the next new thing, chasing the spark of beginning.",
      "It's not that you can't finish things. It's that finishing requires sustained effort on something that's no longer stimulating — and your depleted brain can't sustain interest without novelty. The last 20% of any project is the hardest because all the newness is gone and only persistence remains — persistence that requires resources you don't have.",
      "The workaround: make the ending novel. Change your environment for the final push. Add a reward at completion. Set a deadline with accountability. Or — radical acceptance — decide that some projects don't need finishing. Not everything started needs to be completed. Some things served their purpose in the starting.",
    ],
    tryThis: "Look at your unfinished projects. For each one ask: 'Does this actually need finishing, or did I get what I needed from starting it?' Give yourself permission to officially abandon the ones that don't matter. Close the loop mentally.",
    remember: "You're not flaky. Your brain runs on novelty, and finishing isn't novel. Either make the ending interesting, or give yourself permission to let it go.",
  },
  {
    id: "univ-two-minute-rule",
    title: "The Two-Minute Rule (It Actually Works)",
    subtitle: "Every small task you defer is an open loop draining your brain.",
    category: "systems-structure",
    archetypes: ["plate-spinner", "storm-weatherer", "invisible-architect"],
    dimensions: ["cognitive-load", "system-friction"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "The two-minute rule is simple: if a task takes less than 2 minutes, do it immediately instead of adding it to your mental list. Hang up the coat. Reply to the text. Put the dish in the dishwasher. Wipe the counter. Sign the form. Done.",
      "Why this works for overloaded brains: every task you defer — no matter how small — occupies space in your working memory. It becomes another 'open loop' your brain has to track. Ten deferred 2-minute tasks = ten open loops = significant cognitive drain. Doing them immediately closes the loop and frees the space.",
      "The rule also bypasses the starting problem. You don't have to 'decide to start' a 2-minute task — you just do it in the moment you notice it. The decision cost is zero because the rule already made the decision: under 2 minutes = now. No deliberation needed.",
      "Important caveat: this only works for tasks that genuinely take under 2 minutes. If you start 'quickly' organising a drawer and 45 minutes disappear — that wasn't a 2-minute task. Be honest about what's quick and what's a trap disguised as a small task.",
    ],
    tryThis: "For the rest of today: every time you notice something under 2 minutes, do it immediately. Don't add it to a list. Don't 'do it later.' Just do it now. Count how many open loops you close by bedtime.",
    remember: "Every deferred 2-minute task is an open loop in your working memory. Close it immediately and free the space. The rule makes the decision for you: under 2 minutes = now.",
  },
  {
    id: "univ-launch-pad",
    title: "The Launch Pad: Stop Searching Every Morning",
    subtitle: "One spot by the door. Everything needed to leave. No searching.",
    category: "systems-structure",
    archetypes: ["plate-spinner", "storm-weatherer", "invisible-architect"],
    dimensions: ["system-friction", "cognitive-load"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "Every morning is a scavenger hunt. Keys? Where are the keys? Backpack? Which room? Permission slip? Shoes? WHY ARE THERE NEVER MATCHING SHOES? The problem isn't your family. It's that there's no designated 'leaving the house' zone.",
      "The launch pad is a single location — by your front door — where EVERYTHING needed to leave the house lives. Keys, bags, shoes, coats, forms, water bottles. One spot. If it's needed to leave, it lives here.",
      "This works because it eliminates the search. Your brain doesn't have to remember where things are — it only needs one location. And if you build the habit of putting things there the night before, morning becomes execution, not investigation.",
      "The launch pad can be: a bench with hooks, a shelf by the door, a set of bins, or a spot on the floor with a basket. It doesn't have to look good. It has to be consistent. Same spot. Every time. No exceptions.",
    ],
    tryThis: "Today: designate a launch pad spot by your front door. Put hooks for keys and bags. Tomorrow, notice: did you search for anything? If yes, that thing needs a home at the launch pad.",
    remember: "One spot. Everything needed to leave. No searching, no remembering, no morning scavenger hunts. The launch pad does the thinking for you.",
  },
]
