// ============================================================
// Micro-Guides Content — First 20
// Each guide: one concept, one reframe, one action
// Written as a clinical psychologist who speaks like a human
// ============================================================

import type { MicroGuide } from "./types"

export const MICRO_GUIDES: MicroGuide[] = [
  // ---- EXECUTIVE FUNCTION (3) ----
  {
    id: "ef-task-initiation",
    title: "Why You Can't 'Just Start'",
    subtitle: "It's not laziness. Your brain's starter motor is broken.",
    category: "executive-function",
    archetypes: ["plate-spinner", "running-on-empty", "weight-bearer"],
    dimensions: ["cognitive-load"],
    tags: ["adhd"],
    readTime: "2 min",
    body: [
      "You're staring at the dishes. You know they need doing. You want them done. But your body won't move. It's not laziness. It's not a character flaw. It's a neurological gap between intention and action called task initiation failure.",
      "In a neurotypical brain, the prefrontal cortex sends a 'start' signal that activates motor planning. In an ADHD or depleted brain, that signal is weak or delayed. It's like having a car with a dead starter motor — the engine works fine once it's running, but turning the key does nothing.",
      "This is why you can spend 45 minutes dreading a task that takes 10 minutes to complete. The doing isn't the problem. The starting is. And no amount of willpower fixes a neurological gap — you need a workaround.",
      "The most effective workaround is called 'body-first initiation.' Instead of waiting for your brain to send the start signal, you move your body toward the task physically. Stand up. Walk to the sink. Touch the first dish. Don't commit to finishing — just commit to touching. The movement often triggers the brain to engage.",
    ],
    tryThis: "Next time you're stuck: stand up, walk to the task, and touch one object related to it. Don't commit to doing it. Just touch it. See what happens.",
    remember: "You're not lazy. Your starter motor is weak. Move your body first — your brain will follow.",
  },
  {
    id: "ef-time-blindness",
    title: "Time Blindness Is Real",
    subtitle: "Why you genuinely believed you had 20 minutes when you had 5.",
    category: "executive-function",
    archetypes: ["plate-spinner", "storm-weatherer"],
    dimensions: ["cognitive-load", "system-friction"],
    tags: ["adhd"],
    readTime: "2 min",
    body: [
      "You genuinely believed you had 20 minutes. You had 5. This isn't poor planning — it's time blindness, a well-documented feature of ADHD brains. Your internal clock doesn't tick at the same rate as the external one.",
      "Neurotypical brains have a relatively accurate internal sense of time passing. They can feel the difference between 5 minutes and 20 minutes without looking at a clock. ADHD brains often cannot. Time is either 'now' or 'not now' — and 'not now' could be 5 minutes or 5 hours. They feel the same.",
      "This is why you consistently underestimate how long things take. It's why transitions are brutal — you can't feel the time running out until it's already gone. It's why 'just leave earlier' doesn't work. You can't leave earlier if you can't feel 'earlier' approaching.",
      "The fix isn't willpower. It's external time cues. Timers, alarms, visual countdowns — anything that makes invisible time visible. Your brain needs time translated into something it can perceive: sound, sight, or physical sensation.",
    ],
    tryThis: "Set a timer for 10 minutes and do nothing. Just sit. Notice how long 10 minutes actually feels versus how long you thought it would feel. That gap is your time blindness.",
    remember: "You're not careless with time. You literally can't feel it passing. Make time visible — alarms, timers, clocks in every room.",
  },
  {
    id: "ef-decision-fatigue",
    title: "Why You Can't Decide What's for Dinner",
    subtitle: "Your brain made 400 decisions today. It's out of fuel.",
    category: "executive-function",
    archetypes: ["plate-spinner", "invisible-architect", "weight-bearer"],
    dimensions: ["cognitive-load", "system-friction"],
    tags: ["adhd"],
    readTime: "2 min",
    body: [
      "It's 4pm. Someone asks what's for dinner. Your brain goes completely blank. Not because you don't know how to cook. Because you've already made 400 decisions today and your prefrontal cortex is out of fuel.",
      "Decision-making uses the same cognitive resources as self-control, planning, and emotional regulation. Every choice — what to wear, which route to take, how to respond to that email, what to feed the toddler for snack — depletes the same tank. By afternoon, the tank is empty.",
      "For ADHD brains, this tank is smaller to begin with. Executive function resources are limited, and they're being used at a higher rate because nothing is automatic. Neurotypical brains automate routine decisions. ADHD brains treat every decision as novel — which means every decision costs full price.",
      "This is why meal planning, capsule wardrobes, and routines aren't just 'nice to have' for ADHD brains — they're cognitive prosthetics. Every decision you eliminate in advance is one you don't have to make when your tank is empty.",
    ],
    tryThis: "Identify your top 3 daily 'decision drains' — the recurring choices that cost you the most energy. Eliminate ONE by making it automatic (same breakfast every day, same outfit formula, same Tuesday dinner).",
    remember: "You're not indecisive. You're depleted. Every decision you pre-make is fuel saved for the ones that actually matter.",
  },

  // ---- EMOTIONAL REGULATION (3) ----
  {
    id: "er-rage-cycle",
    title: "Why You Yell at the People You Love Most",
    subtitle: "It's not anger at them. It's overflow from everything else.",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "burning-engine", "weight-bearer"],
    dimensions: ["emotional-bandwidth"],
    tags: ["universal"],
    readTime: "3 min",
    body: [
      "You love your children more than anything. And sometimes you scream at them with a fury that terrifies you. These two things are not contradictory — they're connected.",
      "Rage in mothers is almost always a sign of one thing: your nervous system has exceeded its capacity. It's not that you're angry at your child. It's that your system has been absorbing input — noise, touch, demands, decisions, emotions — all day with no outlet, and it finally overflows. The child just happened to be the last drop.",
      "Neurologically, what's happening is this: your amygdala (threat detection) has been activated so many times without resolution that it's now on a hair trigger. Your prefrontal cortex (the part that says 'don't yell') is offline because it's been overworked all day. The result: amygdala fires, prefrontal cortex can't catch it, and you explode.",
      "This is not a character flaw. It's a resource failure. You ran out of regulation capacity. The rage is your nervous system's emergency pressure release valve. It's not pretty, but it's functional — your body is trying to discharge energy it can't contain.",
      "The fix isn't 'try harder not to yell.' It's reducing the input load BEFORE you hit capacity, and building micro-regulation moments throughout the day so the pressure never builds to explosion level.",
    ],
    tryThis: "Track your rage moments for one week. Note the time of day and what happened in the 2 hours before. You'll find a pattern — usually it's accumulated sensory/emotional load, not the triggering event itself.",
    remember: "You're not a bad mother who yells. You're a depleted mother whose system hit capacity. The rage is a signal, not a sentence.",
  },
  {
    id: "er-guilt-spiral",
    title: "The Guilt Spiral Is Lying to You",
    subtitle: "Feeling guilty doesn't mean you're guilty.",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "the-disappeared", "burning-engine"],
    dimensions: ["emotional-bandwidth", "identity-erosion"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You forgot the school thing. Or you yelled. Or you served cereal for dinner. And now the guilt is telling you a story: 'You're a bad mother. Everyone else manages this. Your kids deserve better.'",
      "Here's what guilt actually is: it's a cognitive distortion called 'emotional reasoning.' You feel bad, therefore you conclude you ARE bad. But feelings aren't facts. Guilt is not evidence of failure — it's evidence of caring. Bad parents don't feel guilty. They don't lie awake replaying the moment. The guilt itself proves your values are intact.",
      "The spiral works like this: event → guilt → shame → 'I'm bad' → overcompensation → exhaustion → another event → more guilt. It's a loop that feeds itself. And it's completely unproductive — guilt doesn't make you a better parent. It just makes you a more exhausted one.",
      "The interruption point is between guilt and shame. Guilt says 'I did something bad.' Shame says 'I AM bad.' You can hold guilt (it's useful information) without letting it become shame (which is a lie about your identity).",
    ],
    tryThis: "Next time guilt hits, say out loud: 'I feel guilty. That means I care. It does not mean I'm bad.' Then ask: 'Is there something to repair here?' If yes, repair it. If no, let it go.",
    remember: "Guilt is not evidence. It's a feeling. And the fact that you feel it at all is proof that you're a good mother having a hard time.",
  },
  {
    id: "er-emotional-flooding",
    title: "When Everything Hits at Once",
    subtitle: "It's not about the bread. It's never about the bread.",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "burning-engine", "storm-weatherer"],
    dimensions: ["emotional-bandwidth"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "One minute you're fine. The next minute you're crying in the pantry because the bread is stale. It's not about the bread. It's never about the bread.",
      "Emotional flooding happens when your nervous system receives more emotional input than it can process in real-time. The emotions stack — unprocessed from yesterday, from this morning, from the argument, from the news, from the child's meltdown — until one small thing tips the whole pile over.",
      "When you're flooded, your prefrontal cortex goes offline. You can't think clearly, you can't problem-solve, you can't regulate. You're operating from your brainstem — pure survival. This is why you can't 'just calm down' when someone tells you to. The part of your brain that calms down isn't available.",
      "The key insight: flooding is not about the trigger. It's about the accumulated load. If you're flooding over small things, it means your baseline is already too high. You're walking around at 8/10 and anything that adds even 0.5 tips you to overflow.",
    ],
    tryThis: "When flooding hits: cold water on your face or wrists (activates the dive reflex and drops heart rate within 30 seconds). Don't try to think or talk until the physical sensation passes. Thinking comes after regulation, not before.",
    remember: "It's not about the bread. It's about everything that came before the bread. Your baseline is too high — that's the real problem to solve.",
  },

  // ---- PHYSICAL / NERVOUS SYSTEM (3) ----
  {
    id: "pns-cortisol-curve",
    title: "The 3pm Crash Isn't Laziness",
    subtitle: "There's a biological reason the afternoon destroys you.",
    category: "physical-nervous-system",
    archetypes: ["running-on-empty", "burning-engine", "weight-bearer"],
    dimensions: ["physical-depletion"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "Every afternoon around 2-4pm, you hit a wall. Energy drops. Brain fog rolls in. Patience evaporates. You think it's because you're weak or undisciplined. It's actually your cortisol curve doing exactly what it's supposed to do.",
      "Cortisol — your alertness hormone — follows a natural daily rhythm. It peaks in the morning (that's what wakes you up) and gradually declines throughout the day. The steepest drop happens mid-afternoon. For everyone. It's biology, not failure.",
      "But here's what makes it worse for depleted mothers: if your morning cortisol is already low (because you're chronically stressed and your adrenals are fatigued), the afternoon drop takes you from 'barely functioning' to 'can't function at all.' You don't have the buffer that rested people have.",
      "This is why the 'witching hour' (3-6pm) is universally the hardest time for mothers. Your cortisol is at its lowest, your kids' behavior is at its worst (they're tired too), and dinner needs to happen. It's a perfect storm of biology and circumstance.",
    ],
    tryThis: "Plan your hardest tasks for morning (when cortisol is highest). Protect 2-4pm as a low-demand window. If possible: protein snack at 2pm, 5 minutes of sunlight, and lower your expectations for that window entirely.",
    remember: "The afternoon crash is cortisol, not character. Plan around it instead of fighting through it.",
  },
  {
    id: "pns-touched-out",
    title: "Touched Out Is a Nervous System State",
    subtitle: "You love them. You can't be touched. Both are true.",
    category: "physical-nervous-system",
    archetypes: ["quiet-volcano", "burning-engine", "running-on-empty"],
    dimensions: ["physical-depletion", "emotional-bandwidth"],
    tags: ["universal", "adhd", "autism"],
    readTime: "2 min",
    body: [
      "Your child reaches for you and your skin crawls. You love them. You don't want to be touched. Both are true at the same time, and the guilt of that contradiction is crushing.",
      "Being 'touched out' is not a preference or a mood. It's a neurological state. Your somatosensory cortex — the part of your brain that processes touch — has a threshold. When you've been touched, climbed on, grabbed, nursed, and clung to all day, that threshold is exceeded. Additional touch registers as a threat, not comfort.",
      "This is the same mechanism that makes a sunburn painful — the nerves are sensitized from overuse. Your touch receptors are literally overstimulated. Wanting to recoil from your child's hand is your nervous system protecting itself from further overload.",
      "This is not rejection of your child. It's your body's boundary alarm going off. And it's more common in mothers with sensory processing differences (ADHD, autism) because their baseline sensitivity is already higher.",
    ],
    tryThis: "When touched out: say 'I love you and my body needs a break from touching right now. Can we sit next to each other instead?' Give yourself 10 minutes of zero physical contact. It resets faster than you think.",
    remember: "Touched out is a nervous system state, not a failure of love. Your body has limits. Respecting them makes you a better parent, not a worse one.",
  },
  {
    id: "pns-burnout-vs-depression",
    title: "Burnout and Depression Look the Same",
    subtitle: "One is fixed by rest. The other isn't. Here's how to tell.",
    category: "physical-nervous-system",
    archetypes: ["running-on-empty", "burning-engine", "weight-bearer"],
    dimensions: ["physical-depletion", "emotional-bandwidth"],
    tags: ["universal"],
    readTime: "3 min",
    body: [
      "You're exhausted. Nothing brings joy. You can't concentrate. You feel empty. Is this depression? Or is this burnout? The symptoms overlap almost completely — but the cause and the fix are different.",
      "Depression is a neurochemical state — serotonin, dopamine, and norepinephrine are dysregulated. It can happen regardless of circumstances. Burnout is a resource depletion state — you've been outputting more than you're inputting for too long. It happens BECAUSE of circumstances.",
      "The key differentiator: if you imagine being given a week alone in a quiet cabin with no responsibilities, how do you feel? If the answer is 'relieved, I'd sleep and recover' — that's more likely burnout. If the answer is 'I'd still feel empty and hopeless even there' — that may be depression. (Both can coexist.)",
      "Why it matters: burnout responds to rest, reduced load, and structural change. Depression often needs clinical intervention — therapy, medication, or both. Treating burnout with antidepressants alone won't fix it if the structural cause remains. Treating depression with 'just rest more' won't fix it if the neurochemistry is off.",
      "If you're unsure: please talk to a healthcare provider. There's no shame in either. But knowing which one you're dealing with changes what will actually help.",
    ],
    tryThis: "Ask yourself the cabin question honestly. Then ask: 'If my circumstances changed dramatically (more support, less load), would I feel better?' If yes — the structure is the problem, not your brain chemistry. If no — consider talking to a professional.",
    remember: "Burnout and depression look identical from the outside. The difference is whether rest would fix it. If you're not sure, ask for help. That's not weakness — it's intelligence.",
    caveat: "This guide helps you reflect on what you might be experiencing — it cannot diagnose. Burnout and depression can coexist, and both deserve professional support. If you're unsure, please speak with a healthcare provider who can assess you properly.",
  },

  // ---- HORMONAL (2) ----
  {
    id: "horm-cycle-executive",
    title: "Your Cycle Is Changing Your Brain Every Week",
    subtitle: "Why some weeks you can handle everything and others you can't.",
    category: "hormonal",
    archetypes: ["quiet-volcano", "running-on-empty", "plate-spinner"],
    dimensions: ["cognitive-load", "emotional-bandwidth", "physical-depletion"],
    tags: ["hormonal", "adhd"],
    readTime: "3 min",
    body: [
      "Some weeks you can handle everything. Other weeks you can barely get out of bed. You think it's random. It's not. It's estrogen.",
      "Estrogen directly modulates dopamine — the neurotransmitter responsible for motivation, focus, and executive function. When estrogen is high (days 6-14 of your cycle, roughly), dopamine flows more freely. You feel capable, organized, motivated. When estrogen drops (days 22-28, and during your period), dopamine drops with it. You feel foggy, unmotivated, scattered.",
      "For women with ADHD, this effect is amplified. Your baseline dopamine is already lower than average. When estrogen drops, you go from 'managing' to 'can't function.' It's not a mood swing — it's a neurochemical cliff.",
      "This is why ADHD symptoms often worsen premenstrually, postpartum, and in perimenopause — all states of low or fluctuating estrogen. It's also why some women aren't diagnosed until these transitions, when their compensatory strategies stop working.",
      "The practical implication: you are not the same person every week of the month. Your capacity genuinely changes. Planning as if you have consistent capacity is setting yourself up to fail during low-estrogen weeks.",
    ],
    tryThis: "Track your cycle alongside your energy for 2 months. Note which days you feel capable and which days everything falls apart. You'll likely see a pattern that maps to your hormonal phases. Then: plan demanding tasks for high-estrogen weeks. Protect low-estrogen weeks with lighter schedules.",
    remember: "You're not inconsistent. Your hormones are changing your brain chemistry every week. Plan for the cycle, not against it.",
  },
  {
    id: "horm-postpartum-depletion",
    title: "Postpartum Depletion Can Last Years",
    subtitle: "The baby stage is over. Why are you still this exhausted?",
    category: "hormonal",
    archetypes: ["running-on-empty", "burning-engine", "weight-bearer"],
    dimensions: ["physical-depletion", "cognitive-load"],
    tags: ["postpartum"],
    readTime: "2 min",
    body: [
      "Your youngest is 3. Or 5. Or 7. And you're still exhausted in a way that sleep doesn't fix. People say 'but the baby stage is over!' as if your body should have bounced back by now. For many women, it hasn't. And there's a reason.",
      "Postpartum depletion — distinct from postpartum depression — is a state of nutritional, hormonal, and neurological deficit that can persist for years if not actively addressed. Pregnancy and breastfeeding deplete iron, zinc, DHA, B12, and vitamin D. These don't automatically replenish.",
      "Research by Dr. Oscar Serrallach found that many mothers are still measurably depleted in key nutrients 7+ years postpartum. The symptoms: brain fog, fatigue that sleep doesn't fix, poor memory, low motivation, emotional flatness. Sound familiar?",
      "This isn't 'just being a tired mom.' It's a physiological state with measurable markers. And it's treatable — but only if you know it exists. Most doctors don't screen for it because the symptoms overlap with 'normal motherhood.'",
    ],
    tryThis: "Consider asking your doctor to check: ferritin (not just hemoglobin), vitamin D, B12, zinc, and thyroid function. These are the most common postpartum deficiencies and they directly affect energy and cognition.",
    remember: "If you're still exhausted years after having kids, it might not be 'just motherhood.' Postpartum depletion is real, measurable, and treatable.",
  },

  // ---- RELATIONSHIPS (3) ----
  {
    id: "rel-invisible-labor",
    title: "The Invisible Labor Inventory",
    subtitle: "You're not 'nagging.' You're running an entire operation alone.",
    category: "relationships",
    archetypes: ["invisible-architect", "weight-bearer", "the-disappeared"],
    dimensions: ["system-friction", "identity-erosion"],
    tags: ["universal"],
    readTime: "3 min",
    body: [
      "You're not just doing tasks. You're carrying the cognitive weight of an entire household: remembering, anticipating, planning, monitoring, adjusting, and worrying — constantly, invisibly, without acknowledgment.",
      "Invisible labor includes: knowing when the kids need new shoes, remembering the teacher's name, tracking who has a playdate when, noticing the toilet paper is low before it runs out, managing the emotional temperature of the household, planning meals 7 days ahead, keeping the mental calendar of everyone's appointments, and worrying about all of it at 2am.",
      "Research calls this 'cognitive labor' or 'mental load.' It's distinct from physical tasks. Your partner might 'help' with dishes — but you're the one who noticed they needed doing, decided when, and would have done them if no one else did. The management layer is the exhausting part, not the execution.",
      "This labor is invisible because it happens inside your head. No one sees you remembering. No one sees you anticipating. No one sees you adjusting the plan when something changes. They only see the output: things running smoothly. And they assume it happens automatically.",
      "The resentment you feel isn't irrational. It's the natural consequence of doing unseen, unacknowledged, uncompensated work for years. Naming it is the first step to changing it.",
    ],
    tryThis: "For one day, write down every invisible task you do — every thing you remember, anticipate, plan, or manage that no one asked you to do. Show the list to your partner. Not as an attack — as information. 'This is what I'm carrying. I need you to see it.'",
    remember: "You're not 'nagging.' You're doing project management for an entire household without a job title, a salary, or a thank you.",
  },
  {
    id: "rel-asking-for-help",
    title: "Why Asking for Help Feels Impossible",
    subtitle: "You know you need it. You still can't ask. Here's why.",
    category: "relationships",
    archetypes: ["invisible-architect", "the-disappeared", "weight-bearer"],
    dimensions: ["system-friction", "identity-erosion"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You know you need help. You can't ask for it. This isn't stubbornness — it's a deeply wired pattern with real psychological roots.",
      "For many women, asking for help triggers one or more of these beliefs: 'If I have to ask, it doesn't count' (the mind-reading expectation). 'Asking means I'm failing' (help = weakness). 'They'll do it wrong and I'll have to redo it' (the competence trap). 'I don't deserve help — other people manage alone' (the comparison trap).",
      "These beliefs aren't random. They're often rooted in childhood experiences (being the 'responsible one'), cultural messaging ('good mothers don't need help'), or past experiences of asking and being dismissed, mocked, or let down.",
      "Here's the reframe: asking for help is not a sign of failure. It's a sign of accurate self-assessment. You know your limits. You know the load is unsustainable. Asking is the intelligent response to an impossible situation. Silence is what keeps you stuck.",
    ],
    tryThis: "Practice with the smallest possible ask. Not 'I need more help' (too vague). Try: 'Can you handle bedtime tonight? I need to sit down.' Specific. Time-bound. Low stakes. Build the muscle.",
    remember: "Asking for help isn't weakness. It's the most efficient solution to an unsustainable load. The weakness is suffering in silence.",
  },
  {
    id: "rel-partner-communication",
    title: "Why 'I Need More Help' Never Works",
    subtitle: "What to say instead that actually changes things.",
    category: "relationships",
    archetypes: ["invisible-architect", "storm-weatherer", "quiet-volcano"],
    dimensions: ["system-friction", "emotional-bandwidth"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "'I need more help around here.' You've said it. Maybe yelled it. And nothing changed. Not because your partner doesn't care — but because that sentence is unactionable.",
      "'More help' is abstract. It requires your partner to: identify what needs doing, figure out when to do it, decide how to do it, and initiate without being asked. That's four executive function steps. If they could do all four independently, they'd already be doing it.",
      "What works instead: specific, time-bound, ownership-based requests. Not 'help with dinner' but 'You own dinner Tuesday through Thursday. Plan it, shop for it, cook it, clean up. I don't want to think about it.' Not 'help with bedtime' but 'You do bedtime every night this week. I'm off duty at 7pm.'",
      "The key shift: from 'helping you' (you're still the manager) to 'owning it' (they carry the full cognitive load for that domain). Helping keeps you as the default. Ownership transfers the mental load entirely.",
    ],
    tryThis: "Pick ONE recurring task. Transfer full ownership: 'This is yours now. You plan it, you execute it, you remember it. I'm not going to remind you or check.' Then — and this is the hard part — let them do it imperfectly without intervening.",
    remember: "'I need help' asks them to assist you. 'This is yours' asks them to own it. Only ownership transfers the mental load.",
  },

  // ---- IDENTITY (2) ----
  {
    id: "id-maternal-identity-shift",
    title: "You Didn't Lose Yourself Overnight",
    subtitle: "It happened slowly. And the thread back is still there.",
    category: "identity",
    archetypes: ["the-disappeared", "quiet-volcano", "invisible-architect"],
    dimensions: ["identity-erosion"],
    tags: ["universal"],
    readTime: "3 min",
    body: [
      "Nobody tells you that becoming a mother involves a death. Not a physical one — an identity one. The person you were doesn't disappear in a dramatic moment. She erodes. Slowly. One cancelled plan at a time. One abandoned hobby at a time. One 'I'll do that later' that never comes.",
      "Psychologists call this 'matrescence' — the developmental transition of becoming a mother. Like adolescence, it involves a fundamental reorganization of identity, brain structure, hormones, and social role. Unlike adolescence, nobody acknowledges it's happening. There's no cultural framework for the grief of it.",
      "The grief is real. You're mourning a version of yourself that existed before. Her freedom. Her spontaneity. Her body. Her time. Her sense of self as a complete person rather than a function. And you're expected to do this mourning silently, while performing gratitude for the role that caused the loss.",
      "Here's what matters: the person you were is not dead. She's dormant. Buried under the weight of constant demand. The thread back to her is thin — but it's not broken. Every time you do one thing that has nothing to do with motherhood, you pull on that thread. You don't need a weekend retreat. You need 60 seconds of being a person, not a function. Repeatedly. Daily.",
    ],
    tryThis: "Finish this sentence without thinking: 'Before kids, I loved ___.' Whatever came to mind — do a 60-second version of it today. Listen to one song from that era. Look at one photo. Read one page. The thread is still there.",
    remember: "You didn't lose yourself. You were buried under the role. The person you were is dormant, not dead. Pull the thread. Daily.",
  },
  {
    id: "id-resentment-signal",
    title: "Resentment Is Not a Character Flaw",
    subtitle: "It's not ugly. It's your psyche telling you something is unsustainable.",
    category: "identity",
    archetypes: ["the-disappeared", "invisible-architect", "quiet-volcano"],
    dimensions: ["identity-erosion", "emotional-bandwidth"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You resent your partner. Maybe your kids. Maybe your entire life. And then you feel guilty for the resentment, which makes you resent everything more. The cycle is exhausting.",
      "Resentment is not a character flaw. It's a signal. Specifically, it's the signal that your needs have gone unmet for too long. It's what happens when you give more than you receive, consistently, without acknowledgment or reciprocity. It's the emotional equivalent of an overdraft fee — you've been spending from an account that no one is depositing into.",
      "The guilt you feel about the resentment is a second layer of harm. You're not allowed to be angry (because 'good mothers are grateful'), so you turn the anger inward (shame), which depletes you further, which creates more resentment. It's a trap designed to keep you silent.",
      "The resentment is not the problem. What's causing the resentment is the problem. Something is unsustainable. Something needs to change. The resentment is your psyche's way of saying: 'This arrangement is not working for me.' Listen to it.",
    ],
    tryThis: "Name the resentment specifically. Not 'I resent everything' but 'I resent that I'm the only one who notices when we're out of milk.' Specific resentments point to specific structural problems that can actually be solved.",
    remember: "Resentment is not ugly. It's information. It's telling you exactly where the imbalance is. Listen to it instead of shaming yourself for feeling it.",
  },

  // ---- SYSTEMS & STRUCTURE (2) ----
  {
    id: "sys-routine-adhd",
    title: "Why Routines Fail (and How to Build Ones That Don't)",
    subtitle: "They keep failing because they weren't built for your brain.",
    category: "systems-structure",
    archetypes: ["plate-spinner", "storm-weatherer", "running-on-empty"],
    dimensions: ["system-friction", "cognitive-load"],
    tags: ["adhd"],
    readTime: "3 min",
    body: [
      "You've tried routines. Morning routines, evening routines, cleaning routines. They work for 3 days and then collapse. You conclude: 'I'm just not a routine person.' But the problem isn't you — it's how the routines were designed.",
      "Most routine advice is designed for neurotypical brains: rigid schedules, specific times, long sequences, perfection expected. ADHD brains need the opposite: flexible anchors, body-based cues, short sequences, and forgiveness built in.",
      "The principles of ADHD-friendly routines: (1) Anchor to an existing behavior, not a time. 'After I pour coffee' is more reliable than '7:15am.' (2) Keep it to 3-5 steps maximum. Long sequences collapse. (3) Make it visible — a checklist on the wall, not a plan in your head. (4) Build in a 'good enough' version for bad days. (5) Expect it to break. Have a restart protocol, not a shame spiral.",
      "The most important principle: a routine that works 4 days out of 7 is not a failed routine. It's a successful one. Neurotypical consistency is 7/7. ADHD consistency is 4-5/7. That's still a routine. It's still structure. It's still helping.",
    ],
    tryThis: "Pick ONE transition point in your day that's consistently chaotic (morning, after school, bedtime). Write 3 steps — not 10 — on a card and put it where you'll see it. Do those 3 things in that order for one week. That's your routine. It doesn't need to be more.",
    remember: "A routine that works 4 days out of 7 is not a failure. It's an ADHD-friendly success. Stop designing for perfection. Design for 'good enough, most days.'",
  },
  {
    id: "sys-lowering-standards",
    title: "Lowering Standards Is a Strategy, Not a Failure",
    subtitle: "What if 'good enough' is actually the smartest strategy?",
    category: "systems-structure",
    archetypes: ["invisible-architect", "plate-spinner", "weight-bearer"],
    dimensions: ["system-friction", "cognitive-load", "physical-depletion"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You're trying to maintain standards that require more resources than you have. The house should be clean. Meals should be homemade. Kids should have enriching activities. You should exercise. You should have a social life. You should be present and patient. All of this. Every day. On a depleted brain and body.",
      "Here's the math: you have X units of energy. The life you're trying to maintain costs 2X. You can either: (a) burn out trying to close the gap, or (b) deliberately lower the cost of some areas so the math works.",
      "Lowering standards isn't giving up. It's triage. It's saying: 'I have limited resources. Where do they matter most?' Clean floors don't matter as much as a regulated parent. Homemade meals don't matter as much as a mother who isn't crying by 6pm. Instagram-worthy activities don't matter as much as a parent who can be present.",
      "The guilt of lowering standards is real. But the cost of maintaining impossible standards is higher: burnout, rage, disconnection, resentment. You're not choosing between 'good enough' and 'perfect.' You're choosing between 'sustainable' and 'collapse.'",
    ],
    tryThis: "Name one standard you're maintaining that costs you disproportionate energy. Ask: 'If I dropped this to 60% effort, what would actually happen?' Usually the answer is: nothing bad. The standard was serving your anxiety, not your family.",
    remember: "You're not failing by doing less. You're succeeding at sustainability. The alternative — maintaining everything until you break — helps no one.",
  },

  // ---- PARENTING (2) ----
  {
    id: "par-repair-over-prevention",
    title: "Repair Matters More Than Prevention",
    subtitle: "You yelled. Here's why what you do NEXT matters more.",
    category: "parenting",
    archetypes: ["quiet-volcano", "burning-engine", "weight-bearer"],
    dimensions: ["emotional-bandwidth"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "You yelled. You slammed a door. You said something you regret. And now you're spiraling: 'I've damaged them. I'm repeating my parents' patterns. They'll remember this forever.'",
      "Here's what the research actually shows: it's not the rupture that determines long-term outcomes. It's whether repair happens. Children who experience rupture WITH repair develop more secure attachment than children who experience no rupture at all. Repair teaches them: 'Relationships can survive conflict. Adults take responsibility. I am safe even when things go wrong.'",
      "What damages children is UNREPAIRED rupture — when the parent yells and then pretends it didn't happen, or blames the child, or never acknowledges it. That teaches: 'My feelings don't matter. Adults aren't safe. I must have deserved it.'",
      "You are not your parents if you repair. The cycle breaks not at the moment of rupture — it breaks at the moment of repair. Every time you go back and say 'I'm sorry. That wasn't okay. You didn't deserve that' — you are literally rewriting the pattern.",
    ],
    tryThis: "After your next rupture (it will happen — you're human), wait until your heart rate drops, then go to your child and say: 'I'm sorry I [specific behavior]. That wasn't okay. You didn't deserve that. I love you.' That's it. That's the whole repair.",
    remember: "You're not damaging your children by losing your temper. You're damaging them by not repairing afterward. Repair is where the cycle breaks.",
  },
  {
    id: "par-co-regulation",
    title: "You Can't Regulate a Child You Haven't Regulated Yourself",
    subtitle: "You can't calm them down until you calm yourself down first.",
    category: "parenting",
    archetypes: ["quiet-volcano", "burning-engine", "storm-weatherer"],
    dimensions: ["emotional-bandwidth", "physical-depletion"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "Your child is melting down. Every parenting book says: 'Stay calm. Be their anchor. Co-regulate.' And you want to scream: 'WITH WHAT? I have nothing left to regulate WITH.'",
      "Here's the neuroscience: co-regulation works through mirror neurons. Your child's nervous system literally syncs to yours. If you're dysregulated (heart racing, jaw clenched, voice tight), your child's nervous system reads that as 'danger' and escalates. If you're regulated (slow breath, soft voice, relaxed body), their system reads 'safe' and begins to calm.",
      "This is why 'just stay calm' is useless advice when you're depleted. You can't fake regulation — your child's nervous system reads your physiology, not your words. If your body is screaming 'threat,' your calm voice doesn't matter. They feel the truth.",
      "The implication is uncomfortable but important: your regulation IS your child's regulation. Taking care of your nervous system isn't selfish — it's literally the mechanism through which your child learns to calm down. Every time you regulate yourself first, you're teaching them how.",
    ],
    tryThis: "Next time your child is escalating: before you do ANYTHING for them, take 3 breaths. In for 4, out for 6. Drop your shoulders. Unclench your jaw. THEN engage. Those 15 seconds of self-regulation will do more than 15 minutes of talking at a dysregulated child.",
    remember: "You can't co-regulate from empty. Your calm IS their calm. Regulate yourself first — not as selfishness, but as the mechanism that actually works.",
  },
]