// ============================================================
// Micro-Guides — Batch 4 (guides 81-100)
// ============================================================

import type { MicroGuide } from "./types"

export const MICRO_GUIDES_BATCH4: MicroGuide[] = [
  // ---- EXECUTIVE FUNCTION (2 more) ----
  {
    id: "ef-context-switching",
    title: "Why One Interruption Ruins Your Whole Hour",
    subtitle: "The true cost of context switching",
    category: "executive-function",
    archetypes: ["plate-spinner", "invisible-architect", "burning-engine"],
    dimensions: ["cognitive-load"],
    readTime: "2 min",
    body: [
      "You were finally in flow — writing that email, cleaning the kitchen, having a thought — and then: 'Mom!' By the time you've handled the interruption (30 seconds), you've lost the thread entirely. It takes 23 minutes to fully re-engage with a task after an interruption. Twenty-three minutes. For a 30-second disruption.",
      "This isn't an ADHD-specific finding — it's universal. But for ADHD brains, it's worse because: (1) getting into flow was harder in the first place (task initiation), (2) the interrupted task may vanish from working memory entirely (object permanence), and (3) the emotional frustration of being interrupted depletes regulation resources.",
      "Motherhood is essentially a job of constant interruption. Children's needs are unpredictable, immediate, and non-negotiable. You're asked to maintain complex cognitive tasks while being interrupted every 3-7 minutes. No professional environment would expect this — but motherhood does, without acknowledgment.",
      "You're not failing to focus. You're being interrupted more than any human brain can sustain. The solution isn't better focus — it's protected windows. Even 20 minutes of uninterrupted time (partner takes over, kids in independent play, door closed) can accomplish what 2 hours of interrupted time cannot.",
    ],
    tryThis: "Tomorrow, create ONE 20-minute protected window. Tell your partner or set kids up with an activity. Close the door. Do one thing without interruption. Notice how much you accomplish — and how different your brain feels — compared to the fragmented rest of the day.",
    remember: "One interruption costs 23 minutes of re-engagement. You're not unfocused — you're over-interrupted. Protect small windows fiercely.",
  },
  {
    id: "ef-note-imperative",
    title: "'I'll Remember This' — You Won't",
    subtitle: "Why writing everything down isn't optional",
    category: "executive-function",
    archetypes: ["plate-spinner", "invisible-architect", "storm-weatherer"],
    dimensions: ["cognitive-load", "system-friction"],
    readTime: "2 min",
    body: [
      "The thought arrives: 'I need to buy milk.' 'I should call the dentist.' 'That permission slip is due Friday.' You think: 'I'll remember.' You won't. Not because you're careless. Because your working memory has a 30-second shelf life for non-urgent information.",
      "Every thought you don't capture is a thought you'll lose. And every lost thought becomes: a missed appointment, a forgotten birthday, a child without a costume on costume day, a bill paid late. The consequences accumulate. The shame accumulates. And the solution was always the same: write it down. Immediately. Every time.",
      "This isn't about being organized or having a perfect system. It's about accepting a neurological reality: your brain cannot hold information reliably. Full stop. Once you accept this — truly accept it, without shame — writing everything down becomes as natural as breathing. It's not a crutch. It's how your brain works.",
      "The tool doesn't matter. Phone notes, voice memos, a scrap of paper, a text to yourself. What matters is the habit: thought arrives → capture it immediately → trust the capture system instead of your memory. The gap between 'I'll remember' and 'I'll write it down' is the gap between chaos and function.",
    ],
    tryThis: "For one day, capture EVERY thought that requires future action. Every single one. Don't filter, don't organize — just dump it into one place (a note on your phone works). At the end of the day, look at the list. That's how much your brain was trying to hold invisibly.",
    remember: "'I'll remember' is the most expensive lie your brain tells you. Write it down. Immediately. Every time. Your memory is not reliable — your capture system is.",
  },

  // ---- EMOTIONAL REGULATION (2 more) ----
  {
    id: "er-perfectionism-loop",
    title: "The Perfectionism-Procrastination Loop",
    subtitle: "Why high standards keep you stuck",
    category: "emotional-regulation",
    archetypes: ["plate-spinner", "the-disappeared", "invisible-architect"],
    dimensions: ["emotional-bandwidth", "cognitive-load"],
    readTime: "2 min",
    body: [
      "You can't start because it won't be perfect. You can't finish because it's not good enough. You can't delegate because they won't do it right. Perfectionism looks like high standards from the outside. From the inside, it's paralysis.",
      "The perfectionism-procrastination loop: you set an impossibly high standard → the gap between where you are and where you 'should' be feels overwhelming → overwhelm triggers avoidance → avoidance creates guilt and shame → shame raises the standard even higher (to compensate) → the gap grows → more paralysis.",
      "For ADHD brains, perfectionism often develops as a compensatory strategy. Because you've been criticized for mistakes your whole life, you learned: 'If I do it perfectly, no one can criticize me.' The perfectionism isn't about excellence — it's about safety. It's armor against the shame of being 'not enough.'",
      "The exit from the loop is radical: done is better than perfect. A sent email with a typo is better than a perfect email never written. A 'good enough' dinner is better than a gourmet meal you were too paralyzed to start. Imperfect action beats perfect inaction. Every time.",
    ],
    tryThis: "Pick one thing you've been avoiding because it won't be perfect. Do the worst possible version of it. Intentionally bad. A terrible first draft. A half-cleaned room. Notice: the world didn't end. And now it's done.",
    remember: "Perfectionism isn't high standards — it's fear of criticism wearing a mask. Done beats perfect. Always. Lower the bar and move.",
  },
  {
    id: "er-compliments-uncomfortable",
    title: "Why Compliments Make You Uncomfortable",
    subtitle: "When praise doesn't match your internal narrative",
    category: "emotional-regulation",
    archetypes: ["the-disappeared", "quiet-volcano", "running-on-empty"],
    dimensions: ["emotional-bandwidth", "identity-erosion"],
    readTime: "2 min",
    body: [
      "Someone says 'You're such a good mom' and instead of feeling good, you feel: uncomfortable, fraudulent, anxious, or angry. You deflect, minimize, or change the subject. Compliments don't land — they bounce off. Why?",
      "When your internal narrative says 'I'm failing' and external feedback says 'you're doing great,' your brain experiences cognitive dissonance — two contradictory pieces of information that can't both be true. Rather than update the internal narrative (which is deeply held), your brain rejects the external feedback. The compliment feels wrong because it doesn't match your story about yourself.",
      "This is compounded by imposter syndrome: the belief that if people really knew what was happening behind the scenes — the yelling, the mess, the screen time, the frozen dinners — they'd take the compliment back. You feel like a fraud being praised for a performance, not a reality.",
      "The work isn't learning to accept compliments gracefully (that's surface). It's updating the internal narrative. Not from 'I'm failing' to 'I'm perfect' — but from 'I'm failing' to 'I'm doing hard things imperfectly, and that's enough.' When the internal story shifts, compliments start to land.",
    ],
    tryThis: "Next time someone compliments you: instead of deflecting, just say 'Thank you.' Nothing else. Let the discomfort exist without resolving it. Notice what your brain wants to say ('but they don't know...') and let that thought pass without acting on it.",
    remember: "Compliments bounce off because they contradict your internal story. The story — not the compliment — is what needs updating. You're not a fraud. You're a person doing hard things.",
  },

  // ---- PHYSICAL / NERVOUS SYSTEM (2 more) ----
  {
    id: "pns-chronic-pain-adhd",
    title: "The ADHD-Chronic Pain Connection",
    subtitle: "Why your body hurts and it's not 'just stress'",
    category: "physical-nervous-system",
    archetypes: ["running-on-empty", "burning-engine", "weight-bearer"],
    dimensions: ["physical-depletion"],
    readTime: "2 min",
    body: [
      "Your shoulders are concrete. Your jaw aches. Your back is always tight. You carry tension you don't notice until someone touches you and you flinch. This isn't 'just stress.' There's a documented connection between ADHD, chronic pain, and the nervous system.",
      "ADHD brains have differences in dopamine processing — and dopamine is involved in pain modulation. Lower dopamine means less natural pain suppression. Additionally, the chronic stress of managing life with executive dysfunction keeps your nervous system in a perpetual state of tension. Your muscles are bracing against a threat that never resolves.",
      "Impaired interoception (not noticing body signals) means you don't register tension until it becomes pain. You've been clenching your jaw for 6 hours without noticing. You've been holding your shoulders at your ears all day. The tension accumulates invisibly until it becomes chronic.",
      "The connection goes both ways: chronic pain worsens executive function (pain uses cognitive resources), and poor executive function worsens pain (you forget to stretch, can't maintain exercise, don't notice tension building). It's a feedback loop that requires intervention at both ends.",
    ],
    tryThis: "Right now: drop your shoulders. Unclench your jaw. Unfurrow your brow. Release your tongue from the roof of your mouth. Notice how much tension you were holding without awareness. Set a reminder to do this body scan 3 times today.",
    remember: "Your chronic pain isn't 'just stress' — it's connected to how your brain processes dopamine and body signals. The tension you don't notice is still costing you. Check in with your body on a schedule.",
  },
  {
    id: "pns-sensory-seeking",
    title: "Why You Crave Intensity",
    subtitle: "Sensory seeking in the understimulated brain",
    category: "physical-nervous-system",
    archetypes: ["plate-spinner", "burning-engine", "storm-weatherer"],
    dimensions: ["physical-depletion", "cognitive-load"],
    readTime: "2 min",
    body: [
      "You pick at your skin. You crave spicy food. You blast music. You scroll endlessly for something that hits. You start arguments for the adrenaline. You take on too much because boredom is physically painful. This isn't self-destructive — it's sensory seeking.",
      "ADHD brains are chronically understimulated. The baseline level of neural activation is lower than neurotypical brains, which means you need MORE input to feel 'normal.' When stimulation drops below your threshold, you feel: restless, agitated, bored to the point of pain, or desperately seeking something — anything — to activate your brain.",
      "Sensory seeking is your brain's attempt to self-regulate by increasing input. It's the same mechanism as a child who can't sit still — they're not misbehaving, they're seeking the stimulation their nervous system requires to function. In adults, it shows up as: phone addiction, overeating, overcommitting, skin picking, nail biting, or creating chaos.",
      "The key is recognizing seeking behavior for what it is (a need for stimulation) and finding healthier ways to meet it: intense exercise, cold showers, crunchy/spicy food, loud music with headphones, fidget tools, or high-stimulation tasks. Your brain needs intensity — give it intensity that doesn't cost you.",
    ],
    tryThis: "Next time you're restlessly scrolling or picking at yourself: recognize it as sensory seeking. Ask: 'What does my brain actually need right now?' Then try: ice on your wrist, a sour candy, 10 jumping jacks, or music turned up loud. Give your brain the intensity it's asking for.",
    remember: "Sensory seeking isn't self-destruction — it's your understimulated brain trying to reach baseline. Recognize the need and meet it intentionally instead of accidentally.",
  },

  // ---- HORMONAL (2 more) ----
  {
    id: "horm-postpartum-rage",
    title: "Postpartum Rage Is Real (and Underdiagnosed)",
    subtitle: "The anger no one warns you about",
    category: "hormonal",
    archetypes: ["quiet-volcano", "burning-engine", "running-on-empty"],
    dimensions: ["emotional-bandwidth", "physical-depletion"],
    readTime: "2 min",
    body: [
      "Everyone warns about postpartum depression — the sadness, the withdrawal, the inability to bond. Nobody warns about postpartum rage — the white-hot fury that comes from nowhere, directed at your partner, your older children, the world. It's terrifying. And it's far more common than anyone acknowledges.",
      "Postpartum rage is a manifestation of postpartum mood disorders, driven by the same hormonal upheaval as PPD but expressing differently. The massive drop in estrogen and progesterone after birth destabilizes serotonin and dopamine. For some women, this manifests as sadness. For others — especially those with ADHD or a history of anger — it manifests as rage.",
      "It's underdiagnosed because: (1) screening tools focus on sadness, not anger, (2) women are ashamed to report rage (it doesn't fit the 'struggling new mom' narrative), and (3) anger in mothers is pathologized as a character flaw rather than recognized as a symptom.",
      "If you're experiencing disproportionate rage in the postpartum period (or even years later, if depletion was never addressed): this is not a character flaw. It's a neurochemical state. It's treatable. And you deserve support for it — not judgment.",
    ],
    tryThis: "If rage is a significant part of your postpartum experience: mention it explicitly to your healthcare provider. Say: 'I'm experiencing intense anger that feels disproportionate and out of my control.' Many providers won't ask about rage specifically — you may need to name it yourself.",
    remember: "Postpartum rage is as real and valid as postpartum depression. It's hormonal, not moral. If you're experiencing it, you deserve support — not shame.",
  },
  {
    id: "horm-thyroid-mimics",
    title: "Is It ADHD or Is It Your Thyroid?",
    subtitle: "When a treatable condition mimics executive dysfunction",
    category: "hormonal",
    archetypes: ["running-on-empty", "plate-spinner", "weight-bearer"],
    dimensions: ["physical-depletion", "cognitive-load"],
    readTime: "2 min",
    body: [
      "Brain fog. Fatigue. Inability to concentrate. Memory problems. Weight changes. Mood swings. These are ADHD symptoms — but they're also thyroid symptoms. And thyroid disorders are 5-8 times more common in women, especially postpartum.",
      "Hypothyroidism (underactive thyroid) mimics ADHD almost perfectly: cognitive sluggishness, poor working memory, fatigue, difficulty initiating tasks, emotional flatness or irritability. Hyperthyroidism (overactive) mimics the hyperactive/impulsive presentation: restlessness, racing thoughts, anxiety, inability to sit still.",
      "The critical difference: thyroid disorders are treatable with medication that works within weeks. If some of your 'ADHD symptoms' are actually thyroid-driven, treating the thyroid can dramatically improve function — sometimes more than ADHD medication alone.",
      "This doesn't mean you don't have ADHD. You can have both. But if you've never had your thyroid properly checked (TSH alone isn't enough — you need Free T3, Free T4, and thyroid antibodies), you might be fighting a battle on two fronts while only addressing one.",
    ],
    tryThis: "If you haven't had comprehensive thyroid testing: ask your doctor for TSH, Free T3, Free T4, and thyroid antibodies (TPO and TG). Especially if your symptoms worsened postpartum or you have a family history of thyroid issues. It's a simple blood test that could change everything.",
    remember: "Thyroid disorders mimic ADHD almost perfectly and are extremely common in women postpartum. A simple blood test could reveal a treatable condition hiding behind your symptoms.",
  },

  // ---- RELATIONSHIPS (2 more) ----
  {
    id: "rel-intimacy-touched-out",
    title: "Intimacy When You're Touched Out",
    subtitle: "Navigating physical connection when your body says no",
    category: "relationships",
    archetypes: ["running-on-empty", "quiet-volcano", "the-disappeared"],
    dimensions: ["physical-depletion", "emotional-bandwidth", "identity-erosion"],
    readTime: "3 min",
    body: [
      "Your partner wants physical closeness. You want to not be touched by another human being for the next 72 hours. The guilt is immediate: 'I should want this. What's wrong with me? Am I broken? Is my relationship dying?'",
      "Nothing is wrong with you. Your nervous system has a touch budget — and your children have spent it. By the end of a day of being climbed on, nursed, grabbed, and clung to, your somatosensory system is maxed. Additional touch — even loving touch — registers as overwhelm, not comfort.",
      "This is compounded by: sensory processing differences (ADHD/autism), physical depletion (your body has nothing left to give), identity erosion (you feel like a body that serves others, not a person with desire), and the mental load (you can't be present in your body when your brain is running logistics).",
      "The conversation with your partner isn't 'I don't want you.' It's 'My body is at capacity and I need it to be mine for a while before I can share it.' This isn't rejection — it's honest communication about a physiological state. A partner who understands this can be part of the solution instead of another demand.",
      "Intimacy doesn't have to mean physical touch. Connection can be: talking without kids present, watching something together, a hand held briefly, or simply being in the same room without anyone needing anything from either of you. Redefine intimacy for this season.",
    ],
    tryThis: "Have the conversation before the moment: 'I want to be close to you, AND my body is at capacity most evenings. Can we find ways to connect that don't require me to be touched? And can we plan physical intimacy for times when I have more capacity — not less?'",
    remember: "Being touched out isn't rejection of your partner. It's your nervous system at capacity. Name it honestly. Redefine intimacy for this season. It won't be this way forever.",
  },
  {
    id: "rel-support-try-harder",
    title: "When People Say 'Just Try Harder'",
    subtitle: "How to respond to people who don't understand",
    category: "relationships",
    archetypes: ["plate-spinner", "weight-bearer", "the-disappeared"],
    dimensions: ["emotional-bandwidth", "identity-erosion"],
    readTime: "2 min",
    body: [
      "'Have you tried a planner?' 'Just set an alarm.' 'You just need to be more organized.' 'Other moms manage.' The advice comes from people who mean well but fundamentally don't understand that your brain works differently. And each suggestion — however well-intentioned — lands as: 'The problem is you. Try harder.'",
      "The 'just try harder' advice assumes a neurotypical brain. It assumes that the gap between intention and action is bridged by effort. For ADHD brains, that gap is neurological — not motivational. You're not failing to try. You're trying with a brain that doesn't convert intention to action the way theirs does.",
      "You don't owe anyone an explanation of your neurology. But if you want to help someone understand, try: 'My brain doesn't work that way. I've tried those things — they don't stick for me because my executive function works differently. What I need isn't advice. It's understanding.'",
      "For the people who can't or won't understand: boundaries. You don't have to educate everyone. You don't have to justify your struggles. 'I appreciate the suggestion' is a complete response. You can stop there. Their understanding is not required for your validity.",
    ],
    tryThis: "Prepare one sentence for the next time someone offers 'just try harder' advice: 'My brain works differently than yours. I'm not looking for solutions right now — I'm looking for understanding.' Practice it. Have it ready.",
    remember: "You don't owe anyone an explanation for why their advice doesn't work for your brain. 'My brain works differently' is a complete sentence. Their understanding is not required for your validity.",
  },

  // ---- IDENTITY (2 more) ----
  {
    id: "id-five-minute-self",
    title: "Finding Yourself in 5-Minute Increments",
    subtitle: "Identity rebuilds through micro-actions, not grand gestures",
    category: "identity",
    archetypes: ["the-disappeared", "running-on-empty", "invisible-architect"],
    dimensions: ["identity-erosion"],
    readTime: "2 min",
    body: [
      "You don't have time for yourself. Not an hour. Not even 30 minutes. The advice to 'take time for you' feels like a cruel joke when you can barely shower alone. So you conclude: identity rebuilding will have to wait until the kids are older. It won't. It can happen in 5 minutes.",
      "Identity doesn't rebuild through retreats and spa days (though those are nice). It rebuilds through repeated micro-contacts with who you are outside of 'mom.' Five minutes of something that's YOURS — not productive, not for anyone else, not optimized — is enough to keep the thread alive.",
      "Five-minute identity acts: listen to one song from before kids (the whole song, with your eyes closed). Read one page of a book that's just for you. Look at one photo from a time you felt like yourself. Text one friend about something that isn't your children. Write one sentence about how you feel. Step outside and look at the sky for 60 seconds without purpose.",
      "These feel insignificant. They're not. Each one is a vote for the person underneath the role. Each one says: 'I still exist. I still have preferences. I still matter as a person, not just a function.' Repeated daily, they compound into something that feels like a self again.",
    ],
    tryThis: "Right now: do one 5-minute identity act. Not later. Now. Listen to a song. Read a page. Look at something beautiful. Set a timer if you need permission. Five minutes. That's all. Then notice: you still exist in there.",
    remember: "You don't need an hour to find yourself. You need 5 minutes, repeated daily. Identity rebuilds through micro-contacts, not grand gestures. One song. One page. One moment of being a person.",
  },
  {
    id: "id-self-care-vs-maintenance",
    title: "Self-Care vs. Self-Maintenance",
    subtitle: "Why 'self-care' feels like another chore",
    category: "identity",
    archetypes: ["running-on-empty", "the-disappeared", "invisible-architect"],
    dimensions: ["identity-erosion", "physical-depletion"],
    readTime: "2 min",
    body: [
      "The internet says self-care is: bubble baths, face masks, journaling, yoga, meditation. You try these things and feel... nothing. Or worse — guilty for 'wasting time.' Self-care has become another item on the to-do list. Another thing you're failing at.",
      "Here's the distinction that changes everything: self-maintenance is keeping yourself functional (showering, eating, sleeping, medical appointments). Self-care is doing something that fills you up (not just prevents you from breaking down). Most of what's marketed as 'self-care' is actually self-maintenance dressed up in candles.",
      "Real self-care is anything that makes you feel more like yourself — not more functional, not more productive, not more relaxed for the benefit of others. It might be: reading trash fiction, watching a show your partner hates, going for a drive alone with loud music, sitting in a parking lot doing nothing, or having a conversation about something that isn't kids.",
      "The test: does this activity exist for YOUR enjoyment, or does it exist to make you a better mother/partner/employee? If it's the latter, it's maintenance. If it's the former — if it serves no purpose except your own pleasure — that's care. And you deserve both.",
    ],
    tryThis: "Name one thing you do purely for your own enjoyment — not because it makes you healthier, calmer, or more productive. Just because you like it. If you can't name one, that's the problem. Find one. Protect it.",
    remember: "Self-care isn't a bath bomb. It's anything that makes you feel like a person, not a function. If it only exists to make you 'better' for others, it's maintenance. Real care serves no one but you.",
  },

  // ---- SYSTEMS & STRUCTURE (2 more) ----
  {
    id: "sys-batch-processing",
    title: "Batch Processing for ADHD Brains",
    subtitle: "Do similar tasks together instead of scattered",
    category: "systems-structure",
    archetypes: ["plate-spinner", "invisible-architect", "storm-weatherer"],
    dimensions: ["cognitive-load", "system-friction"],
    readTime: "2 min",
    body: [
      "You make one phone call, then switch to email, then start laundry, then remember the other phone call, then check the email again. Each switch costs cognitive resources. By the end of the day, you've done 20 things but finished 3. The rest are half-done, scattered across your attention.",
      "Batch processing is the opposite: group similar tasks and do them together. All phone calls in one block. All emails in one sitting. All meal prep at once. All errands in one trip. Instead of switching between task types 50 times a day, you switch 5 times.",
      "Why this works for ADHD brains: each task type requires a different 'mode' — phone calls need social energy, emails need writing energy, physical tasks need body energy. Switching modes is expensive. Staying in one mode and completing multiple tasks of that type is dramatically more efficient.",
      "The practical version: designate 'admin time' (15 minutes, all emails/texts/forms at once), 'errand time' (one trip, all stops), 'cleaning time' (30 minutes, all rooms), 'planning time' (one sitting, whole week). Batch by type, not by urgency.",
    ],
    tryThis: "Tomorrow, batch your communication: instead of responding to messages throughout the day, check and respond twice — once mid-morning, once mid-afternoon. Notice how much less fragmented your day feels when you're not constantly switching modes.",
    remember: "Switching between task types costs more than the tasks themselves. Group similar things together. One mode at a time. Batch, don't scatter.",
  },
  {
    id: "sys-visual-timers",
    title: "Visual Timers Change Everything",
    subtitle: "Making invisible time visible",
    category: "systems-structure",
    archetypes: ["plate-spinner", "storm-weatherer", "burning-engine"],
    dimensions: ["cognitive-load", "system-friction"],
    readTime: "2 min",
    body: [
      "Time is invisible. For ADHD brains that can't feel time passing internally, invisible time might as well not exist. This is why 'you have 10 minutes' means nothing — you can't see 10 minutes. You can't feel them shrinking. Until suddenly they're gone and you're late again.",
      "Visual timers solve this by making time physical. A Time Timer (the red disk that shrinks), a sand timer, or even a phone timer with a visual countdown — these translate abstract time into something your brain can perceive: a shrinking shape, falling sand, a moving bar.",
      "For children AND adults with ADHD, visual timers reduce transition difficulty (you can SEE the end approaching), improve time estimation (you learn what 10 minutes actually looks like), reduce anxiety (no surprise endings), and support task completion (the visual creates gentle urgency).",
      "Use them for: morning routines (15-minute timer visible to everyone), transitions ('when the timer ends, we leave'), focused work blocks (25-minute Pomodoro), and self-care ('10 minutes of rest — watch the timer so you don't feel guilty about stopping').",
    ],
    tryThis: "Get a visual timer (a Time Timer app on your phone works, or a cheap sand timer). Use it tomorrow morning: set 15 minutes visible to everyone. 'When the red is gone, we leave.' Notice how much smoother the transition is when time is visible instead of abstract.",
    remember: "You can't manage time you can't see. Visual timers make the invisible visible — for you AND your kids. They're not childish. They're assistive technology for time-blind brains.",
  },

  // ---- PARENTING (2 more) ----
  {
    id: "par-morning-chaos",
    title: "Morning Chaos Has 3 Real Levers",
    subtitle: "Stop fighting the morning — redesign it",
    category: "parenting",
    archetypes: ["plate-spinner", "storm-weatherer", "burning-engine"],
    dimensions: ["system-friction", "cognitive-load", "emotional-bandwidth"],
    readTime: "2 min",
    body: [
      "Every morning is a disaster. You're yelling by 7:30. Someone can't find their shoes. Someone won't eat. Someone is melting down about socks. You leave late, frazzled, and already depleted before the day has started. You've tried everything. Nothing sticks.",
      "Morning chaos has three actual levers — and most advice only addresses one. The levers are: (1) What happens the night before, (2) How many decisions exist in the morning, and (3) How many transitions are required. Fix any one of these and mornings improve. Fix all three and they transform.",
      "Lever 1 — The night before: clothes laid out, bags packed, lunches made, shoes by the door. Every decision made tonight is one eliminated tomorrow. Morning-you has less executive function than evening-you. Do the thinking now.",
      "Lever 2 — Decisions: reduce to zero where possible. Same breakfast options every day (pick from 2-3, not infinite). Same getting-ready order (checklist on the wall). Same departure routine. No choosing, no negotiating, no improvising.",
      "Lever 3 — Transitions: minimize them. Wake up → get dressed (in the same room, clothes already there). Dressed → eat (go directly, no detours). Eat → shoes and door (launch pad ready). Each transition is a potential failure point. Fewer transitions = fewer meltdowns.",
    ],
    tryThis: "Tonight: lay out tomorrow's clothes (yours and kids'), pack bags, put shoes by the door. Tomorrow morning, notice: which parts were smoother? That's lever 1 working. Next, tackle lever 2 (reduce choices) or lever 3 (reduce transitions).",
    remember: "Morning chaos isn't a discipline problem. It's a design problem. Three levers: prep the night before, eliminate decisions, minimize transitions. Fix the design, not the people.",
  },
  {
    id: "par-letting-go-parent",
    title: "Letting Go of the Parent You Thought You'd Be",
    subtitle: "Grieving the gap between expectation and reality",
    category: "parenting",
    archetypes: ["the-disappeared", "quiet-volcano", "weight-bearer"],
    dimensions: ["identity-erosion", "emotional-bandwidth"],
    readTime: "3 min",
    body: [
      "Before kids, you had a vision. Patient. Creative. Present. Fun. The kind of mom who does art projects and bakes cookies and never raises her voice. The kind of mom your kids would describe as 'warm' and 'always there.' That mom doesn't exist. And the gap between her and you is a source of daily grief.",
      "The parent you imagined was created without data. She didn't know about your nervous system, your executive function, your sensory limits, your hormonal fluctuations, or the reality of doing this with minimal support. She was designed in a vacuum — and she was never achievable. Not by you. Not by anyone with your neurology in your circumstances.",
      "Grieving this imagined parent is necessary. Not because she was realistic — but because holding onto her as the standard keeps you in perpetual failure. You can't meet a standard that was designed for a person who doesn't exist, in circumstances that don't match yours.",
      "The parent you actually are — imperfect, depleted, trying, repairing, showing up on hard days, loving fiercely even when you can't show it perfectly — is enough. Not because the bar is low. Because the bar was always in the wrong place. Your children don't need the imagined parent. They need the real one. The one who stays. The one who tries again tomorrow.",
    ],
    tryThis: "Write a letter to the parent you thought you'd be. Thank her for the vision. Then let her go: 'You were created without knowing what I'd be working with. I release you. The parent I actually am is enough for the children I actually have.'",
    remember: "The parent you imagined was designed without data. She didn't know your brain, your body, or your circumstances. Let her go. The parent you actually are — imperfect and present — is what your children need.",
  },
]