// ============================================================
// Micro-Guides — Batch 5 (guides 88-100)
// Filling gaps to reach 100
// ============================================================

import type { MicroGuide } from "./types"

export const MICRO_GUIDES_BATCH5: MicroGuide[] = [
  {
    id: "ef-starting-projects",
    title: "Why You Start 10 Projects and Finish None",
    subtitle: "The trail of half-finished projects behind you isn't laziness.",
    category: "executive-function",
    archetypes: ["plate-spinner", "the-disappeared", "storm-weatherer"],
    dimensions: ["cognitive-load"],
    readTime: "2 min",
    body: [
      "The closet reorganization you started in March. The craft project from last summer. The online course you signed up for. The garden that got planted but never maintained. You have a trail of 80%-done projects behind you and the shame of each one weighs on you.",
      "This is the novelty-completion gap. ADHD brains are fueled by novelty — new things flood the brain with dopamine. Starting is exciting. The middle is boring. And boring tasks don't generate enough dopamine to sustain attention. So you start the next new thing, chasing the dopamine hit of beginning.",
      "It's not that you can't finish things. It's that finishing requires sustained effort on something that's no longer novel — and your brain literally doesn't produce the neurochemistry to support that. The last 20% of any project is the hardest 20% for an ADHD brain because all the novelty is gone.",
      "The workaround: make the ending novel. Change your environment for the final push. Add a reward at completion. Set a deadline with external accountability. Or — radical acceptance — decide that some projects don't need finishing. Not everything started needs to be completed. Some things served their purpose in the starting.",
    ],
    tryThis: "Look at your unfinished projects. For each one ask: 'Does this actually need finishing, or did I get what I needed from starting it?' Give yourself permission to officially abandon the ones that don't matter. Close the loop mentally even if you don't close it physically.",
    remember: "You're not flaky. Your brain runs on novelty, and finishing isn't novel. Either make the ending interesting, or give yourself permission to let it go.",
  },
  {
    id: "er-emotional-labor",
    title: "Emotional Labor Is Depleting You Invisibly",
    subtitle: "You manage the emotional temperature of your entire household. Invisibly.",
    category: "emotional-regulation",
    archetypes: ["invisible-architect", "quiet-volcano", "the-disappeared"],
    dimensions: ["emotional-bandwidth", "identity-erosion"],
    readTime: "2 min",
    body: [
      "You manage the emotional temperature of your entire household. You notice when your partner is stressed and adjust. You anticipate your child's meltdown and prevent it. You smooth over conflicts. You remember to ask about the thing that was worrying them. You hold everyone's emotional state in your awareness — constantly.",
      "This is emotional labor — and it's distinct from emotional support. Support is: being there when someone is upset. Labor is: monitoring, anticipating, managing, and regulating everyone's emotions proactively, without being asked, without acknowledgment, without reciprocity.",
      "The cost is invisible because the work is invisible. No one sees you deciding not to mention the thing that would upset your partner. No one sees you redirecting the conversation before it triggers your child. No one sees you swallowing your own feelings because there's no room for them alongside everyone else's.",
      "Emotional labor depletes the same resources as cognitive labor — it uses working memory (tracking everyone's states), executive function (planning responses), and emotional regulation (suppressing your own needs). By evening, you're empty — not from what you did, but from what you held.",
    ],
    tryThis: "For one day, notice every time you manage someone else's emotional state — every time you adjust, smooth, prevent, or suppress. Don't change anything yet. Just count. The number will be staggering. That's the invisible work you're doing.",
    remember: "Emotional labor is real work that uses real cognitive resources. The exhaustion you feel isn't from 'nothing' — it's from holding everyone's emotional world in your head all day.",
  },
  {
    id: "pns-gut-brain",
    title: "Your Gut Is Talking to Your Brain",
    subtitle: "Your stomach and your brain are in constant conversation.",
    category: "physical-nervous-system",
    archetypes: ["running-on-empty", "burning-engine", "weight-bearer"],
    dimensions: ["physical-depletion", "emotional-bandwidth"],
    readTime: "2 min",
    body: [
      "You're anxious and your stomach hurts. Or you're stressed and you can't eat. Or you're overwhelmed and your digestion is a mess. This isn't coincidence — your gut and brain are in constant bidirectional communication through the vagus nerve and the enteric nervous system.",
      "Your gut produces approximately 90% of your body's serotonin and 50% of its dopamine. When your gut is inflamed, malnourished, or disrupted (from stress, poor diet, or irregular eating), neurotransmitter production drops. Less serotonin = more anxiety and depression. Less dopamine = worse ADHD symptoms.",
      "The stress-gut loop: stress disrupts digestion → disrupted digestion reduces neurotransmitter production → reduced neurotransmitters worsen mood and executive function → worsened function increases stress → more digestive disruption. It's a cycle that can be interrupted at any point.",
      "For overwhelmed mothers who skip meals, eat standing up, rely on coffee and adrenaline, and never sit down for a proper meal — the gut-brain axis is almost certainly compromised. This isn't about 'clean eating' or wellness culture. It's about basic fuel for basic brain function.",
    ],
    tryThis: "This week: eat one meal per day sitting down, without multitasking, chewing slowly. Just one. Notice if your digestion and your mood shift even slightly. Your gut needs calm to function — and your brain needs your gut to function.",
    remember: "Your gut makes most of your serotonin and dopamine. When you skip meals, eat in chaos, or run on coffee — your brain chemistry suffers directly. Feed your gut and you feed your brain.",
  },
  {
    id: "horm-pmdd",
    title: "PMDD Is Not 'Bad PMS'",
    subtitle: "If you lose a week of your life every month, that's not 'just PMS.'",
    category: "hormonal",
    archetypes: ["quiet-volcano", "burning-engine", "weight-bearer"],
    dimensions: ["emotional-bandwidth", "physical-depletion"],
    readTime: "2 min",
    body: [
      "PMS is uncomfortable. PMDD (Premenstrual Dysphoric Disorder) is disabling. If the week before your period involves: suicidal thoughts, rage so intense you scare yourself, complete inability to function, feeling like a different person, or relationship-destroying emotional episodes — that's not 'just hormones.' That's PMDD.",
      "PMDD affects 3-8% of menstruating women and is significantly more common in women with ADHD. It's caused by an abnormal sensitivity to normal hormonal fluctuations — your hormone levels may be 'normal' on blood tests, but your brain's response to them is amplified.",
      "The distinction matters because PMDD is treatable — with SSRIs (which can be taken only during the luteal phase), hormonal interventions, or other targeted approaches. But it's chronically underdiagnosed because: women minimize their symptoms ('it's just PMS'), providers dismiss them ('that's normal'), and the cyclical nature means you feel fine for 3 weeks and forget how bad the fourth week was.",
      "If you lose 1-2 weeks of functional capacity every month to premenstrual symptoms — that's not something to push through. That's a medical condition that deserves treatment.",
    ],
    tryThis: "Track your worst symptoms against your cycle for 2-3 months. If they consistently cluster in the 7-10 days before your period AND resolve within a few days of bleeding starting — bring this data to your doctor and ask specifically about PMDD.",
    remember: "PMDD is not 'bad PMS.' It's a diagnosable, treatable condition. If you lose a week of your life every month to premenstrual symptoms, you deserve medical support — not dismissal.",
    caveat: "This guide describes a medical condition that requires professional diagnosis and treatment. If this resonates, please discuss with your healthcare provider. Self-diagnosis is a starting point for conversation, not a conclusion.",
  },
  {
    id: "rel-mental-load-conversation",
    title: "How to Actually Have the Mental Load Conversation",
    subtitle: "How to actually have this conversation without it becoming a fight.",
    category: "relationships",
    archetypes: ["invisible-architect", "quiet-volcano", "the-disappeared"],
    dimensions: ["system-friction", "emotional-bandwidth"],
    readTime: "3 min",
    body: [
      "You need to talk to your partner about the mental load. You've tried before — it turned into a fight, or they got defensive, or nothing changed. The conversation feels impossible. But it's necessary. Here's a framework that actually works.",
      "Step 1 — Choose the right moment. Not during a fight. Not when you're depleted. Not when they're stressed. Pick a calm moment and say: 'I need to talk about something important. Not right now if you're not ready — but soon. When works for you?' This gives them preparation time instead of ambush.",
      "Step 2 — Lead with impact, not blame. Not: 'You never help.' Instead: 'I'm carrying something that's making me resentful, and I don't want resentment in our relationship. I need to show you what I'm holding.' Then show them — the list, the invisible tasks, the cognitive weight. Make the invisible visible.",
      "Step 3 — Ask for ownership, not help. Not: 'Can you help more?' Instead: 'I need you to fully own [specific domain]. That means: you think about it, you plan it, you execute it, you remember it. I don't want to manage it or remind you. I need it off my plate entirely.'",
      "Step 4 — Expect imperfection. They will do it differently than you. Probably worse at first. That's the cost of redistribution. If you take it back every time it's not done your way, you'll never actually transfer the load. Let it be imperfect. The goal is equity, not your standard applied by someone else.",
    ],
    tryThis: "Pick ONE domain to transfer. Start small: 'You own kids' lunches this week. Planning, shopping, packing — all of it. I won't remind you or check.' Then: actually let go. Don't hover. Don't redo. Let them figure it out.",
    remember: "The mental load conversation isn't about blame — it's about sustainability. Lead with impact, ask for ownership (not help), and tolerate imperfection. Equity doesn't mean identical — it means equitable cognitive weight.",
  },
  {
    id: "id-reclaiming-no",
    title: "Reclaiming 'No' as a Complete Sentence",
    subtitle: "'No' is a complete sentence. Here's why you can't say it without a paragraph.",
    category: "identity",
    archetypes: ["the-disappeared", "quiet-volcano", "invisible-architect"],
    dimensions: ["identity-erosion", "emotional-bandwidth"],
    readTime: "2 min",
    body: [
      "'No, I can't, because...' and then you give three reasons, an apology, an alternative suggestion, and a promise to make it up to them. You can't just say no. You have to justify it. Explain it. Earn the right to decline. Why?",
      "Over-explaining 'no' comes from a core belief: 'My needs are not sufficient reason to decline. I need an external excuse.' This belief was usually installed early — by parents who required justification for every boundary, by a culture that rewards female compliance, or by relationships where 'no' was met with punishment.",
      "The over-explanation also serves a protective function: if you give enough reasons, maybe they won't be angry. Maybe they'll understand. Maybe you can say no without losing their approval. But here's what actually happens: the more you explain, the more they argue with your reasons. Every reason you give is a handle they can grab to pull you back to 'yes.'",
      "'No' is a complete sentence. It doesn't require justification, explanation, or apology. You can offer a reason if you want to — but you don't owe one. The discomfort you feel saying a bare 'no' is the old conditioning protesting. It's not evidence that you're being rude. It's evidence that you're doing something new.",
    ],
    tryThis: "Practice a bare 'no' on something low-stakes this week. 'Can you volunteer for the bake sale?' 'No, I can't this time.' Full stop. No reason. No apology. Notice the discomfort — and notice that nothing bad actually happens.",
    remember: "'No' is a complete sentence. You don't owe an explanation for having limits. The discomfort of saying it is old conditioning — not evidence of wrongdoing.",
  },
  {
    id: "sys-two-minute-rule",
    title: "The Two-Minute Rule (Actually Works for ADHD)",
    subtitle: "Every small task you defer is an open loop draining your brain.",
    category: "systems-structure",
    archetypes: ["plate-spinner", "storm-weatherer", "invisible-architect"],
    dimensions: ["cognitive-load", "system-friction"],
    readTime: "2 min",
    body: [
      "The two-minute rule is simple: if a task takes less than 2 minutes to complete, do it immediately instead of adding it to your mental list. Hang up the coat. Reply to the text. Put the dish in the dishwasher. Wipe the counter. Sign the form. Done.",
      "Why this works for ADHD brains specifically: every task you defer — no matter how small — occupies space in your working memory. It becomes another 'open loop' your brain has to track. Ten deferred 2-minute tasks = ten open loops = significant cognitive load. Doing them immediately closes the loop and frees the space.",
      "The rule also bypasses task initiation problems. You don't have to 'decide to start' a 2-minute task — you just do it in the moment you notice it. The decision cost is zero because the rule already made the decision for you: under 2 minutes = now. No deliberation needed.",
      "Important caveat: this only works for tasks that genuinely take under 2 minutes. If you start 'quickly' organizing a drawer and 45 minutes disappear — that wasn't a 2-minute task. Be honest about what's actually quick and what's a hyperfocus trap disguised as a small task.",
    ],
    tryThis: "For the rest of today: every time you notice something that would take under 2 minutes, do it immediately. Don't add it to a list. Don't 'do it later.' Just do it now. Count how many open loops you close by bedtime.",
    remember: "Every deferred 2-minute task is an open loop in your working memory. Close it immediately and free the space. The rule makes the decision for you: under 2 minutes = now.",
  },
  {
    id: "par-homework-battles",
    title: "Homework Battles With an ADHD Brain (Yours or Theirs)",
    subtitle: "Two depleted brains fighting over a boring task at 4pm. No wonder it's awful.",
    category: "parenting",
    archetypes: ["plate-spinner", "burning-engine", "quiet-volcano"],
    dimensions: ["cognitive-load", "emotional-bandwidth"],
    readTime: "3 min",
    body: [
      "It's 4pm. Homework needs to happen. Your child can't start. You can't make them start. You're both dysregulated within 5 minutes. The yelling begins. The crying begins. Everyone ends up worse than before. This is not a parenting failure — it's two depleted brains colliding over a task that requires executive function neither of you has left.",
      "Why homework is uniquely terrible: it happens at the worst time of day (afternoon, when cortisol and dopamine are lowest), it requires task initiation (the hardest executive function skill), it's boring (no dopamine reward), and it involves a parent-child power dynamic that activates everyone's worst patterns.",
      "If your child has ADHD (diagnosed or suspected): they literally cannot 'just sit down and do it.' Their brain needs: a transition buffer (10 minutes of decompression after school before starting), a body break (movement before sitting), a snack (fuel for cognitive work), reduced choice ('start with math' not 'what do you want to do first?'), and your calm presence (body doubling).",
      "If YOU have ADHD: you're being asked to supervise a boring task while depleted, which is your personal hell. Strategies: set a timer (external structure for both of you), do your own 'homework' alongside them (body doubling works both ways), keep it short (20 minutes max, then break), and lower your standard (done > perfect).",
    ],
    tryThis: "Tomorrow's homework: snack first, 10 minutes of play/movement, then sit together with a timer set for 20 minutes. You do something alongside them (bills, emails, reading). When the timer goes off, stop — regardless of completion. Rebuild from there.",
    remember: "Homework battles aren't about discipline. They're about two depleted brains fighting over a task that requires resources neither has at 4pm. Lower the bar, shorten the window, and sit together.",
  },
  {
    id: "par-meltdown-not-failure",
    title: "Your Child's Meltdown Is Not Your Failure",
    subtitle: "Their meltdown is not your report card.",
    category: "parenting",
    archetypes: ["quiet-volcano", "weight-bearer", "the-disappeared"],
    dimensions: ["emotional-bandwidth", "identity-erosion"],
    readTime: "2 min",
    body: [
      "Your child is screaming in the grocery store. Or hitting their sibling. Or refusing to get dressed. And the voice in your head says: 'If I were a better mother, this wouldn't be happening. Other kids don't do this. I'm failing them.'",
      "Your child's behavior is not a report card on your parenting. Children melt down because: they're developmentally immature (their prefrontal cortex won't be fully developed until age 25), they're tired/hungry/overstimulated, they're processing big emotions with small tools, or they have their own neurodivergent brain that processes the world intensely.",
      "None of these causes are: your fault, evidence of bad parenting, something you could have prevented with better strategies, or a reflection of your worth as a mother. Children with the most attuned, responsive parents still melt down. Because they're children. That's what children do.",
      "The shame you feel during their meltdown is often about the perceived judgment of others — the looks in the store, the comments from family, the comparison to 'well-behaved' children. But other people's judgment is about their discomfort, not your competence. Your child is having a hard time. That's not the same as you doing a bad job.",
    ],
    tryThis: "Next time your child melts down in public: instead of 'what am I doing wrong?' ask 'what does my child need right now?' Shift from self-judgment to curiosity about their experience. Their meltdown is about THEM — not about you.",
    remember: "Your child's behavior is not your report card. Children melt down because they're children — not because you failed. Separate their experience from your worth.",
  },
  {
    id: "pns-social-exhaustion",
    title: "Why Socializing Drains You Completely",
    subtitle: "2 hours of socializing. 24 hours of recovery. That's not introversion.",
    category: "physical-nervous-system",
    archetypes: ["the-disappeared", "running-on-empty", "quiet-volcano"],
    dimensions: ["physical-depletion", "emotional-bandwidth"],
    readTime: "2 min",
    body: [
      "You went to the birthday party. You smiled, chatted, performed 'normal mom.' And now you're wrecked — not just tired, but completely emptied. You need 24 hours to recover from 2 hours of socializing. People say 'you're just introverted.' It's more than that.",
      "Social exhaustion in ADHD/neurodivergent women comes from masking — the constant, conscious effort to appear neurotypical in social settings. You're monitoring your facial expressions, filtering your responses, tracking the conversation, suppressing impulses to interrupt, managing sensory input, and performing 'appropriate' social behavior. All simultaneously. All consciously.",
      "Neurotypical people do most of this automatically — it costs them minimal energy. For neurodivergent brains, every social behavior that others do on autopilot requires conscious executive function. It's like manually breathing — possible, but exhausting when sustained.",
      "The recovery time isn't weakness or antisocial behavior. It's your brain needing to restore the resources that masking depleted. The 24-hour 'social hangover' is proportionate to the effort expended — you just can't see the effort because it happened inside your head.",
    ],
    tryThis: "After your next social event: plan recovery time in advance. Not as a 'maybe if I need it' but as a non-negotiable. 'After the party, I have 2 hours of nothing.' Treat it like a medical appointment — because neurologically, it is.",
    remember: "Social exhaustion isn't introversion — it's the cost of masking. Every social behavior that others do automatically costs you conscious effort. Plan recovery as non-negotiable, not optional.",
  },
  {
    id: "sys-anchor-habits",
    title: "Anchor Habits: The One Thing That Holds Everything Else",
    subtitle: "You don't need 10 new habits. You need one that holds on your worst day.",
    category: "systems-structure",
    archetypes: ["storm-weatherer", "running-on-empty", "weight-bearer"],
    dimensions: ["system-friction", "physical-depletion"],
    readTime: "2 min",
    body: [
      "When everything is chaos, you don't need 10 new habits. You need one. One anchor point that happens every day regardless of how bad things get. One thing that your body does on autopilot even when your brain is offline. That's your anchor habit.",
      "An anchor habit is the single behavior that, if maintained, keeps the floor from dropping out entirely. For some people it's: making the bed (signals 'the day has structure'). For others: the evening reset (tomorrow is prepared). For others: the morning coffee ritual (a moment of calm before chaos). It's different for everyone.",
      "The key properties of a good anchor habit: (1) It's small enough to do on your worst day. (2) It's tied to a physical cue (not a time — times shift). (3) It creates a sense of 'I did something' even when everything else falls apart. (4) It's forgiving — missing one day doesn't break it.",
      "When life collapses — illness, crisis, schedule upheaval — everything else can fall away. But if your anchor habit holds, you have a foundation to rebuild from. It's the one thread that doesn't break. Everything else can be reconstructed around it.",
    ],
    tryThis: "Identify your anchor habit — or choose one. What's the ONE thing that, if you did it every day, would make you feel like you're not completely falling apart? Make it tiny. Make it physical. Do it tomorrow. Then the next day. That's your floor.",
    remember: "You don't need 10 habits. You need one anchor — one thing that holds even on your worst day. Build everything else around it. When life collapses, this is what you protect.",
  },
  {
    id: "rel-partner-adhd-too",
    title: "When Your Partner Has ADHD Too",
    subtitle: "Neither of you is the 'organized one.' Now what?",
    category: "relationships",
    archetypes: ["invisible-architect", "storm-weatherer", "plate-spinner"],
    dimensions: ["system-friction", "cognitive-load"],
    readTime: "2 min",
    body: [
      "Two ADHD brains in one household means: double the forgotten appointments, double the unfinished projects, double the emotional intensity — and no one playing the 'neurotypical anchor' role that many ADHD adults unconsciously rely on their partner to fill.",
      "The unique challenges: neither person naturally notices what needs doing (both have impaired 'noticing'). Both struggle with task initiation, so things pile up with no one starting. Both have emotional dysregulation, so conflicts escalate faster. And the mental load often still falls on one person — usually the one who was socialized female — regardless of both having ADHD.",
      "The advantage: genuine understanding. Your partner GETS why you forgot. They know the shame of losing things, the frustration of time blindness, the exhaustion of masking. That empathy is real and valuable — if you can harness it instead of letting both brains spiral together.",
      "What works: externalize EVERYTHING (shared calendar, visible lists, automated reminders — neither brain can hold it internally). Divide by strength, not by 'fairness' (if one of you is better at initiating and the other at maintaining, use that). Schedule a weekly 'admin meeting' where you both look at what's coming — because neither will notice it spontaneously.",
    ],
    tryThis: "If both you and your partner have ADHD: set up one shared system this week — a whiteboard, a shared app, a weekly 10-minute 'what's coming up' conversation. Neither of you can hold it in your head. Put it somewhere BOTH of you can see it.",
    remember: "Two ADHD brains means no one is the 'default rememberer.' You need external systems that neither brain has to hold. The advantage: genuine empathy. The challenge: no autopilot. Build systems together.",
  },
  {
    id: "par-different-than-parented",
    title: "Parenting Differently Than You Were Parented",
    subtitle: "You know how you DON'T want to parent. But what do you do instead?",
    category: "parenting",
    archetypes: ["quiet-volcano", "the-disappeared", "weight-bearer"],
    dimensions: ["emotional-bandwidth", "identity-erosion"],
    readTime: "2 min",
    body: [
      "You know how you DON'T want to parent — because you lived it. You won't hit. You won't use shame. You won't withdraw love as punishment. You won't dismiss their feelings. But knowing what you don't want to do doesn't tell you what TO do. And in the heat of the moment, when you have no script, the old patterns are the only ones your nervous system knows.",
      "Breaking intergenerational patterns is one of the hardest things a human can do. You're essentially trying to override neural pathways that were laid down in childhood — pathways that fire automatically under stress. Your parents' voice comes out of your mouth not because you chose it, but because it's the deepest groove in your brain.",
      "The work happens in three layers: (1) Awareness — catching the old pattern as it fires ('I'm about to do the thing my mother did'). (2) Pause — creating a gap between the trigger and the response, even if it's just 3 seconds. (3) Choice — doing something different, even imperfectly. Even if the 'different' thing is just walking away instead of repeating the pattern.",
      "You will not do this perfectly. You will catch yourself mid-pattern sometimes. You will repeat things you swore you'd never say. And then you'll repair. And the repair — the going back and saying 'that wasn't okay, I'm sorry, I'm working on it' — IS the cycle breaking. Not the prevention of all repetition. The repair after it.",
    ],
    tryThis: "Identify one specific pattern from your childhood you're trying not to repeat. Write down: 'When [trigger] happens, my automatic response is [old pattern]. What I want to do instead is [new response].' Having it written gives you a script for the moment your nervous system goes on autopilot.",
    remember: "You won't break the cycle perfectly. You'll catch it, miss it, catch it again. The cycle breaks not in the prevention of all repetition — but in the repair afterward. Every repair is a new line of code overwriting the old.",
    groundingNote: "If working on intergenerational patterns brings up grief, anger, or painful memories about your own childhood, that's expected. A therapist who specializes in intergenerational trauma can support this work in ways self-reflection alone cannot.",
  },
]