// ============================================================
// Micro-Guides — Batch 2 (guides 21-50)
// ============================================================

import type { MicroGuide } from "./types"

export const MICRO_GUIDES_BATCH2: MicroGuide[] = [
  // ---- EXECUTIVE FUNCTION (4 more) ----
  {
    id: "ef-object-permanence",
    title: "Out of Sight, Out of Mind — Literally",
    subtitle: "Object permanence and the ADHD brain",
    category: "executive-function",
    archetypes: ["plate-spinner", "storm-weatherer", "invisible-architect"],
    dimensions: ["cognitive-load", "system-friction"],
    readTime: "2 min",
    body: [
      "The bill you forgot to pay wasn't laziness. The friend you haven't texted back in three weeks isn't because you don't care. The food rotting in the back of the fridge isn't neglect. It's object permanence — or rather, the lack of it.",
      "In ADHD brains, the working memory system that keeps non-visible things 'alive' in your awareness is impaired. When something leaves your visual field, it can literally cease to exist in your mind. Not metaphorically. Neurologically.",
      "This is why you buy duplicates of things you already own. Why you forget about people you love when you don't see them regularly. Why the laundry in the dryer stays there for three days. The item didn't leave your life — it left your awareness.",
      "The fix is environmental, not motivational. Make important things visible. Bills on the counter, not in a drawer. Reminders on your phone, not in your head. Friends in a recurring calendar event, not left to spontaneous memory. If your brain can't hold it invisibly, make it visible.",
    ],
    tryThis: "Walk through your house and identify 3 things that are 'out of sight, out of mind' right now. Move them somewhere visible. A bill on the fridge. A return by the front door. A text reminder for the friend you keep meaning to call.",
    remember: "You don't forget because you don't care. You forget because your brain drops what it can't see. Make the invisible visible.",
  },
  {
    id: "ef-hyperfocus-trap",
    title: "Hyperfocus Isn't a Superpower (Usually)",
    subtitle: "When intense focus works against you",
    category: "executive-function",
    archetypes: ["plate-spinner", "the-disappeared", "invisible-architect"],
    dimensions: ["cognitive-load", "identity-erosion"],
    readTime: "2 min",
    body: [
      "You sat down to 'quickly check' something and three hours disappeared. The kids were on screens the whole time. Dinner didn't happen. You feel guilty and confused — how can you have ADHD if you can focus THAT intensely?",
      "Hyperfocus isn't actually focus. It's the inability to disengage. Your brain's attention regulation system is impaired in both directions — it can't start things (task initiation) AND it can't stop things (task disengagement). Hyperfocus is the flip side of distractibility, not the opposite of it.",
      "The trigger is usually dopamine. When something is novel, interesting, or urgent, your brain floods with dopamine and locks on. It's not choosing to focus — it's being captured. And while you're captured, everything else disappears: time, hunger, children, responsibilities.",
      "This is why hyperfocus often lands on the 'wrong' things — reorganizing a closet instead of paying bills, researching a hobby instead of making dinner. Your brain doesn't prioritize by importance. It prioritizes by dopamine.",
    ],
    tryThis: "Set a timer before you start anything that might capture you. Not to limit the activity — but to create an external interruption that your brain can't provide internally. A 30-minute alarm that says 'check on the world.'",
    remember: "Hyperfocus isn't a choice or a superpower. It's your brain being captured by dopamine. Use timers as external interrupts for what your brain can't do internally.",
  },
  {
    id: "ef-transition-difficulty",
    title: "Why Transitions Feel Like Dying",
    subtitle: "The neurology of switching tasks",
    category: "executive-function",
    archetypes: ["plate-spinner", "storm-weatherer", "burning-engine"],
    dimensions: ["cognitive-load", "emotional-bandwidth"],
    readTime: "2 min",
    body: [
      "Getting out the door. Stopping one activity to start another. Shifting from work-brain to mom-brain. Every transition feels like dragging yourself through wet concrete. It's not resistance — it's neurology.",
      "Task switching requires your prefrontal cortex to: close the current mental 'file,' clear working memory, load the new context, and initiate the new behavior. For ADHD brains, each of these steps is impaired. The old task doesn't close cleanly. The new one doesn't load smoothly. You're stuck in between — half in one world, half in another.",
      "This is why your kids saying 'Mom!' when you're in the middle of something feels physically painful. It's not that you don't want to respond. It's that the transition cost is enormous — and they're asking you to pay it instantly, without warning.",
      "Children, by nature, demand constant transitions. Breakfast to getting dressed. Playing to leaving. Bath to bed. Each one costs you cognitive resources that are already scarce. By the end of the day, you've paid the transition tax dozens of times. No wonder you're depleted.",
    ],
    tryThis: "Give yourself (and your kids) transition warnings. '5 minutes until we switch.' This isn't just for them — it's for YOUR brain to begin the shutdown process on the current task. Your brain needs lead time that neurotypical brains don't.",
    remember: "Transitions aren't simple for your brain. Each one costs real cognitive resources. Build in warnings and buffer time — for yourself, not just your kids.",
  },
  {
    id: "ef-working-memory",
    title: "Your Brain Has 3 Tabs, Not 30",
    subtitle: "Working memory limits and what to do about them",
    category: "executive-function",
    archetypes: ["plate-spinner", "invisible-architect", "weight-bearer"],
    dimensions: ["cognitive-load"],
    readTime: "2 min",
    body: [
      "Working memory is the brain's scratchpad — the space where you hold information you're actively using. Most people can hold 4-7 items. ADHD brains? Often 2-3. And motherhood asks you to hold 40.",
      "This is why you walk into a room and forget why. Why you start a sentence and lose the thought. Why you can't hold a grocery list and a phone conversation simultaneously. Your scratchpad is full. Every new input pushes something else off.",
      "It's also why you feel like you're 'going crazy' or worry about early dementia. You're not. Your working memory is functioning at its actual capacity — it's just that its actual capacity is smaller than what your life demands. The gap between demand and capacity is what creates the feeling of cognitive failure.",
      "The solution isn't to expand your working memory (you can't, really). It's to reduce what you ask it to hold. Write everything down. Use lists, alarms, sticky notes, phone reminders. These aren't crutches — they're prosthetics for a real limitation. You wouldn't ask someone with a broken leg to 'just walk harder.'",
    ],
    tryThis: "For one day, write down EVERYTHING instead of trying to remember it. Every thought, every task, every thing someone asks you to do. Notice how much lighter your brain feels when it's not trying to hold it all.",
    remember: "Your working memory has 3 tabs. Your life has 30 open. The fix isn't a better brain — it's getting things OUT of your brain and into external systems.",
  },

  // ---- EMOTIONAL REGULATION (4 more) ----
  {
    id: "er-rejection-sensitivity",
    title: "Why That Comment Destroyed Your Whole Day",
    subtitle: "Rejection Sensitive Dysphoria and the ADHD brain",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "the-disappeared", "burning-engine"],
    dimensions: ["emotional-bandwidth", "identity-erosion"],
    readTime: "3 min",
    body: [
      "Someone made an offhand comment — maybe your partner, maybe another mom at pickup, maybe your own mother. It wasn't even that bad. But it landed like a punch to the chest and you've been replaying it for hours. You can't let it go. You feel humiliated, furious, or devastated — and the intensity of your reaction scares you.",
      "This is Rejection Sensitive Dysphoria (RSD) — an emotional response pattern found in an estimated 99% of people with ADHD. It's not 'being too sensitive.' It's a neurological difference in how your brain processes perceived rejection, criticism, or failure. The emotional pain is real, immediate, and disproportionate to the trigger.",
      "Neurologically, RSD involves the anterior cingulate cortex and the emotional processing centers responding to social threat signals with the same intensity as physical pain. Brain imaging studies show that social rejection activates the same neural pathways as being physically struck. You're not overreacting — your brain is literally experiencing pain.",
      "RSD is why you might avoid trying new things (fear of failure), people-please compulsively (fear of disapproval), or interpret neutral comments as criticism. It's why one negative piece of feedback can erase a hundred positive ones. Your brain has a negativity bias on steroids.",
      "The most important thing to know: the intensity of the feeling is real, but the story your brain tells about it is often distorted. 'She hates me' might actually be 'she was distracted.' 'I'm a failure' might actually be 'I made one mistake.' The feeling is valid. The interpretation needs questioning.",
    ],
    tryThis: "Next time a comment hits you disproportionately hard, write down: (1) What was actually said. (2) What my brain is telling me it means. (3) What are 2 other possible interpretations? The gap between #2 and #3 is where RSD lives.",
    remember: "The pain is real — your brain processes rejection like physical injury. But the story it tells you about what the rejection means is often wrong. Feel the feeling. Question the narrative.",
  },
  {
    id: "er-emotional-hangover",
    title: "The Emotional Hangover Is Real",
    subtitle: "Why you're still wrecked the day after a hard moment",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "burning-engine", "running-on-empty"],
    dimensions: ["emotional-bandwidth", "physical-depletion"],
    readTime: "2 min",
    body: [
      "The meltdown was yesterday. The argument was last night. But today you feel like you've been hit by a truck — foggy, exhausted, fragile, unable to function at your normal level. Everyone else seems to have moved on. You haven't.",
      "This is an emotional hangover — and it's a documented neurological phenomenon. Intense emotional experiences trigger a cascade of stress hormones (cortisol, adrenaline, norepinephrine) that take 24-72 hours to fully clear from your system. Your body is literally still processing the chemical aftermath of yesterday's emotional event.",
      "For ADHD brains, this recovery period is longer because: (1) the initial emotional response was more intense (emotional dysregulation), (2) the rumination continues feeding the stress response (you can't stop replaying it), and (3) your baseline recovery resources are already depleted.",
      "This is why you can't 'just move on.' Your nervous system hasn't finished processing. Pushing through an emotional hangover is like running on a sprained ankle — you can do it, but you're causing more damage and extending the recovery time.",
    ],
    tryThis: "After an intense emotional event, treat the next day like a recovery day. Lower your expectations by 50%. Cancel what you can. Rest more. This isn't indulgence — it's giving your nervous system the time it physiologically needs to clear the stress chemicals.",
    remember: "Emotional hangovers are biochemical, not weakness. Your body needs 24-72 hours to clear stress hormones. Plan for recovery, not performance, the day after something hard.",
  },
  {
    id: "er-anger-as-information",
    title: "Your Anger Is Trying to Tell You Something",
    subtitle: "Anger as a secondary emotion",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "the-disappeared", "invisible-architect"],
    dimensions: ["emotional-bandwidth", "identity-erosion"],
    readTime: "2 min",
    body: [
      "You're angry. At your partner, at your kids, at the mess, at your life. The anger feels ugly and wrong — good mothers aren't angry. So you push it down, or it explodes, and either way you feel ashamed.",
      "Here's what clinical psychology knows about anger: it's almost always a secondary emotion. Underneath anger, there's always something more vulnerable — hurt, fear, grief, exhaustion, or unmet need. Anger is the bodyguard that shows up so you don't have to feel the more painful thing underneath.",
      "When you're angry at your partner for not helping: underneath is probably hurt (I don't feel valued), fear (I can't sustain this alone), or grief (this isn't the partnership I imagined). When you're angry at your kids: underneath is usually overwhelm (I have nothing left) or grief (I'm not the parent I want to be).",
      "Anger isn't the problem to solve. It's the alarm telling you where the problem is. When you can ask 'what's underneath this anger?' you get to the actual need — which is addressable. The anger itself is just the smoke. The fire is below.",
    ],
    tryThis: "Next time you feel anger rising, pause and ask: 'What am I actually feeling underneath this? Am I hurt? Scared? Exhausted? Grieving? Feeling unseen?' Name the underneath feeling. That's the one that needs attention.",
    remember: "Anger is the bodyguard emotion. It protects you from feeling something more vulnerable underneath. Ask what's below it — that's where the real need lives.",
  },
  {
    id: "er-nervous-system-states",
    title: "You're Not Choosing to Shut Down",
    subtitle: "Understanding freeze, fight, flight, and fawn",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "burning-engine", "weight-bearer", "storm-weatherer"],
    dimensions: ["emotional-bandwidth", "physical-depletion"],
    readTime: "3 min",
    body: [
      "Sometimes you explode (fight). Sometimes you flee to the bathroom (flight). Sometimes you go completely blank and can't move or speak (freeze). Sometimes you over-apologize and people-please your way through (fawn). None of these are choices. They're autonomic nervous system responses.",
      "Your autonomic nervous system operates below conscious control. When it detects threat — and 'threat' includes sensory overload, emotional overwhelm, conflict, or simply too much demand — it activates a survival response. You don't choose which one. Your nervous system chooses based on what worked in your past.",
      "Fight shows up as rage, snapping, yelling, slamming things. Flight shows up as escaping — scrolling your phone, hiding in the bathroom, mentally checking out. Freeze shows up as blankness, inability to respond, going mute, dissociation. Fawn shows up as over-accommodating, saying yes when you mean no, prioritizing others' comfort over your own safety.",
      "The critical insight: these responses were adaptive at some point. They kept you safe — probably in childhood. They're still running because your nervous system hasn't updated its threat assessment. It's using old software for new situations. Your child's tantrum isn't actually dangerous — but your nervous system responds as if it is.",
      "You can't willpower your way out of a survival response. But you can learn to recognize which state you're in, and use specific tools to shift back to regulation. The first step is always: name it. 'I'm in freeze right now.' Naming activates the prefrontal cortex, which begins to bring the survival response back under conscious influence.",
    ],
    tryThis: "Learn your default survival response. Which one do you go to most often under stress — fight, flight, freeze, or fawn? Once you know your pattern, you can catch it earlier: 'I'm starting to fawn right now. That means I'm feeling threatened. What do I actually need?'",
    remember: "Fight, flight, freeze, and fawn aren't choices — they're your nervous system's automatic survival responses. You can't willpower past them. But you can name them, which begins to shift them.",
  },

  // ---- PHYSICAL / NERVOUS SYSTEM (3 more) ----
  {
    id: "pns-sleep-architecture",
    title: "Why 8 Hours Still Leaves You Exhausted",
    subtitle: "Sleep quality vs. sleep quantity",
    category: "physical-nervous-system",
    archetypes: ["running-on-empty", "burning-engine", "weight-bearer"],
    dimensions: ["physical-depletion"],
    readTime: "2 min",
    body: [
      "You slept 8 hours. You're still exhausted. People say 'but you got enough sleep!' and you want to scream. Because the hours aren't the problem. The architecture is.",
      "Sleep has stages: light sleep, deep sleep (slow-wave), and REM. Deep sleep is where physical restoration happens — tissue repair, immune function, growth hormone release. REM is where emotional processing and memory consolidation happen. If you're not getting enough of either, 8 hours means nothing.",
      "What disrupts sleep architecture in mothers: hypervigilance (your brain stays in light sleep, listening for children), cortisol dysregulation (stress hormones prevent deep sleep entry), blue light before bed (suppresses melatonin), alcohol (fragments REM), and racing thoughts (prevents sleep onset, reducing total deep sleep time).",
      "The result: you can lie in bed for 8 hours and get 2 hours of restorative sleep. Your body is horizontal but your brain never fully powers down. You wake up feeling like you didn't sleep because, neurologically, you barely did.",
    ],
    tryThis: "For one week, try this: no screens 30 minutes before bed (or use night mode), keep the room cold (65-68°F is optimal for deep sleep), and do a 2-minute brain dump on paper before lying down. These target the three biggest disruptors of sleep architecture.",
    remember: "Hours in bed ≠ restorative sleep. If you're sleeping 'enough' and still exhausted, the quality is the problem — not the quantity. Target deep sleep, not just duration.",
  },
  {
    id: "pns-interoception",
    title: "You Might Not Know You're Hungry, Thirsty, or Tired",
    subtitle: "Interoception and the disconnected body",
    category: "physical-nervous-system",
    archetypes: ["running-on-empty", "plate-spinner", "the-disappeared"],
    dimensions: ["physical-depletion", "cognitive-load"],
    readTime: "2 min",
    body: [
      "It's 3pm and you realize you haven't eaten. Or you suddenly notice you desperately need to pee — and have for hours. Or you're shaking and irritable and only then realize you're hungry. This isn't just being busy. It's impaired interoception.",
      "Interoception is your brain's ability to sense internal body signals — hunger, thirst, temperature, bladder fullness, fatigue, pain. In ADHD brains, this signal processing is often delayed or muted. You don't feel hungry until you're starving. You don't feel tired until you're collapsing. The signals are there — your brain just doesn't prioritize them.",
      "This is compounded by motherhood, which trains you to ignore your own body signals in favor of everyone else's needs. Over years, the ignoring becomes automatic. You genuinely lose the ability to notice what your body is telling you until it's screaming.",
      "The downstream effects are significant: you're making decisions on an empty stomach (impaired glucose = impaired executive function), you're dehydrated (cognitive impairment), you're holding tension you don't notice (chronic pain), and you're exhausted without registering it (until you crash).",
    ],
    tryThis: "Set 3 alarms today: 10am, 1pm, 4pm. When they go off, stop and scan: Am I hungry? Thirsty? Do I need the bathroom? Am I tense anywhere? Don't wait for your body to tell you — ask it directly on a schedule.",
    remember: "You might not feel hungry, thirsty, or tired until it's an emergency. That's impaired interoception, not toughness. Use scheduled check-ins instead of waiting for signals that may never come.",
  },
  {
    id: "pns-adrenaline-functioning",
    title: "You're Running on Adrenaline, Not Energy",
    subtitle: "The difference between activation and vitality",
    category: "physical-nervous-system",
    archetypes: ["burning-engine", "running-on-empty", "weight-bearer"],
    dimensions: ["physical-depletion", "emotional-bandwidth"],
    readTime: "2 min",
    body: [
      "You're getting things done. You're functioning. People look at you and see a capable person. But inside, you know the truth: you're not running on energy. You're running on adrenaline and cortisol — your body's emergency fuel system.",
      "There's a critical difference between genuine energy (fueled by rest, nutrition, and sustainable rhythms) and stress activation (fueled by urgency, anxiety, and the fight-or-flight system). They look the same from the outside. They feel completely different from the inside — and they have very different long-term costs.",
      "Adrenaline functioning feels like: wired but tired, productive but anxious, getting things done but unable to stop, collapsing the moment you sit down, needing urgency or deadline pressure to function, feeling like you'll fall apart if you slow down.",
      "The cost: your body is burning emergency reserves meant for actual emergencies. Chronic adrenaline functioning leads to adrenal fatigue, immune suppression, hormonal disruption, and eventually — complete collapse. The crash isn't a surprise. It's the inevitable endpoint of running on emergency fuel.",
    ],
    tryThis: "Ask yourself honestly: 'Am I functioning because I have energy, or because I'm afraid of what happens if I stop?' If it's the second one, your body is in emergency mode. The most radical thing you can do is stop — even for 10 minutes — and prove to your nervous system that stopping is safe.",
    remember: "Productivity powered by adrenaline isn't health — it's a slow-motion emergency. If you can only function under pressure, your body is running on fumes, not fuel.",
  },

  // ---- HORMONAL (3 more) ----
  {
    id: "horm-perimenopause-adhd",
    title: "Perimenopause Can Unmask ADHD",
    subtitle: "When your coping strategies suddenly stop working",
    category: "hormonal",
    archetypes: ["plate-spinner", "running-on-empty", "burning-engine"],
    dimensions: ["cognitive-load", "physical-depletion", "emotional-bandwidth"],
    readTime: "3 min",
    body: [
      "You managed fine for years. Maybe not perfectly, but you had systems, workarounds, compensatory strategies that kept life running. Then, somewhere in your late 30s or 40s, everything fell apart. The strategies stopped working. The brain fog descended. The emotional reactivity intensified. You thought you were losing your mind.",
      "You might be in perimenopause — and if you have ADHD (diagnosed or not), this transition can be devastating. Here's why: estrogen has been quietly supporting your dopamine system your entire adult life. As estrogen fluctuates and declines in perimenopause, dopamine support drops with it. The compensatory strategies that worked when you had adequate dopamine suddenly fail without it.",
      "This is why many women are first diagnosed with ADHD in their 40s. It's not that the ADHD is new — it's that the hormonal support that was masking it has withdrawn. The scaffolding fell away and the underlying architecture was revealed.",
      "Symptoms that intensify in perimenopause: brain fog, word-finding difficulty, inability to focus, emotional volatility, rage, insomnia, fatigue, and the feeling that you're 'going crazy.' These overlap with both ADHD and perimenopause — which is why so many women are dismissed with 'it's just your age' instead of getting proper support.",
    ],
    tryThis: "If you're 35+ and your cognitive function has noticeably declined, consider discussing both perimenopause AND ADHD with your healthcare provider. They're not mutually exclusive — and addressing both changes the treatment approach significantly.",
    remember: "If your coping strategies suddenly stopped working in your late 30s-40s, it might not be 'just stress.' Declining estrogen unmasks ADHD that was previously compensated. You're not losing your mind — your hormonal scaffolding is shifting.",
  },
  {
    id: "horm-premenstrual-adhd",
    title: "The Week Before Your Period Is Not Your Fault",
    subtitle: "Why ADHD symptoms spike premenstrually",
    category: "hormonal",
    archetypes: ["quiet-volcano", "plate-spinner", "burning-engine"],
    dimensions: ["emotional-bandwidth", "cognitive-load", "physical-depletion"],
    readTime: "2 min",
    body: [
      "The week before your period, you become a different person. More reactive. More scattered. More overwhelmed. More likely to yell, cry, or shut down. You blame yourself — 'Why can't I hold it together?' — but this isn't a willpower failure. It's a predictable neurochemical event.",
      "In the luteal phase (roughly days 21-28), both estrogen and progesterone drop sharply. Since estrogen supports dopamine function, this drop creates a temporary but significant worsening of all ADHD symptoms: attention, emotional regulation, impulse control, working memory, and energy.",
      "Research shows that women with ADHD report a 30-50% worsening of symptoms premenstrually. This isn't subjective — it's measurable in cognitive testing. Your brain is literally functioning with less dopamine support during this window.",
      "The implication: you need a different plan for this week. Not the same expectations with more willpower — genuinely different expectations. Less on your plate. More support. Lower standards. Earlier bedtime. This isn't giving up. It's planning around a known neurochemical reality.",
    ],
    tryThis: "Track your cycle for 2 months alongside your worst ADHD days. If they cluster in the week before your period, you have your answer. Then: build a 'luteal phase protocol' — reduced commitments, easier meals, more rest, and explicit permission to function at 60%.",
    remember: "The premenstrual week isn't a character failure. It's a dopamine dip. Plan for it like you'd plan for any known challenge — with reduced expectations and increased support.",
  },
  {
    id: "horm-breastfeeding-brain",
    title: "Breastfeeding Brain Is Neurologically Real",
    subtitle: "Why nursing affects cognition and mood",
    category: "hormonal",
    archetypes: ["running-on-empty", "burning-engine", "plate-spinner"],
    dimensions: ["physical-depletion", "cognitive-load"],
    readTime: "2 min",
    body: [
      "You're breastfeeding and you can't think straight. You forget words mid-sentence. You feel foggy, emotional, and drained in a way that goes beyond sleep deprivation. People say 'mom brain' like it's cute. It's not cute. It's real, and it has a mechanism.",
      "Breastfeeding suppresses estrogen (to prevent ovulation). Low estrogen means low dopamine support. For women with ADHD, this creates a prolonged period of significantly impaired executive function — on top of sleep deprivation, on top of the demands of a newborn.",
      "Additionally, prolactin (the milk-production hormone) has sedating effects, and oxytocin (released during letdown) can cause mood dips in some women (called D-MER — Dysphoric Milk Ejection Reflex). The hormonal cocktail of breastfeeding is actively working against cognitive clarity.",
      "This doesn't mean you should stop breastfeeding (that's your choice entirely). It means you should know that the cognitive impairment is physiological, not personal. You're not 'losing it.' Your brain is operating under significant hormonal constraint. Adjust expectations accordingly.",
    ],
    tryThis: "If you're breastfeeding and struggling cognitively: externalize everything (write it ALL down), accept help without guilt, and know that this is temporary. Your brain will come back online as hormones normalize. In the meantime, lower the bar and protect your energy.",
    remember: "Breastfeeding suppresses the hormones that support your executive function. The fog is biochemical, not personal. It's temporary — but while it lasts, you need more support, not more effort.",
  },

  // ---- RELATIONSHIPS (3 more) ----
  {
    id: "rel-weaponized-incompetence",
    title: "When 'I Don't Know How' Really Means 'I Don't Want To'",
    subtitle: "Recognizing weaponized incompetence",
    category: "relationships",
    archetypes: ["invisible-architect", "the-disappeared", "quiet-volcano"],
    dimensions: ["system-friction", "identity-erosion", "emotional-bandwidth"],
    readTime: "3 min",
    body: [
      "He loads the dishwasher 'wrong.' He 'doesn't know' which clothes the kids need for school. He 'can't find' the thing that's in the same place it's been for three years. So you do it yourself. Again. Because it's faster. Because it's easier. Because at least it gets done right.",
      "This pattern has a name: weaponized incompetence. It's when someone performs a task so poorly — or claims such helplessness — that you stop asking them to do it. The result: you carry the full load, they carry none, and the arrangement appears 'natural' rather than chosen.",
      "Important nuance: sometimes it IS genuine incompetence. If your partner has ADHD too, or genuinely was never taught domestic skills, the inability might be real. The difference is in the response to feedback. Genuine incompetence says 'show me how, I want to learn.' Weaponized incompetence says 'you're better at it anyway' or does it badly enough that you take it back.",
      "The cost to you is enormous: every task you take back is another item on your cognitive load. Every 'it's easier if I just do it' is another brick in the wall of resentment. And the longer the pattern runs, the more 'natural' it appears — to both of you.",
      "Breaking this pattern requires tolerating imperfection. His way of loading the dishwasher doesn't have to match yours. The kids can survive mismatched socks. The standard you're protecting might be costing you more than it's worth.",
    ],
    tryThis: "Identify one task you've taken back because your partner 'can't do it right.' Give it back. Fully. Say: 'This is yours. I won't redo it. I won't supervise it. I need to not think about it.' Then — the hard part — let it be imperfect.",
    remember: "If you're doing everything because 'it's easier,' ask: easier for whom? The short-term ease of doing it yourself is building long-term resentment and unsustainable load.",
  },
  {
    id: "rel-comparison-trap",
    title: "The Other Moms Are Struggling Too",
    subtitle: "Why comparison is a rigged game",
    category: "relationships",
    archetypes: ["the-disappeared", "quiet-volcano", "weight-bearer"],
    dimensions: ["identity-erosion", "emotional-bandwidth"],
    readTime: "2 min",
    body: [
      "She's at pickup with her hair done, her kids in matching outfits, a homemade snack in hand. You're in yesterday's clothes with a screaming toddler and goldfish crackers from the car floor. The comparison is instant and devastating: she's managing. You're not.",
      "Except you're comparing your inside to her outside. You see her curated 15 minutes. You don't see her 3am anxiety, her marriage strain, her crying in the car before she walked in, her own mother's voice in her head telling her she's not enough. Everyone is performing 'fine' in public. You're just the only one who knows your own backstage.",
      "Comparison is particularly toxic for ADHD brains because of rejection sensitive dysphoria — you don't just notice the gap, you feel it as physical pain. And because of the negativity bias — you dismiss your own successes and magnify your failures while doing the opposite for others.",
      "The truth: there is no mother alive who is handling everything well. There are only mothers who are better at hiding what's falling apart. The performance of competence is not competence. And your struggle is not evidence of your inadequacy — it's evidence of your honesty.",
    ],
    tryThis: "Next time comparison hits: name one thing you're seeing (her outside) and one thing you're not seeing (her inside). Then name one thing you're doing well that she can't see either. The game is rigged because you only have half the data.",
    remember: "You're comparing your worst moments to her best performance. That's not a fair comparison — it's a cognitive distortion. Everyone is struggling. You're just honest about it.",
  },
  {
    id: "rel-boundaries-not-walls",
    title: "Boundaries Are Not Punishment",
    subtitle: "The difference between protecting yourself and pushing people away",
    category: "relationships",
    archetypes: ["quiet-volcano", "the-disappeared", "invisible-architect"],
    dimensions: ["emotional-bandwidth", "identity-erosion"],
    readTime: "2 min",
    body: [
      "You finally set a boundary — said no to something, asked for space, declined an invitation — and now you feel guilty. Or the other person is upset. And you're wondering if you were wrong. If you were selfish. If boundaries are just a fancy word for being difficult.",
      "A boundary is not a wall. A wall says 'stay away from me.' A boundary says 'here's how to be close to me safely.' Walls are built from fear and isolation. Boundaries are built from self-knowledge and sustainability. They protect the relationship by preventing resentment from building.",
      "The guilt you feel after setting a boundary is almost always the echo of old conditioning: 'good girls don't say no,' 'mothers sacrifice everything,' 'your needs come last.' That guilt is not evidence that you did something wrong. It's evidence that you did something new.",
      "People who are upset by your boundaries were benefiting from your lack of them. That's not a reason to remove the boundary. It's confirmation that the boundary was needed.",
    ],
    tryThis: "Reframe your last boundary as a gift to the relationship: 'By saying no to X, I'm preventing the resentment that would have built if I said yes. I'm protecting my ability to show up genuinely, not performatively.' Boundaries serve connection — they don't destroy it.",
    remember: "Boundaries aren't selfish. They're what makes sustainable relationships possible. The guilt is old conditioning, not evidence of wrongdoing.",
  },

  // ---- IDENTITY (3 more) ----
  {
    id: "id-good-mom-myth",
    title: "The 'Good Mom' Doesn't Exist",
    subtitle: "Deconstructing an impossible standard",
    category: "identity",
    archetypes: ["the-disappeared", "quiet-volcano", "weight-bearer"],
    dimensions: ["identity-erosion", "emotional-bandwidth"],
    readTime: "2 min",
    body: [
      "The 'good mom' is patient. She's present. She makes homemade meals and does crafts and never yells and always has energy for one more story at bedtime. She doesn't resent her children. She doesn't miss her old life. She doesn't scroll her phone while they play. She is, in every way, a fiction.",
      "The 'good mom' standard is not a real person. It's a composite — assembled from Instagram highlights, parenting books written by people with nannies, your own mother's selective memory, and a culture that benefits from women's unpaid, uncomplaining labor.",
      "No one meets this standard. Not the mom at pickup who looks put-together. Not the influencer with the aesthetic playroom. Not your own mother (ask her honestly about her worst moments — she has them). The standard exists not to be met, but to keep you striving, spending, and silent about your struggle.",
      "The real question isn't 'am I a good mom?' It's 'good by whose definition?' If the definition requires you to be depleted, invisible, and self-sacrificing — the definition is the problem, not you.",
    ],
    tryThis: "Write down your definition of 'good mom.' Then ask: 'Where did each item on this list come from? My values? Or someone else's expectations?' Cross off everything that came from outside. What's left is YOUR standard — and it's probably already being met.",
    remember: "The 'good mom' is a cultural fiction designed to keep you striving. You don't have to meet a standard that no real person has ever met. Define your own.",
  },
  {
    id: "id-desire-as-data",
    title: "Wanting Things Isn't Selfish",
    subtitle: "Desire as evidence of selfhood",
    category: "identity",
    archetypes: ["the-disappeared", "invisible-architect", "running-on-empty"],
    dimensions: ["identity-erosion"],
    readTime: "2 min",
    body: [
      "When was the last time someone asked what you want — and you could answer? Not what your kids need. Not what would make your partner happy. Not what the house requires. What YOU want. If you drew a blank, that's not because you're selfless. It's because your desire has been systematically suppressed.",
      "Desire is the first sign of self. It's how you know you're still a person underneath the role. 'I want to read that book.' 'I want to go to that place.' 'I want 20 minutes alone.' Each want is a data point about who you are — separate from who you serve.",
      "Motherhood trains desire out of you through a simple mechanism: every time you want something, guilt arrives. 'I should want to be with my kids.' 'I shouldn't need time alone.' 'Good mothers don't want to escape.' Over years, you stop wanting — because wanting hurts too much when you can't have.",
      "But suppressed desire doesn't disappear. It converts to resentment, numbness, or depression. The woman who 'doesn't need anything' isn't enlightened — she's disconnected from herself. Reconnecting with desire — even small, silly, impractical desire — is how identity rebuilds.",
    ],
    tryThis: "Complete this sentence 5 times without filtering: 'I want ___.' Don't judge the answers. Don't assess feasibility. Just notice what comes up. Those wants are you — still alive under the role.",
    remember: "Wanting things isn't selfish. It's evidence that you still exist as a person. Every desire you notice is a thread back to yourself. Pull it.",
  },
  {
    id: "id-grief-permission",
    title: "You're Allowed to Grieve a Life You Chose",
    subtitle: "Grief and gratitude can coexist",
    category: "identity",
    archetypes: ["the-disappeared", "quiet-volcano", "running-on-empty"],
    dimensions: ["identity-erosion", "emotional-bandwidth"],
    readTime: "2 min",
    body: [
      "You chose this. You wanted children. Maybe you fought for them. And now you're grieving — the freedom, the spontaneity, the body, the career, the relationship, the person you were. And the guilt of grieving something you chose is its own special torture.",
      "Here's what psychology knows: grief and gratitude are not opposites. They coexist. You can love your children with your whole heart AND grieve what motherhood cost you. You can be grateful for your life AND mourn the life you didn't get to live. Both are true. Simultaneously. Without contradiction.",
      "The cultural message that says 'you chose this, so you can't complain' is a silencing mechanism. It keeps mothers isolated in their grief, unable to name it without being accused of ingratitude. But unnamed grief doesn't resolve — it festers into depression, resentment, or numbness.",
      "You are allowed to grieve. The loss of your former self. The loss of your freedom. The loss of the motherhood you imagined versus the one you got. These are real losses. They deserve acknowledgment — not silence.",
    ],
    tryThis: "Say out loud (or write): 'I love my children AND I grieve ___.' Fill in the blank honestly. Let both things be true at the same time. That's not contradiction — that's the full complexity of being human.",
    remember: "Choosing something doesn't forfeit your right to grieve what it cost. Grief and gratitude coexist. You're allowed to hold both.",
  },

  // ---- SYSTEMS & STRUCTURE (3 more) ----
  {
    id: "sys-environmental-design",
    title: "Design Your Environment, Not Your Willpower",
    subtitle: "Why your house should do the remembering for you",
    category: "systems-structure",
    archetypes: ["plate-spinner", "storm-weatherer", "invisible-architect"],
    dimensions: ["system-friction", "cognitive-load"],
    readTime: "2 min",
    body: [
      "You keep losing your keys. You forget to take your medication. The kids' shoes are never by the door when you need them. You blame yourself — 'Why can't I just remember?' But the question isn't why you can't remember. It's why your environment isn't remembering for you.",
      "Environmental design is the principle that your physical space should make the right behavior easy and the wrong behavior hard. It's more powerful than willpower, more reliable than memory, and more sustainable than any habit app.",
      "Examples: A hook by the door means keys always go in the same place (no searching). Medication next to the coffee maker means you see it every morning (no forgetting). A bin by the entrance means shoes have a home (no hunting). A visual checklist on the wall means the routine is external (no holding it in your head).",
      "For ADHD brains, environmental design isn't a nice-to-have — it's essential. Your working memory can't hold the location of every object. Your executive function can't initiate a search every time you need something. The environment needs to do the cognitive work that your brain can't reliably do.",
    ],
    tryThis: "Identify your top 'friction point' — the thing you lose, forget, or can't find most often. Then ask: 'Where should this LIVE so that I never have to think about it?' Give it a permanent, visible home. That's one less thing your brain has to track.",
    remember: "Don't ask your brain to remember what your environment can hold. Every object with a 'home,' every routine made visible, is cognitive load permanently removed.",
  },
  {
    id: "sys-decision-elimination",
    title: "The Power of Eliminating Choices",
    subtitle: "Why fewer options means better functioning",
    category: "systems-structure",
    archetypes: ["plate-spinner", "invisible-architect", "running-on-empty"],
    dimensions: ["cognitive-load", "system-friction"],
    readTime: "2 min",
    body: [
      "Steve Jobs wore the same outfit every day. Obama limited his suits to two colors. These aren't quirks — they're decision elimination strategies. Every choice you remove from your day is cognitive fuel saved for choices that actually matter.",
      "For ADHD brains, this principle is even more critical. Your decision-making resources are smaller and deplete faster. Every 'what should I wear,' 'what should we eat,' 'which route should I take' costs the same cognitive currency as 'how should I handle this parenting moment.' By afternoon, the currency is spent.",
      "Decision elimination looks like: same breakfast every weekday (no choosing). Capsule wardrobe with pre-matched outfits (no assembling). Meal rotation that repeats weekly (no planning). Same grocery list every week (no browsing). Automated bill payments (no remembering). Same bedtime routine in the same order (no improvising).",
      "This isn't boring. It's strategic. The most creative, successful people in the world eliminate routine decisions so they can spend their cognitive resources on things that actually require thought. You deserve the same strategy.",
    ],
    tryThis: "Pick the decision that drains you most every day (usually meals or clothing). Eliminate it entirely for one week: same breakfast, same lunch formula, or 5 pre-planned outfits. Notice how much lighter your brain feels without that daily choice.",
    remember: "Every decision you eliminate is fuel saved for the decisions that actually matter. Automation isn't laziness — it's intelligence applied to a limited resource.",
  },
  {
    id: "sys-good-enough-systems",
    title: "Your System Doesn't Have to Be Perfect to Work",
    subtitle: "The 70% system that actually runs vs. the 100% system that doesn't",
    category: "systems-structure",
    archetypes: ["plate-spinner", "invisible-architect", "storm-weatherer"],
    dimensions: ["system-friction", "cognitive-load"],
    readTime: "2 min",
    body: [
      "You've tried every planner, every app, every organizational system. They work for a week, then collapse. So you conclude you're 'not an organized person.' But the problem isn't you — it's that you keep choosing systems designed for neurotypical brains operating at 100% consistency.",
      "An ADHD-friendly system has one requirement: it works when you're at 50% capacity. Not when you're motivated and energized — when you're depleted, distracted, and barely functioning. If a system only works on your best days, it's not a system. It's a hobby.",
      "The principles: (1) Fewer steps is always better. A 3-step system beats a 10-step system. (2) Visual beats hidden. A whiteboard on the wall beats a notebook in a drawer. (3) Forgiving beats rigid. A system that works 4/7 days is better than one that requires 7/7. (4) Started beats perfect. A messy list on your phone beats a beautiful planner you never open.",
      "The best system for you is the one you'll actually use when you're at your worst. Not the prettiest one. Not the most comprehensive one. The one with the lowest barrier to entry on your hardest day.",
    ],
    tryThis: "Look at your current organizational system (or lack of one). Ask: 'Would I use this on my worst day? When I'm exhausted, overwhelmed, and can barely think?' If no — simplify it until the answer is yes. That's your real system.",
    remember: "A 70% system you actually use beats a 100% system you abandon. Design for your worst day, not your best.",
  },

  // ---- PARENTING (4 more) ----
  {
    id: "par-screen-guilt",
    title: "Screen Time Guilt Is Not Helping Anyone",
    subtitle: "A realistic framework for screens in overwhelmed households",
    category: "parenting",
    archetypes: ["burning-engine", "running-on-empty", "weight-bearer"],
    dimensions: ["emotional-bandwidth", "physical-depletion"],
    readTime: "2 min",
    body: [
      "Your kids are on screens right now. Maybe they've been on screens for two hours. And the guilt is eating you alive — because every article, every expert, every other mom seems to say that screens are destroying your children's brains.",
      "Here's what the research actually shows: moderate screen time (1-3 hours/day) in the context of an otherwise connected, responsive parent-child relationship shows minimal negative effects. The harm comes from screens REPLACING connection entirely — not from screens existing alongside it.",
      "What matters more than screen time quantity: Are you available for connection when screens are off? Do you have some shared screen experiences (watching together, talking about what they're seeing)? Are basic needs met (sleep, outdoor time, social interaction)? If yes to these — the screens are not the emergency the guilt tells you they are.",
      "A regulated parent who used screens to get 30 minutes of recovery is a better parent than a depleted, resentful parent who white-knuckled through without them. The screens gave you something your children need more than a screen-free afternoon: a mother who can be present when she returns.",
    ],
    tryThis: "Reframe screen time as a tool, not a failure: 'I'm using screens right now so I can regulate, which means I'll be more present and patient when they're done.' That's not an excuse — it's a strategy.",
    remember: "A regulated parent who used screens is better than a depleted parent who didn't. Screens are a tool. Guilt about them costs more than the screens themselves.",
  },
  {
    id: "par-bedtime-battles",
    title: "Bedtime Doesn't Have to Be a War",
    subtitle: "Why bedtime is the hardest hour and what actually helps",
    category: "parenting",
    archetypes: ["burning-engine", "running-on-empty", "storm-weatherer"],
    dimensions: ["physical-depletion", "emotional-bandwidth", "system-friction"],
    readTime: "3 min",
    body: [
      "It's 7pm. You have nothing left. And now you have to navigate the most demanding hour of the day: bedtime. The negotiations, the 'one more story,' the getting out of bed, the sudden thirst, the existential fears that only emerge at 8:47pm. You're running on fumes and they need you at your most patient.",
      "Why bedtime is neurologically the hardest: your cortisol is at its daily low (minimal self-regulation resources), your children's cortisol is also low (they're dysregulated and clingy), the transition from activity to rest is the biggest transition of the day, and there's no 'after' to look forward to — just collapse.",
      "What actually helps isn't more patience (you don't have any). It's more structure. A bedtime routine that is the SAME every single night — same order, same steps, same words — reduces the cognitive load on both of you. The routine does the thinking. Neither of you has to.",
      "The minimum viable bedtime: pajamas, teeth, one book (or one song), lights out. That's it. On your worst nights, that's the whole routine. On better nights, you can add. But the floor is: pajamas, teeth, book, done. Everything else is optional.",
    ],
    tryThis: "Write your minimum viable bedtime routine on a card and put it in their room. On hard nights, point to the card: 'We're doing the short routine tonight.' No guilt. No negotiation. The card is the authority, not you.",
    remember: "Bedtime doesn't need to be magical. It needs to be predictable. Same routine, same order, every night. The structure carries you when your energy can't.",
  },
  {
    id: "par-sibling-conflict",
    title: "You Don't Have to Referee Every Fight",
    subtitle: "When to intervene and when to step back",
    category: "parenting",
    archetypes: ["quiet-volcano", "burning-engine", "plate-spinner"],
    dimensions: ["emotional-bandwidth", "cognitive-load"],
    readTime: "2 min",
    body: [
      "They're fighting again. The screaming, the 'she hit me,' the 'it's not fair.' Every fiber of your being wants to either solve it or scream. But here's what developmental psychology tells us: not every sibling conflict requires your intervention.",
      "Children learn conflict resolution BY conflicting. When you referee every disagreement, you become the external regulator they never learn to be for themselves. They learn: 'When there's a problem, mom fixes it.' What they need to learn: 'When there's a problem, I can navigate it.'",
      "When to intervene: physical safety is at risk, one child is consistently being victimized (power imbalance), or the conflict has escalated beyond their developmental capacity to resolve. When to step back: it's verbal, it's age-appropriate, both children have roughly equal power, and no one is in danger.",
      "Stepping back doesn't mean ignoring. It means narrating from a distance: 'I can hear you're both upset. I trust you to figure this out.' Or setting a boundary without solving: 'If you can't share it, I'm putting it away. You decide.' Then walk away. Let them solve it imperfectly.",
    ],
    tryThis: "Next sibling conflict: pause for 30 seconds before intervening. Ask yourself: 'Is anyone unsafe?' If no — try: 'I can hear you're both frustrated. I'm going to give you 2 minutes to work it out before I step in.' You might be surprised.",
    remember: "You don't have to solve every conflict. Children learn regulation BY navigating disagreement. Your job is safety, not constant mediation.",
  },
  {
    id: "par-good-enough-parenting",
    title: "Good Enough Parenting Is Clinically Optimal",
    subtitle: "Why perfection actually harms children",
    category: "parenting",
    archetypes: ["weight-bearer", "the-disappeared", "quiet-volcano"],
    dimensions: ["emotional-bandwidth", "identity-erosion"],
    readTime: "3 min",
    body: [
      "In 1953, pediatrician and psychoanalyst Donald Winnicott introduced a concept that should be on every mother's mirror: the 'good enough mother.' Not the perfect mother. Not the always-present mother. The good enough one. And he argued — with decades of clinical evidence — that good enough is actually optimal.",
      "Here's why: a perfect parent (if one existed) would create a child who never learns to tolerate frustration, never develops resilience, and never discovers their own capacity to cope. Children NEED manageable doses of imperfection to develop psychological strength. Your failures are not just forgivable — they're developmentally necessary.",
      "Good enough means: you meet their needs most of the time (not all of the time). You repair after rupture (not prevent all rupture). You're emotionally available enough (not constantly available). You provide safety and love as a baseline (not perfection as a standard).",
      "Research consistently shows that children thrive with 'good enough' parenting — defined as meeting needs approximately 30-50% of the time in attunement studies. Not 100%. Not 80%. Thirty to fifty percent. The bar is lower than you think. And you're almost certainly already clearing it.",
      "Every time you beat yourself up for not being perfect, you're measuring yourself against a standard that would actually harm your child if you met it. Your imperfection is not your failure. It's your child's developmental opportunity.",
    ],
    tryThis: "Tonight, instead of reviewing what you did wrong today, ask: 'Did my child feel safe? Did they feel loved? Did I repair when I messed up?' If yes to these — you were good enough. And good enough is clinically optimal.",
    remember: "Winnicott's research is clear: 'good enough' parenting produces healthier children than 'perfect' parenting. Your imperfection isn't failing them — it's building their resilience.",
  },
]