// ============================================================
// Micro-Guides — Batch 3 (guides 51-80)
// ============================================================

import type { MicroGuide } from "./types"

export const MICRO_GUIDES_BATCH3: MicroGuide[] = [
  // ---- EXECUTIVE FUNCTION (5 more) ----
  {
    id: "ef-wall-of-awful",
    title: "The Wall of Awful",
    subtitle: "The task is 3 minutes. The feelings around it are 6 weeks old.",
    category: "executive-function",
    archetypes: ["plate-spinner", "quiet-volcano", "the-disappeared"],
    dimensions: ["cognitive-load", "emotional-bandwidth"],
    tags: ["adhd"],
    readTime: "2 min",
    body: [
      "You need to make a phone call. It would take 3 minutes. You've been avoiding it for 6 weeks. It's not that you're lazy or don't care. It's that between you and the task, there's an invisible wall built from every previous failure, every time you were criticized for being late, every shame spiral attached to this type of task.",
      "ADHD researcher Brendan Mahan calls this the 'Wall of Awful.' It's the accumulated emotional weight that builds up around tasks you've failed at before. The task itself might be simple — but the emotional history attached to it makes it feel insurmountable.",
      "The wall is built brick by brick: the time you forgot and someone was disappointed. The time you did it wrong and felt stupid. The time you were late and got that look. Each experience adds a brick. Eventually, the wall is so high that the 3-minute task feels like climbing Everest.",
      "You can't willpower over the wall. You have to go around it, through it, or shrink it. Going around: pair the task with something pleasant (call while walking outside). Going through: acknowledge the wall out loud ('I'm avoiding this because of shame, not difficulty'). Shrinking it: do the tiniest possible version (open the email, don't reply yet).",
    ],
    tryThis: "Name one task you've been avoiding. Then ask: 'What's the emotional history here? What am I actually afraid of — the task, or the feelings attached to it?' Naming the wall often shrinks it enough to step over.",
    remember: "The task isn't hard. The feelings attached to it are. Name the wall. Then find a way around, through, or under it.",
  },
  {
    id: "ef-body-doubling",
    title: "Why You Can Only Clean When Someone's Watching",
    subtitle: "It's not weird. Your brain just works better with someone nearby.",
    category: "executive-function",
    archetypes: ["plate-spinner", "storm-weatherer", "running-on-empty"],
    dimensions: ["cognitive-load", "system-friction"],
    tags: ["adhd"],
    readTime: "2 min",
    body: [
      "Alone, you can't start. But the moment someone else is in the room — even if they're doing something completely different — suddenly you can function. You can clean, organize, make calls, do paperwork. It's like their presence flips a switch in your brain. This isn't weird. It's called body doubling.",
      "Body doubling works because ADHD brains struggle with internal motivation but respond well to external cues. Another person's presence provides: a subtle sense of accountability, a mirror for 'normal' behavior, reduced isolation (which worsens executive dysfunction), and a grounding anchor that keeps your brain from floating away.",
      "This is why you could study in coffee shops but not at home. Why you clean before guests arrive but not for yourself. Why work feels easier in an office than remotely. Your brain needs external structure that it can't generate internally.",
      "Body doubling doesn't require the other person to help, supervise, or even know what you're doing. They just need to exist in your space. A friend on FaceTime while you fold laundry. A YouTube 'study with me' video. Your partner reading in the same room while you do admin. The presence is the mechanism.",
    ],
    tryThis: "Next time you're stuck on a task: call a friend and say 'Can you just stay on the phone while I do this thing? You don't have to talk.' Or put on a 'body doubling' livestream. Notice how much easier the task becomes with another human present — even virtually.",
    remember: "Needing someone else's presence to function isn't dependency — it's a legitimate ADHD strategy. Your brain needs external anchoring. Use it without shame.",
  },
  {
    id: "ef-revenge-bedtime",
    title: "Revenge Bedtime Procrastination",
    subtitle: "You're not undisciplined. You're reclaiming the only time that's yours.",
    category: "executive-function",
    archetypes: ["the-disappeared", "running-on-empty", "invisible-architect"],
    dimensions: ["cognitive-load", "identity-erosion", "physical-depletion"],
    tags: ["adhd", "universal"],
    readTime: "2 min",
    body: [
      "It's 11pm. You're exhausted. You should be asleep. Instead, you're scrolling, watching, reading — anything to extend this quiet window where no one needs you. You know you'll pay for it tomorrow. You do it anyway. Every night.",
      "This is revenge bedtime procrastination — and it's not a discipline failure. It's a rational response to a day where you had zero autonomy. When every waking hour belongs to someone else (children, partner, work, household), the night becomes the only time that's YOURS. Staying up is how you reclaim a sense of self.",
      "The 'revenge' is against a day that gave you nothing. Your brain is saying: 'I refuse to end this day without having one moment that was mine.' The cost (exhaustion tomorrow) feels worth it because the alternative (going to sleep without any personal time) feels like erasure.",
      "The fix isn't 'just go to bed earlier.' The fix is building personal time INTO the day so you don't have to steal it from sleep. Even 15 minutes of protected 'you time' during waking hours can reduce the compulsion to stay up. Your brain needs to know it'll get something — it doesn't have to be at midnight.",
    ],
    tryThis: "Tomorrow, protect 15 minutes during the day that are explicitly yours — not productive, not for anyone else. Read, scroll, stare at the wall. Whatever you want. Then notice if the pull to stay up late is slightly less intense. You're giving your brain what it's been stealing from sleep.",
    remember: "You stay up late because the day gave you nothing that was yours. The fix isn't more discipline — it's more autonomy during waking hours.",
  },
  {
    id: "ef-urgency-dependency",
    title: "Why You Only Function Under Pressure",
    subtitle: "You only function under deadline pressure. Here's why.",
    category: "executive-function",
    archetypes: ["plate-spinner", "burning-engine", "storm-weatherer"],
    dimensions: ["cognitive-load", "physical-depletion"],
    tags: ["adhd"],
    readTime: "2 min",
    body: [
      "The deadline is tomorrow. Suddenly, after weeks of paralysis, you're a machine. Focused, productive, unstoppable. You produce your best work in the final hours. Then you crash. And the cycle repeats.",
      "This isn't procrastination in the traditional sense. It's urgency dependency — your brain's reliance on adrenaline to compensate for insufficient dopamine. When a deadline creates urgency, your body releases adrenaline and norepinephrine, which temporarily boost the same neurotransmitters that ADHD brains lack. Urgency is self-medication.",
      "The problem: this works in the short term but destroys you long-term. The adrenaline crash after the deadline is real. The chronic stress of last-minute functioning damages your health. And the pattern reinforces itself — your brain learns that it only needs to activate under threat, so it stops activating any other time.",
      "Breaking urgency dependency doesn't mean eliminating deadlines. It means creating artificial urgency for non-urgent tasks: shorter timers, accountability partners, public commitments, or breaking large tasks into small ones with immediate deadlines. Give your brain the urgency signal without the actual emergency.",
    ],
    tryThis: "Next time you have a task with a distant deadline: set a 25-minute timer and tell yourself 'I'm only doing this for 25 minutes.' The time constraint creates artificial urgency. Your brain doesn't know the difference between real and manufactured pressure — it just needs the signal.",
    remember: "You're not lazy until the last minute — you're dopamine-deficient until adrenaline compensates. Create artificial urgency instead of waiting for real emergencies.",
  },
  {
    id: "ef-procrastination-emotion",
    title: "Procrastination Is Emotional, Not Logical",
    subtitle: "The task isn't the problem. The feeling attached to it is.",
    category: "executive-function",
    archetypes: ["plate-spinner", "quiet-volcano", "the-disappeared"],
    dimensions: ["cognitive-load", "emotional-bandwidth"],
    tags: ["adhd"],
    readTime: "2 min",
    body: [
      "You're not procrastinating because you're lazy. You're not procrastinating because you don't care. You're procrastinating because the task is attached to a feeling you don't want to feel — and your brain is protecting you from that feeling by avoiding the task.",
      "Research by Dr. Tim Pychyl and Dr. Fuschia Sirois shows that procrastination is fundamentally an emotion regulation problem, not a time management problem. We avoid tasks that trigger: anxiety (what if I fail?), boredom (this is unstimulating), frustration (this is hard), resentment (I shouldn't have to do this), or shame (I should have done this already).",
      "For ADHD brains, this is amplified because emotional regulation is already impaired. You feel the negative emotion more intensely AND you have fewer resources to push through it. The avoidance isn't a choice — it's your brain's automatic response to emotional discomfort.",
      "The intervention isn't 'just do it.' It's: identify the emotion, validate it ('of course I'm avoiding this — it makes me feel anxious'), and then ask 'what's the smallest possible action that would reduce this feeling?' Often, starting — even for 2 minutes — dissolves the emotional barrier because the anticipated feeling was worse than the actual experience.",
    ],
    tryThis: "Pick something you're procrastinating on. Ask: 'What feeling am I avoiding by not doing this?' Name it specifically. Then commit to 2 minutes only. Not finishing — just starting. The feeling usually dissolves once you're in motion.",
    remember: "You're not avoiding the task. You're avoiding the feeling attached to it. Name the feeling, then start for 2 minutes. Motion dissolves what avoidance amplifies.",
  },

  // ---- EMOTIONAL REGULATION (4 more) ----
  {
    id: "er-emotional-permanence",
    title: "This Feeling Will Not Last Forever",
    subtitle: "When you're in it, it feels like forever. It's not.",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "burning-engine", "weight-bearer"],
    dimensions: ["emotional-bandwidth"],
    tags: ["adhd"],
    readTime: "2 min",
    body: [
      "When you're in it — the rage, the despair, the overwhelm — it feels like it will never end. Like this is your permanent state. Like you've always felt this way and always will. This isn't dramatic. It's a feature of how ADHD brains process emotions.",
      "Neurotypical brains maintain 'emotional object permanence' — the ability to remember that other emotional states exist even while experiencing a current one. When they're sad, they can recall that they've been happy before and will be again. ADHD brains often can't do this. The current emotion fills the entire screen.",
      "This is why a bad morning can feel like a bad life. Why one fight with your partner feels like the relationship is over. Why one parenting failure feels like you've ruined your children permanently. The emotion isn't just big — it's all-consuming. There's no room for perspective.",
      "The intervention is external reminders of other states. A note on your mirror: 'This feeling is temporary.' A photo from a good day on your phone. A text from a friend saved for hard moments. You need evidence from outside the current emotional state because your brain can't generate it from inside.",
    ],
    tryThis: "Right now, while you're NOT in crisis: write yourself a note for when you are. 'This feeling will pass. You've felt this before and it ended. You are not your worst moment.' Put it somewhere you'll find it when you need it.",
    remember: "The current emotion feels permanent because your brain can't access other emotional states while it's activated. It's lying about 'forever.' This will pass.",
  },
  {
    id: "er-shame-avoidance",
    title: "The Shame Spiral Is Keeping You Stuck",
    subtitle: "Shame says 'you ARE the problem.' That's a lie.",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "the-disappeared", "plate-spinner"],
    dimensions: ["emotional-bandwidth", "identity-erosion", "cognitive-load"],
    tags: ["adhd", "universal"],
    readTime: "3 min",
    body: [
      "You forgot something important. Instead of just fixing it, your brain launches a full investigation: 'Why am I like this? What's wrong with me? Everyone else can manage this. I'm fundamentally broken.' The shame spiral has begun — and ironically, it's now preventing you from addressing the original problem.",
      "Shame is the most paralyzing emotion humans experience. Unlike guilt (which says 'I did something bad' and motivates repair), shame says 'I AM bad' and motivates hiding. When you're in shame, you can't problem-solve, you can't take action, you can't ask for help. You can only freeze, avoid, or self-punish.",
      "The shame-avoidance cycle works like this: you avoid a task → shame builds about the avoidance → shame makes the task feel even more impossible → you avoid harder → more shame accumulates → eventually the shame is so large that the task becomes untouchable. The original 5-minute task is now surrounded by weeks of shame.",
      "Breaking the cycle requires separating the behavior from the identity. 'I forgot' is not 'I am forgetful.' 'I was late' is not 'I am unreliable.' 'I yelled' is not 'I am a bad mother.' The behavior can be addressed. The identity statement just buries you deeper.",
    ],
    tryThis: "Next time shame hits, catch the identity statement ('I'm so stupid/lazy/broken') and rewrite it as a behavior statement ('I forgot this specific thing because my working memory was full'). Behavior is fixable. Identity is a trap.",
    remember: "Shame says 'you ARE the problem.' That's a lie that keeps you stuck. You DID a thing. You are not the thing. Separate behavior from identity.",
  },
  {
    id: "er-crying-when-angry",
    title: "Why You Cry When You're Angry",
    subtitle: "You're furious. So why are you crying?",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "the-disappeared", "burning-engine"],
    dimensions: ["emotional-bandwidth"],
    tags: ["universal", "adhd"],
    readTime: "2 min",
    body: [
      "You're furious. You need to have a serious conversation. You open your mouth and — tears. Not sad tears. Rage tears. Frustration tears. And now you look like you're upset instead of angry, and no one takes you seriously, and you're even MORE frustrated.",
      "Crying when angry is extremely common in women and people with ADHD. It's not weakness or emotional instability. It's your autonomic nervous system's overflow valve. When emotional arousal exceeds your system's capacity to contain it, the excess has to go somewhere. For some people it's yelling. For you, it's tears.",
      "The mechanism: intense emotion activates the sympathetic nervous system (fight/flight). When that activation exceeds a threshold, the parasympathetic system kicks in to regulate — and one of its tools is lacrimation (tear production). Your body is literally trying to calm itself down. The tears are regulation, not breakdown.",
      "This doesn't mean you're not angry. It means your body processes anger through tears instead of through aggression. That's not a flaw — it's actually a less destructive outlet. But it IS frustrating when you need to be taken seriously and your body is undermining your message.",
    ],
    tryThis: "If you need to have a hard conversation and know you'll cry: name it upfront. 'I'm going to cry during this conversation. That doesn't mean I'm sad or backing down. It's how my body processes strong emotion. Please listen to my words, not my tears.'",
    remember: "Frustration tears are your nervous system's overflow valve — not weakness. Your body processes anger through tears instead of aggression. Name it so others understand.",
  },
  {
    id: "er-fine-mask",
    title: "The Cost of Performing 'Fine'",
    subtitle: "You look fine. It's costing you everything.",
    category: "emotional-regulation",
    archetypes: ["quiet-volcano", "the-disappeared", "invisible-architect"],
    dimensions: ["emotional-bandwidth", "identity-erosion", "physical-depletion"],
    tags: ["universal", "adhd", "autism"],
    readTime: "2 min",
    body: [
      "'How are you?' 'Fine!' You say it automatically. At pickup. At work. To your partner. To your mother. You perform 'fine' so convincingly that no one checks further. And the performance is killing you.",
      "Masking — presenting a functional, composed exterior while internally struggling — is exhausting at a neurological level. It requires constant self-monitoring, emotion suppression, behavior modification, and social performance. Each of these uses executive function resources. By the end of a day of masking, you're depleted not from what you did, but from pretending you were okay while doing it.",
      "The cost compounds: because you look fine, no one offers help. Because no one offers help, you carry more alone. Because you carry more alone, you're more depleted. Because you're more depleted, the mask takes more effort. It's a cycle that ends in collapse — the moment you can't hold the mask anymore and everything falls apart 'suddenly' (it wasn't sudden — it was building for months).",
      "Masking also disconnects you from yourself. When you perform 'fine' long enough, you lose access to how you actually feel. The mask becomes the default. And underneath it, the real you — exhausted, angry, grieving, overwhelmed — goes unwitnessed. Even by yourself.",
    ],
    tryThis: "Today, when someone asks how you are, try one honest answer. Not a trauma dump — just honesty. 'Honestly? Today is hard.' or 'I'm running on empty.' One crack in the mask. See what happens when you let someone see you.",
    remember: "The mask keeps you safe but it also keeps you alone. Every performance of 'fine' costs energy and prevents help from reaching you. One honest answer can break the cycle.",
  },

  // ---- PHYSICAL / NERVOUS SYSTEM (3 more) ----
  {
    id: "pns-vagus-nerve",
    title: "Your Vagus Nerve Is the Reset Button",
    subtitle: "Cold water, long exhales, humming — your body's reset button.",
    category: "physical-nervous-system",
    archetypes: ["quiet-volcano", "burning-engine", "storm-weatherer"],
    dimensions: ["emotional-bandwidth", "physical-depletion"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "There's a nerve that runs from your brainstem through your face, throat, heart, lungs, and gut. It's called the vagus nerve, and it's the master switch between your stress response (sympathetic) and your rest response (parasympathetic). Stimulating it is the fastest way to shift from activated to calm.",
      "When your vagus nerve is stimulated, it sends a 'safe' signal to your entire body: heart rate drops, breathing slows, digestion resumes, muscles relax, and your prefrontal cortex comes back online. This isn't meditation or mindfulness — it's direct nervous system manipulation through physical input.",
      "The fastest vagal stimulation techniques: cold water on your face (activates the dive reflex — 30 seconds to shift), humming or singing (vibrates the vagus nerve in your throat), slow exhale breathing (exhale longer than inhale — 4 in, 6-8 out), gargling vigorously, or placing your hand on your chest with gentle pressure.",
      "These work even when you're too activated to 'think your way calm.' That's the point — they bypass cognition entirely and work directly on the nervous system. You don't have to believe in them or be in the right mindset. You just have to do the physical action.",
    ],
    tryThis: "Right now: breathe in for 4 counts, out for 8 counts. Do it 5 times. Notice your shoulders drop, your jaw unclench, your heart rate slow. That's your vagus nerve activating. Remember this for the next time you're about to explode.",
    remember: "You have a physical reset button. Cold water, long exhales, humming — these bypass your thinking brain and directly calm your nervous system. Use them before trying to think or talk.",
  },
  {
    id: "pns-cant-relax",
    title: "Why You Can't Relax Even When You Have Time",
    subtitle: "The kids are gone. The house is quiet. You still can't stop.",
    category: "physical-nervous-system",
    archetypes: ["invisible-architect", "burning-engine", "weight-bearer"],
    dimensions: ["physical-depletion", "system-friction"],
    tags: ["universal", "trauma"],
    readTime: "2 min",
    body: [
      "The kids are at grandma's. The house is quiet. You have 3 hours to yourself. And you can't relax. You're restless, anxious, making lists in your head, feeling guilty, or just... vibrating. The opportunity for rest is here but your body won't take it.",
      "This is hypervigilance — your nervous system stuck in 'scanning' mode. When you've been the person responsible for everything for long enough, your brain adapts by staying permanently alert. It's watching for the next need, the next crisis, the next thing that requires your attention. Even when there's nothing to watch for, the scanning continues.",
      "Hypervigilance is a trauma response that's been normalized by motherhood. Your body learned: 'If I stop watching, something bad happens.' Maybe a child got hurt when you looked away. Maybe things fell apart when you rested. Your nervous system concluded: rest is dangerous. Vigilance is survival.",
      "The inability to relax isn't a personality trait ('I'm just not good at doing nothing'). It's a nervous system state that can be shifted — but not through willpower. It requires proving to your body, repeatedly, that rest is safe. That nothing catastrophic happens when you stop scanning. This takes time and practice.",
    ],
    tryThis: "Next time you have free time and can't relax: set a timer for 10 minutes. Lie down. Tell yourself: 'For 10 minutes, nothing is my responsibility. If something happens, it can wait 10 minutes.' Practice tolerating the discomfort of not-scanning. It gets easier.",
    remember: "You can't relax because your nervous system believes rest is dangerous. It's not a personality flaw — it's hypervigilance. Prove to your body that stopping is safe, one small window at a time.",
  },
  {
    id: "pns-exercise-paradox",
    title: "Why Exercise Helps But You Can't Start It",
    subtitle: "It helps. You know it helps. You still can't make yourself do it.",
    category: "physical-nervous-system",
    archetypes: ["running-on-empty", "plate-spinner", "the-disappeared"],
    dimensions: ["physical-depletion", "cognitive-load"],
    tags: ["adhd"],
    readTime: "2 min",
    body: [
      "Every piece of advice says 'exercise helps ADHD.' And it does — research shows 20 minutes of moderate exercise can improve executive function for 2-4 hours afterward. It's essentially free medication. There's just one problem: starting exercise requires the exact executive function that exercise is supposed to improve. It's a cruel catch-22.",
      "To exercise, you need: task initiation (starting), time management (fitting it in), working memory (remembering to do it), emotional regulation (pushing through discomfort), and planning (what to do, where, when). These are ALL executive function skills. Telling an ADHD brain to 'just exercise' is like telling someone with a broken leg to walk to the pharmacy for crutches.",
      "The workaround isn't motivation or discipline. It's removing every barrier between you and movement. Not 'go to the gym for an hour' but 'walk to the end of the street.' Not 'follow a workout plan' but 'put on shoes and step outside.' Not 'exercise at 6am' but 'move your body at whatever time you happen to have energy.'",
      "The lowest barrier version: movement that doesn't feel like exercise. Dancing in the kitchen. Walking while on a phone call. Doing squats while waiting for the kettle. Playing chase with your kids. Your brain doesn't need a 'workout' — it needs 20 minutes of elevated heart rate. How you get there doesn't matter.",
    ],
    tryThis: "Don't plan exercise. Instead: right now, stand up and walk for 5 minutes. Around the house, around the block, anywhere. No gear, no plan, no commitment beyond 5 minutes. Notice how your brain feels after. That's the evidence your body needs to do it again.",
    remember: "Exercise helps ADHD but requires ADHD skills to start. Remove every barrier. Make it tiny. Make it now. 5 minutes of movement beats 0 minutes of a perfect workout plan.",
  },

  // ---- RELATIONSHIPS (3 more) ----
  {
    id: "rel-default-parent",
    title: "The Default Parent Trap",
    subtitle: "Even when your partner is right there, they ask YOU.",
    category: "relationships",
    archetypes: ["invisible-architect", "the-disappeared", "weight-bearer"],
    dimensions: ["system-friction", "identity-erosion"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "'Mom, where are my shoes?' 'Mom, what's for dinner?' 'Mom, can I have a playdate?' Even when your partner is sitting right there. Even when they're perfectly capable of answering. The question comes to you. Because you're the default.",
      "The default parent is the one who holds the full mental model of the household: who needs what, when, where everything is, what's coming up, what's running low, who's upset and why. The other parent may participate — but they participate in YOUR system. They help. They don't hold.",
      "How this happens: it starts with biological necessity (pregnancy, breastfeeding, recovery) and then calcifies through repetition. You knew the answers first, so you kept answering. You were faster, so you kept doing. You noticed first, so you kept noticing. Until 'default' became permanent.",
      "The cost isn't just the tasks. It's the cognitive weight of being the household's operating system. Every question directed at you — even ones your partner could answer — is a micro-demand on your working memory. Multiply that by 50 questions a day and you understand why you're depleted by noon.",
    ],
    tryThis: "For one day, redirect. When a child asks you something your partner could answer: 'Ask Dad.' When your partner asks where something is: 'I don't know — where do you think it might be?' You're not being difficult. You're redistributing the cognitive load.",
    remember: "You became the default through repetition, not destiny. Every question you redirect is a small act of redistribution. They can figure it out. Let them.",
  },
  {
    id: "rel-friendship-after-kids",
    title: "Why Your Friendships Faded (and It's Not Your Fault)",
    subtitle: "You didn't become a bad friend. Life made friendship structurally impossible.",
    category: "relationships",
    archetypes: ["the-disappeared", "running-on-empty", "invisible-architect"],
    dimensions: ["identity-erosion", "system-friction"],
    tags: ["universal", "adhd"],
    readTime: "2 min",
    body: [
      "You used to have friends. Close ones. Now you have people you occasionally text back three days late with 'Sorry, just saw this!' You miss them. You feel guilty. You wonder if you're a bad friend or if they've given up on you.",
      "Here's what happened: adult friendship requires three things — proximity, repeated unplanned interaction, and time. Motherhood eliminates all three simultaneously. You're home-bound (no proximity). Your schedule is dictated by children (no spontaneity). Your free time is zero (no availability). The friendships didn't die from neglect. They died from structural impossibility.",
      "For ADHD brains, it's worse: object permanence means friends you don't see regularly literally fade from your awareness. Not from your heart — from your active memory. You love them. You just forget they exist until something reminds you. Then the guilt of the gap prevents you from reaching out.",
      "The friendships aren't gone. They're dormant. And most of your friends are experiencing the same thing. The text you're afraid to send ('I'm sorry I disappeared') is probably the text they've been wanting to send you too.",
    ],
    tryThis: "Send one text today to a friend you've been meaning to contact. Don't apologize for the gap. Just say something real: 'Thinking of you. Life is chaos. Miss you.' That's enough. The thread doesn't have to be continuous to be real.",
    remember: "Your friendships faded because of structural barriers, not because you're a bad friend. The people who love you understand. Reach out without apology.",
  },
  {
    id: "rel-mothers-voice",
    title: "Your Mother's Voice in Your Head",
    subtitle: "That critical voice in your head? It might not be yours.",
    category: "relationships",
    archetypes: ["quiet-volcano", "the-disappeared", "weight-bearer"],
    dimensions: ["emotional-bandwidth", "identity-erosion"],
    tags: ["universal", "trauma"],
    readTime: "3 min",
    body: [
      "You open your mouth and your mother comes out. Her words. Her tone. Her criticism. Maybe directed at your children. Maybe directed at yourself. The voice in your head that says 'you're not doing this right' — whose voice is it really? Often, it's hers.",
      "Intergenerational transmission of parenting patterns is one of the most robust findings in developmental psychology. We internalize our parents' voices — their standards, their criticisms, their fears — and they become our inner monologue. We parent the way we were parented, not because we choose to, but because those neural pathways were laid down first.",
      "This doesn't mean your mother was malicious. She was likely doing her best with her own unprocessed patterns, her own undiagnosed neurodivergence, her own lack of support. Understanding this doesn't excuse harm — but it contextualizes it. She passed down what she received.",
      "The work is separating her voice from yours. When the inner critic speaks, ask: 'Is this MY value, or something I inherited?' When you catch yourself repeating her patterns, pause: 'Is this how I want to parent, or how I was parented?' The awareness itself is the interruption. You can't change what you can't see.",
      "You are not doomed to repeat her patterns. The fact that you're aware of them means you're already breaking the cycle. Every time you choose differently — even imperfectly — you're writing new code over old programming.",
    ],
    tryThis: "Notice your inner critic today. When it speaks, ask: 'Whose voice is this? Is this mine, or did I inherit it?' You don't have to do anything with the answer yet. Just notice. Awareness is the first crack in the pattern.",
    remember: "The critical voice in your head may not be yours. It might be inherited. You can acknowledge where it came from AND choose not to pass it forward. Awareness breaks the cycle.",
    groundingNote: "If exploring your mother's influence brings up grief, anger, or painful memories — that's normal and valid. You don't have to resolve it here. A therapist who works with intergenerational patterns can hold this with you in a way an app cannot.",
  },

  // ---- IDENTITY (2 more) ----
  {
    id: "id-ambivalence-normal",
    title: "Ambivalence About Motherhood Is Normal",
    subtitle: "Both things are true. You love them AND you wish for something else.",
    category: "identity",
    archetypes: ["the-disappeared", "quiet-volcano", "running-on-empty"],
    dimensions: ["identity-erosion", "emotional-bandwidth"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "Sometimes you fantasize about a different life. One without the constant demands, the noise, the weight. Then the guilt hits: 'What kind of mother thinks this?' The answer: a normal one. A human one. An honest one.",
      "Maternal ambivalence — holding simultaneous love and resentment, joy and regret, gratitude and grief — is one of the most universal and least discussed experiences of motherhood. Psychoanalyst Rozsika Parker argued that ambivalence isn't a failure of love. It's a sign of its complexity.",
      "The cultural demand is that mothers feel only one thing: grateful, fulfilled, complete. Any deviation from this is treated as pathology or ingratitude. But human beings don't feel one thing about anything complex. You don't feel one thing about your career, your body, your childhood. Why would you feel one thing about the most demanding role of your life?",
      "The ambivalence isn't the problem. The silence about it is. When you can't name it, it festers into shame. When you can name it — 'I love my children AND I sometimes wish I had a different life' — it loses its power to make you feel broken.",
    ],
    tryThis: "Say to yourself (or write): 'I love my children AND ___.' Fill in the honest thing. The thing you're not supposed to feel. Let both be true. That's not contradiction — that's the full complexity of being a person.",
    remember: "Ambivalence is not a failure of love. It's a sign of its complexity. You can love your children completely and still wish for something different. Both are true. Both are human.",
  },
  {
    id: "id-productivity-identity",
    title: "You Are Not What You Produce",
    subtitle: "You feel worthless on days you 'didn't do anything.' Let's talk about that.",
    category: "identity",
    archetypes: ["invisible-architect", "plate-spinner", "running-on-empty"],
    dimensions: ["identity-erosion", "cognitive-load"],
    tags: ["universal", "adhd"],
    readTime: "2 min",
    body: [
      "You feel worthless on days you 'didn't do anything.' You feel guilty resting because you haven't 'earned' it. Your internal value system runs on output: tasks completed, meals made, problems solved, people served. On days the list is short, you are less.",
      "This is productivity as identity — and it's one of the most common and destructive patterns in high-functioning women, especially those with ADHD. Because your brain makes everything harder, you've compensated by doing MORE. Overachieving became your proof of worth. If you're producing, you're valuable. If you're not, you're nothing.",
      "The origin is usually early: being praised for achievement, being valued for helpfulness, learning that love was conditional on performance. The message internalized: 'I am what I do. If I do nothing, I am nothing.' Motherhood intensifies this because the 'doing' is infinite — there's always more to produce.",
      "The reframe is radical and uncomfortable: you have inherent worth that exists independent of your output. You are valuable lying on the couch doing nothing. You are valuable on your worst, least productive day. Your worth is not earned through labor. It exists because you exist.",
    ],
    tryThis: "Today, do one thing that produces nothing. Stare out the window. Lie on the floor. Sit in silence. Notice the discomfort. Notice the voice that says 'you should be doing something.' That voice is the conditioning. You don't have to obey it.",
    remember: "You are not what you produce. Your worth exists independent of your output. Rest is not earned. It's a right. Even on days you 'did nothing' — you are still enough.",
  },

  // ---- SYSTEMS & STRUCTURE (3 more) ----
  {
    id: "sys-sunday-reset",
    title: "The Sunday Reset (15 Minutes That Change Your Week)",
    subtitle: "15 minutes on Sunday that change your entire Monday.",
    category: "systems-structure",
    archetypes: ["plate-spinner", "invisible-architect", "storm-weatherer"],
    dimensions: ["system-friction", "cognitive-load"],
    tags: ["universal", "adhd"],
    readTime: "2 min",
    body: [
      "Monday morning hits and you're already behind. The week feels chaotic before it starts. You're reactive all week because you never got ahead of it. The Sunday Reset changes this — and it takes 15 minutes, not an hour.",
      "The Sunday Reset isn't meal prepping, deep cleaning, or planning a perfect week. It's three things: (1) Look at the calendar — what's non-negotiable this week? (2) Identify the top 3 priorities — if you could only do 3 things, what would matter most? (3) Brain dump — get everything out of your head onto paper.",
      "That's it. 15 minutes. The goal isn't to plan every hour. It's to enter Monday with awareness instead of ambush. When you know what's coming, your brain can prepare. When you're surprised, your brain panics.",
      "For ADHD brains, the Sunday Reset works because it externalizes the week before it starts. Instead of holding it all in working memory (which will fail), you put it on paper (which won't). Monday-you doesn't have to figure out the week — Sunday-you already did.",
    ],
    tryThis: "This Sunday: set a 15-minute timer. Open your calendar. Write down what's happening this week. Pick your top 3. Dump everything else onto a list. Done. Notice how different Monday feels when you're not ambushed.",
    remember: "15 minutes on Sunday saves hours of reactive chaos during the week. You're not planning perfection — you're preventing ambush.",
  },
  {
    id: "sys-launch-pad",
    title: "The Launch Pad Concept",
    subtitle: "Stop searching for keys every morning. One spot. Everything.",
    category: "systems-structure",
    archetypes: ["plate-spinner", "storm-weatherer", "invisible-architect"],
    dimensions: ["system-friction", "cognitive-load"],
    tags: ["adhd"],
    readTime: "2 min",
    body: [
      "Every morning is a scavenger hunt. Keys? Where are the keys? Backpack? Which room? Permission slip? Was it on the counter? Shoes? WHY ARE THERE NEVER MATCHING SHOES? The problem isn't your family. It's that there's no designated 'leaving the house' zone.",
      "The launch pad is a single location — by your front door — where EVERYTHING needed to leave the house lives. Keys, bags, shoes, coats, forms, water bottles. One spot. Non-negotiable. If it's needed to leave, it lives here. If it's not here, it doesn't exist.",
      "This works because it eliminates the search. Your brain doesn't have to remember where things are — it only has to remember one location. And if you build the habit of putting things there the night before (evening reset), morning becomes execution, not investigation.",
      "The launch pad can be: a bench with hooks above it, a shelf by the door, a set of bins, or literally a spot on the floor with a basket. It doesn't have to be Pinterest-worthy. It has to be consistent. Same spot. Every time. No exceptions.",
    ],
    tryThis: "Today: designate a launch pad spot by your front door. Put hooks for keys and bags. Tomorrow morning, notice: did you search for anything? If yes, that thing needs a home at the launch pad. Build it over a week.",
    remember: "One spot. Everything needed to leave the house. No searching, no remembering, no morning scavenger hunts. The launch pad does the thinking for you.",
  },
  {
    id: "sys-emergency-protocol",
    title: "When Everything Collapses: Your Emergency Protocol",
    subtitle: "Write the plan when you're well. Follow it when you're not.",
    category: "systems-structure",
    archetypes: ["weight-bearer", "burning-engine", "storm-weatherer"],
    dimensions: ["system-friction", "physical-depletion", "emotional-bandwidth"],
    tags: ["universal"],
    readTime: "2 min",
    body: [
      "Some days, everything falls apart. You're sick, or the kids are sick, or something happened, or you just woke up and there's nothing in the tank. On these days, you need a plan that requires zero executive function to execute. You need your emergency protocol.",
      "An emergency protocol is a pre-decided set of rules for crisis days. You write it when you're functioning so you can follow it when you're not. It answers every question in advance so your depleted brain doesn't have to decide anything.",
      "Example emergency protocol: Meals = cereal, sandwiches, frozen pizza (no cooking). Clothes = whatever is clean (no matching). Screen time = unlimited (no guilt). Housework = nothing (it can wait). Bedtime = early and simple (pajamas, teeth, bed). Your job today = keep everyone alive and fed. That's it.",
      "The power of the protocol is that it removes decision-making AND removes guilt. You're not 'giving up' — you're following a pre-approved plan. You decided in advance that this is acceptable. Crisis-day-you doesn't have to justify it. She just has to follow it.",
    ],
    tryThis: "Write your emergency protocol right now, while you have capacity. Meals, clothes, screens, housework, bedtime — what's the absolute minimum? Write it on a card. Put it on the fridge. On your next terrible day, point to the card and follow it.",
    remember: "Write the plan when you're well. Follow the plan when you're not. Emergency protocols remove decisions AND guilt simultaneously. Cereal for dinner is a valid protocol.",
  },

  // ---- PARENTING (3 more) ----
  {
    id: "par-gentle-not-gentle",
    title: "Gentle Parenting When You're Not Gentle",
    subtitle: "The books say 'stay calm.' You have nothing left to stay calm WITH.",
    category: "parenting",
    archetypes: ["quiet-volcano", "burning-engine", "weight-bearer"],
    dimensions: ["emotional-bandwidth", "physical-depletion"],
    tags: ["universal", "adhd"],
    readTime: "3 min",
    body: [
      "You've read the books. You know you're supposed to validate feelings, offer choices, stay calm, narrate emotions, hold space. And on your good days, you can. But on your bad days — which are most days — you don't have the bandwidth for gentle parenting. And the gap between the ideal and your reality is crushing you.",
      "Here's what the gentle parenting movement often fails to acknowledge: it requires enormous executive function and emotional regulation resources. Staying calm while a child screams requires a regulated nervous system. Offering choices requires working memory. Validating feelings requires emotional bandwidth. These are all things that are depleted in overwhelmed, neurodivergent mothers.",
      "The dirty secret of gentle parenting content: much of it is created by people with support systems, regulated nervous systems, and one child. It's not designed for a depleted mother of three with ADHD, no support, and a nervous system running on fumes. The advice isn't wrong — it's just not calibrated for your reality.",
      "What works instead: 'good enough' parenting. On your best days, be gentle. On your worst days, be safe. The minimum viable parenting standard is: no one gets hurt, basic needs are met, and you repair after rupture. Everything above that is bonus. And the repair — not the prevention of all rupture — is what actually builds secure attachment.",
    ],
    tryThis: "Give yourself a 'parenting tier' system. Tier 1 (good day): gentle, present, connected. Tier 2 (hard day): safe, fed, basic routine. Tier 3 (crisis day): everyone alive, screens allowed, repair later. Know which tier you're on TODAY and parent accordingly.",
    remember: "Gentle parenting requires resources you may not have today. That's not failure — it's reality. Safe + repair is enough. You don't have to be gentle to be good.",
  },
  {
    id: "par-triggers",
    title: "Your Child Is Triggering Your Childhood",
    subtitle: "Your reaction was too big for the moment. It belongs to a different time.",
    category: "parenting",
    archetypes: ["quiet-volcano", "burning-engine", "the-disappeared"],
    dimensions: ["emotional-bandwidth", "identity-erosion"],
    tags: ["universal", "trauma"],
    readTime: "3 min",
    body: [
      "Your child whines and something inside you snaps — not proportionate to the whining, but to something older. Your child defies you and you feel a rage that belongs to a different time. Your child cries and you feel nothing — numb, disconnected, gone. These disproportionate reactions aren't about your child. They're about your childhood.",
      "Parenting is the most triggering experience most adults will ever have. Your children — through their needs, their emotions, their developmental stages — will systematically activate every unresolved wound from your own childhood. Not because they're trying to. Because their experience mirrors yours at that age, and your nervous system can't tell the difference between then and now.",
      "Common triggers: a child's neediness (if your needs were dismissed), a child's anger (if anger wasn't safe in your home), a child's helplessness (if you had to be self-sufficient too young), a child's joy (if joy was punished or dangerous), a child's defiance (if obedience was survival).",
      "When you're triggered, you're not parenting your child in the present. You're reacting from your past. The child in front of you becomes the child you were — and you respond as your parent did, or as the opposite of your parent (which is still a reaction to them, not a free choice).",
      "The awareness itself is the intervention. When you can say 'I'm triggered right now — this reaction is bigger than this moment' — you create a gap between the trigger and the response. In that gap, you can choose. Not perfectly. But differently than the automatic pattern.",
    ],
    tryThis: "Next time you have a disproportionate reaction to your child: pause and ask 'How old do I feel right now?' If the answer isn't your actual age — you're triggered. The reaction belongs to a younger you. Name it: 'This is old. This isn't about right now.'",
    remember: "Your child will trigger your childhood. That's not their fault or yours. The awareness — 'this reaction is bigger than this moment' — is what breaks the intergenerational cycle.",
    groundingNote: "If this brought up something heavy from your own childhood, you don't have to process it alone. The 'What's Heavy' space is here for you, and a therapist who specializes in intergenerational trauma can help you work through what an app cannot.",
  },
  {
    id: "par-child-adhd",
    title: "When You See Yourself in Your Child",
    subtitle: "You see yourself in them. The struggles no one understood in you.",
    category: "parenting",
    archetypes: ["plate-spinner", "quiet-volcano", "invisible-architect"],
    dimensions: ["cognitive-load", "emotional-bandwidth"],
    tags: ["adhd"],
    readTime: "3 min",
    body: [
      "Your child can't sit still. Or they melt down over transitions. Or they forget everything. Or they're intensely emotional. And you see yourself in them — the struggles you had, the things no one understood, the ways you were punished for a brain that worked differently. It's painful and clarifying at the same time.",
      "Many mothers discover their own ADHD through their child's evaluation. Seeing the diagnostic criteria applied to your child and thinking 'wait — that's me too' is one of the most common pathways to adult female ADHD diagnosis. The recognition is both validating and grief-inducing.",
      "If you see ADHD patterns in your child, you have something most parents don't: lived experience of what it feels like from the inside. You know that 'try harder' doesn't work. You know that the forgetting isn't carelessness. You know that the emotional intensity isn't drama. This knowledge is your superpower as their parent.",
      "What your child needs from you: understanding (not fixing), accommodation (not punishment for brain differences), advocacy (with schools, with family members who don't get it), and modeling (showing them that a brain like theirs can build a good life — imperfectly, with support, but genuinely good).",
      "Important: observing patterns is not diagnosing. If you're concerned, discuss your observations with your child's pediatrician. Frame it as: 'I'm noticing these patterns and I'd like to understand them better.' You're not labeling your child — you're seeking understanding.",
    ],
    tryThis: "If you see yourself in your child's struggles: write down what you wish someone had understood about you at their age. That list is your parenting guide for them. Give them what you didn't get.",
    remember: "Seeing yourself in your child is painful and powerful. Your lived experience of a different brain is their greatest asset — you understand from the inside what others can only observe from the outside.",
  },
]